const express=require('express'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),multer=require('multer'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const db=require('./db');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
const root=path.join(__dirname,'..'),uploads=path.join(root,'uploads');fs.mkdirSync(uploads,{recursive:true});
const upload=multer({dest:uploads,limits:{fileSize:20*1024*1024}});
app.use(express.json({limit:'5mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(root,'public')));app.use('/uploads',express.static(uploads));
const roles={
 'CEO / Owner':['*'],
 'Operations Manager':['dashboard','staff','tasks','reports','kpi','meetings','businesses','inventory','finance','approvals','crm','documents','sales','pos','restaurant'],
 'Finance / Admin':['dashboard','finance','approvals','documents','reports','sales','purchases','inventory'],
 'Sales / Business Development':['dashboard','tasks','crm','kpi','documents','sales','customers'],
 'Business Unit Manager':['dashboard','tasks','staff','reports','kpi','inventory','finance','meetings','sales','purchases','crm','documents','pos','restaurant'],
 'Staff Member':['dashboard','tasks','reports','documents','inventory']};
function tok(u){return{id:u.id,name:u.name,email:u.email,role:u.role,business_unit_id:u.business_unit_id};}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(h.slice(7),SECRET);next();}catch(e){res.status(401).json({error:'Invalid or expired session'});}}
function allow(...p){return(req,res,next)=>{if(req.user.role==='CEO / Owner'||(roles[req.user.role]||[]).includes('*')||p.some(x=>(roles[req.user.role]||[]).includes(x)))return next();res.status(403).json({error:'You do not have permission for this action'});};}
function audit(u,e,id,a,d=''){db.prepare('INSERT INTO audit_log(user_id,entity,entity_id,action,details) VALUES(?,?,?,?,?)').run(u?.id||null,e,id||null,a,d);}
function notify(uid,level,title,message){db.prepare('INSERT INTO notifications(user_id,level,title,message) VALUES(?,?,?,?)').run(uid||null,level,title,message);}
function unitScope(req,field='business_unit_id'){if(req.user.role==='CEO / Owner')return{sql:'',args:[]};if(req.user.business_unit_id)return{sql:` AND ${field}=?`,args:[req.user.business_unit_id]};return{sql:'',args:[]};}
function uid(){return crypto.randomBytes(24).toString('hex');}
function num(v){return Number(v||0);}
function nextNo(prefix,table,col){const n=db.prepare(`SELECT COUNT(*) c FROM ${table}`).get().c+1;return `${prefix}-${new Date().getFullYear()}-${String(n).padStart(5,'0')}`;}

app.get('/api/health',(req,res)=>res.json({ok:true,version:'5.0.0'}));
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE lower(email)=lower(?) AND active=1').get(email||'');if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'Invalid email or password'});const t=jwt.sign(tok(u),SECRET,{expiresIn:'12h'});audit(u,'auth',u.id,'login');res.json({token:t,user:tok(u)});});
app.post('/api/auth/forgot',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE lower(email)=lower(?) AND active=1').get(req.body.email||'');if(!u)return res.json({message:'If the account exists, a reset link has been created.'});const token=uid();db.prepare('INSERT INTO password_resets(user_id,token,expires_at) VALUES(?,?,datetime(\'now\',\'+30 minutes\'))').run(u.id,token);const base=`${req.protocol}://${req.get('host')}`;res.json({message:'Reset link created.',reset_url:`${base}/?reset=${token}`});});
app.post('/api/auth/reset',(req,res)=>{const r=db.prepare('SELECT * FROM password_resets WHERE token=? AND used=0 AND datetime(expires_at)>datetime(\'now\')').get(req.body.token||'');if(!r)return res.status(400).json({error:'Reset token is invalid or expired'});if(!req.body.password||req.body.password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(bcrypt.hashSync(req.body.password,12),r.user_id);db.prepare('UPDATE password_resets SET used=1 WHERE id=?').run(r.id);res.json({ok:true});});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));

app.get('/api/dashboard',auth,allow('dashboard'),(req,res)=>{const s=unitScope(req,'f.business_unit_id');const where=s.sql?' WHERE 1=1'+s.sql:' WHERE 1=1';const rev=db.prepare(`SELECT COALESCE(SUM(amount),0)v FROM finance_entries f${where} AND f.type='Revenue'`).get(...s.args).v;const exp=db.prepare(`SELECT COALESCE(SUM(amount),0)v FROM finance_entries f${where} AND f.type='Expense'`).get(...s.args).v;const sales=db.prepare(`SELECT COALESCE(SUM(total),0)v FROM sales s${s.sql.replace('f.','s.')}`).get(...s.args).v;const gp=db.prepare(`SELECT COALESCE(SUM(gross_profit),0)v FROM sales s${s.sql.replace('f.','s.')}`).get(...s.args).v;const pending=db.prepare('SELECT COUNT(*)c FROM approvals WHERE status=\'Pending\'').get().c;const overdue=db.prepare('SELECT COUNT(*)c FROM tasks WHERE status NOT IN (\'Completed\',\'Cancelled\') AND due_date IS NOT NULL AND date(due_date)<date(\'now\')').get().c;const low=db.prepare('SELECT COUNT(*)c FROM products WHERE active=1 AND item_type=\'PRODUCT\' AND current_stock<=reorder_level').get().c;const unread=db.prepare('SELECT COUNT(*)c FROM notifications WHERE (user_id IS NULL OR user_id=?) AND read_at IS NULL').get(req.user.id).c;const units=db.prepare(`SELECT b.id,b.name,b.status,COALESCE((SELECT SUM(total) FROM sales s WHERE s.business_unit_id=b.id AND s.status='Completed'),0)sales,COALESCE((SELECT SUM(gross_profit) FROM sales s WHERE s.business_unit_id=b.id AND s.status='Completed'),0)gross_profit,COALESCE((SELECT SUM(amount) FROM finance_entries f WHERE f.business_unit_id=b.id AND f.type='Expense'),0)expenses,COALESCE((SELECT SUM(p.current_stock*p.cost_price) FROM products p WHERE p.business_unit_id=b.id AND p.active=1),0)inventory_value FROM business_units b ORDER BY b.name`).all();res.json({revenue:rev,expenses:exp,net:rev-exp,sales,gross_profit:gp,pending,overdue,low,unread,units});});
app.get('/api/dashboard/timeseries',auth,allow('dashboard'),(req,res)=>{const rows=db.prepare(`SELECT date(created_at) d,COALESCE(SUM(total),0)sales,COALESCE(SUM(gross_profit),0)profit FROM sales WHERE status='Completed' AND date(created_at)>=date('now','-29 days') GROUP BY date(created_at) ORDER BY d`).all();res.json(rows);});

app.get('/api/business-units',auth,(req,res)=>res.json(db.prepare(`SELECT b.*,u.name manager_name FROM business_units b LEFT JOIN users u ON u.id=b.manager_id ORDER BY b.name`).all()));
app.post('/api/business-units',auth,allow('businesses'),(req,res)=>{if(!req.body.name)return res.status(400).json({error:'Business name is required'});try{const r=db.prepare('INSERT INTO business_units(name,manager_id,status,notes) VALUES(?,?,?,?)').run(req.body.name,req.body.manager_id||null,req.body.status||'Active',req.body.notes||'');audit(req.user,'business_unit',r.lastInsertRowid,'create',req.body.name);res.json({id:r.lastInsertRowid});}catch(e){res.status(400).json({error:'Business unit already exists'});}});
app.put('/api/business-units/:id',auth,allow('businesses'),(req,res)=>{db.prepare('UPDATE business_units SET name=COALESCE(?,name),manager_id=?,status=COALESCE(?,status),notes=COALESCE(?,notes) WHERE id=?').run(req.body.name||null,req.body.manager_id||null,req.body.status||null,req.body.notes||null,req.params.id);audit(req.user,'business_unit',req.params.id,'update',JSON.stringify(req.body));res.json({ok:true});});

app.delete('/api/business-units/:id',auth,allow('businesses'),(req,res)=>{const b=db.prepare('SELECT * FROM business_units WHERE id=?').get(req.params.id);if(!b)return res.status(404).json({error:'Business unit not found'});const refs=db.prepare('SELECT COUNT(*) c FROM products WHERE business_unit_id=?').get(b.id).c+db.prepare('SELECT COUNT(*) c FROM sales WHERE business_unit_id=?').get(b.id).c+db.prepare('SELECT COUNT(*) c FROM finance_entries WHERE business_unit_id=?').get(b.id).c;if(refs>0)return res.status(400).json({error:'Business has historical records. Set it to Closed instead of deleting it.'});db.prepare('DELETE FROM business_units WHERE id=?').run(b.id);audit(req.user,'business_unit',b.id,'delete',b.name);res.json({ok:true});});

app.get('/api/users',auth,allow('staff'),(req,res)=>res.json(db.prepare(`SELECT u.id,u.name,u.email,u.role,u.business_unit_id,b.name business_unit,u.active,u.created_at FROM users u LEFT JOIN business_units b ON b.id=u.business_unit_id ORDER BY u.name`).all()));
app.post('/api/users',auth,allow('staff'),(req,res)=>{const {name,email,password,role,business_unit_id}=req.body;if(!name||!email||!password||!role)return res.status(400).json({error:'Name, email, password and role are required'});try{const r=db.prepare('INSERT INTO users(name,email,password_hash,role,business_unit_id) VALUES(?,?,?,?,?)').run(name,email,bcrypt.hashSync(password,12),role,business_unit_id||null);notify(r.lastInsertRowid,'info','Welcome to Blue Ocean','Your account has been created.');audit(req.user,'user',r.lastInsertRowid,'create',email);res.json({id:r.lastInsertRowid});}catch(e){res.status(400).json({error:'Email already exists'});}});

app.put('/api/users/:id',auth,allow('staff'),(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.params.id);if(!u)return res.status(404).json({error:'User not found'});db.prepare('UPDATE users SET name=?,email=?,role=?,business_unit_id=?,active=? WHERE id=?').run(req.body.name??u.name,req.body.email??u.email,req.body.role??u.role,req.body.business_unit_id||null,req.body.active===undefined?u.active:(req.body.active?1:0),u.id);if(req.body.password)db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(bcrypt.hashSync(req.body.password,12),u.id);audit(req.user,'user',u.id,'update',u.email);res.json({ok:true});});
app.delete('/api/users/:id',auth,allow('staff'),(req,res)=>{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({error:'You cannot deactivate your own account'});const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.params.id);if(!u)return res.status(404).json({error:'User not found'});db.prepare('UPDATE users SET active=0 WHERE id=?').run(u.id);audit(req.user,'user',u.id,'deactivate',u.email);res.json({ok:true});});

app.get('/api/tasks',auth,allow('tasks'),(req,res)=>{let q=`SELECT t.*,u.name owner,b.name business_unit FROM tasks t JOIN users u ON u.id=t.owner_id LEFT JOIN business_units b ON b.id=t.business_unit_id WHERE 1=1`;const s=unitScope(req,'t.business_unit_id');q+=s.sql;const args=[...s.args];if(req.user.role==='Staff Member'){q+=' AND t.owner_id=?';args.push(req.user.id);}res.json(db.prepare(q+' ORDER BY CASE t.priority WHEN \'Critical\' THEN 1 WHEN \'High\' THEN 2 WHEN \'Normal\' THEN 3 ELSE 4 END,t.due_date').all(...args));});
app.post('/api/tasks',auth,allow('tasks'),(req,res)=>{const {title,owner_id,business_unit_id,priority='Normal',due_date,expected_result='',recurring='None'}=req.body;if(!title||!owner_id)return res.status(400).json({error:'Task title and owner are required'});const r=db.prepare('INSERT INTO tasks(title,owner_id,business_unit_id,priority,due_date,expected_result,recurring,created_by) VALUES(?,?,?,?,?,?,?,?)').run(title,owner_id,business_unit_id||null,priority,due_date||null,expected_result,recurring,req.user.id);notify(owner_id,'info','New task assigned',title);audit(req.user,'task',r.lastInsertRowid,'create',title);res.json({id:r.lastInsertRowid});});
app.put('/api/tasks/:id',auth,allow('tasks'),(req,res)=>{const t=db.prepare('SELECT * FROM tasks WHERE id=?').get(req.params.id);if(!t)return res.status(404).json({error:'Task not found'});if(req.user.role==='Staff Member'&&t.owner_id!==req.user.id)return res.status(403).json({error:'Not your task'});db.prepare('UPDATE tasks SET title=COALESCE(?,title),owner_id=?,business_unit_id=?,status=COALESCE(?,status),priority=COALESCE(?,priority),due_date=COALESCE(?,due_date),expected_result=COALESCE(?,expected_result) WHERE id=?').run(req.body.title??t.title,req.body.owner_id||null,req.body.business_unit_id||null,req.body.status||null,req.body.priority||null,req.body.due_date||null,req.body.expected_result||null,t.id);db.prepare('INSERT INTO task_history(task_id,user_id,action,note) VALUES(?,?,?,?)').run(t.id,req.user.id,'update',JSON.stringify(req.body));audit(req.user,'task',t.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/tasks/:id',auth,allow('tasks'),(req,res)=>{const t=db.prepare('SELECT * FROM tasks WHERE id=?').get(req.params.id);if(!t)return res.status(404).json({error:'Task not found'});if(req.user.role==='Staff Member'&&t.owner_id!==req.user.id)return res.status(403).json({error:'Not your task'});db.prepare('DELETE FROM tasks WHERE id=?').run(t.id);audit(req.user,'task',t.id,'delete',t.title);res.json({ok:true});});

app.get('/api/products',auth,allow('inventory','sales','pos'),(req,res)=>{let q=`SELECT p.*,b.name business_unit FROM products p JOIN business_units b ON b.id=p.business_unit_id WHERE p.active=1`;const s=unitScope(req,'p.business_unit_id');q+=s.sql;res.json(db.prepare(q+' ORDER BY b.name,p.name').all(...s.args));});
app.post('/api/products',auth,allow('inventory'),(req,res)=>{const {business_unit_id,sku,name,category='General',supplier='',item_type='PRODUCT',unit='pcs',opening_stock=0,reorder_level=0,cost_price=0,selling_price=0,tax_rate=0}=req.body;if(!business_unit_id||!sku||!name)return res.status(400).json({error:'Business, SKU and name are required'});try{const r=db.prepare('INSERT INTO products(business_unit_id,sku,name,category,supplier,item_type,unit,opening_stock,current_stock,reorder_level,cost_price,selling_price,tax_rate) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(business_unit_id,sku,name,category,supplier,item_type,unit,num(opening_stock),num(opening_stock),num(reorder_level),num(cost_price),num(selling_price),num(tax_rate));if(num(opening_stock))db.prepare('INSERT INTO stock_movements(product_id,type,quantity,unit_cost,reason,user_id) VALUES(?,?,?,?,?,?)').run(r.lastInsertRowid,'Opening',num(opening_stock),num(cost_price),'Opening stock',req.user.id);audit(req.user,'product',r.lastInsertRowid,'create',name);res.json({id:r.lastInsertRowid});}catch(e){res.status(400).json({error:'SKU already exists in this business'});}});
app.put('/api/products/:id',auth,allow('inventory'),(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'Product/service not found'});db.prepare(`UPDATE products SET sku=?,name=?,category=?,supplier=?,item_type=?,unit=?,reorder_level=?,cost_price=?,selling_price=?,tax_rate=?,active=? WHERE id=?`).run(req.body.sku??p.sku,req.body.name??p.name,req.body.category??p.category,req.body.supplier??p.supplier,req.body.item_type??p.item_type,req.body.unit??p.unit,num(req.body.reorder_level??p.reorder_level),num(req.body.cost_price??p.cost_price),num(req.body.selling_price??p.selling_price),num(req.body.tax_rate??p.tax_rate),req.body.active===undefined?p.active:(req.body.active?1:0),p.id);audit(req.user,'product',p.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/products/:id',auth,allow('inventory'),(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'Product/service not found'});db.prepare('UPDATE products SET active=0 WHERE id=?').run(p.id);audit(req.user,'product',p.id,'archive',p.name);res.json({ok:true});});

app.post('/api/inventory/move',auth,allow('inventory'),(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=?').get(req.body.product_id);if(!p)return res.status(404).json({error:'Product not found'});let q=num(req.body.quantity);const type=req.body.type||'ADD';if(q<=0)return res.status(400).json({error:'Quantity must be greater than zero'});if(type==='REMOVE'||type==='WASTE'||type==='SALE'){if(p.current_stock<q)return res.status(400).json({error:'Insufficient stock'});q=-q;}db.prepare('UPDATE products SET current_stock=current_stock+? WHERE id=?').run(q,p.id);db.prepare('INSERT INTO stock_movements(product_id,type,quantity,unit_cost,reason,user_id) VALUES(?,?,?,?,?,?)').run(p.id,type,Math.abs(q),p.cost_price,req.body.reason||'',req.user.id);audit(req.user,'inventory',p.id,type,`${Math.abs(q)}`);res.json({ok:true});});
app.get('/api/inventory/movements',auth,allow('inventory'),(req,res)=>{const rows=db.prepare(`SELECT sm.*,p.name product,p.sku,b.name business_unit,u.name user_name FROM stock_movements sm JOIN products p ON p.id=sm.product_id JOIN business_units b ON b.id=p.business_unit_id LEFT JOIN users u ON u.id=sm.user_id ORDER BY sm.created_at DESC LIMIT 300`).all();res.json(rows);});

function createSale(req,res,restaurant=false){const b=restaurant?db.prepare('SELECT id FROM business_units WHERE name=\'MIMI Resturant\'').get()?.id:req.body.business_unit_id;if(!b)return res.status(400).json({error:'Business unit is required'});const items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)return res.status(400).json({error:'Add at least one item'});let subtotal=0,cost=0,tax=0,clean=[];for(const it of items){const p=db.prepare('SELECT * FROM products WHERE id=? AND business_unit_id=?').get(it.product_id,b);if(!p)return res.status(400).json({error:'Invalid item'});const qty=num(it.quantity);if(qty<=0)return res.status(400).json({error:'Invalid quantity'});if(p.item_type==='PRODUCT'&&p.current_stock<qty)return res.status(400).json({error:`Insufficient stock: ${p.name}`});const price=num(it.unit_price||p.selling_price),line=qty*price,tc=qty*p.cost_price,tt=line*(num(p.tax_rate)/100);subtotal+=line;cost+=tc;tax+=tt;clean.push({p,qty,price,line,tt});}const discount=num(req.body.discount),total=Math.max(0,subtotal-discount+tax),gp=total-cost;const invoice=nextNo(restaurant?'MIMI':'INV','sales','id');const sale=db.prepare('INSERT INTO sales(business_unit_id,invoice_no,customer_id,customer_name,order_type,payment_method,subtotal,discount,tax,total,cost_total,gross_profit,receipt_file,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(b,invoice,req.body.customer_id||null,req.body.customer_name||'',req.body.order_type||'Sale',req.body.payment_method||'Cash',subtotal,discount,tax,total,cost,gp,req.body.receipt_file||'',req.body.notes||'',req.user.id);const add=db.prepare('INSERT INTO sale_items(sale_id,product_id,item_type,item_name,quantity,unit_price,unit_cost,tax_rate,line_total) VALUES(?,?,?,?,?,?,?,?,?)');const move=db.prepare('INSERT INTO stock_movements(product_id,type,quantity,unit_cost,reason,reference_type,reference_id,user_id) VALUES(?,?,?,?,?,?,?,?)');for(const x of clean){add.run(sale.lastInsertRowid,x.p.id,x.p.item_type,x.p.name,x.qty,x.price,x.p.cost_price,x.p.tax_rate,x.line);if(x.p.item_type==='PRODUCT'){db.prepare('UPDATE products SET current_stock=current_stock-? WHERE id=?').run(x.qty,x.p.id);move.run(x.p.id,'SALE',x.qty,x.p.cost_price,invoice,'SALE',sale.lastInsertRowid,req.user.id);}}db.prepare('INSERT INTO finance_entries(business_unit_id,type,category,amount,description,status,payment_method,reference,created_by) VALUES(?,?,?,?,?,?,?,?,?)').run(b,'Revenue','Sales',total,`${restaurant?'Restaurant POS':'Sale'} ${invoice}`,'Recorded',req.body.payment_method||'Cash',invoice,req.user.id);audit(req.user,'sale',sale.lastInsertRowid,'create',invoice);res.json({id:sale.lastInsertRowid,invoice,total,gross_profit:gp});}
app.post('/api/sales',auth,allow('sales','pos'),(req,res)=>createSale(req,res,false));
app.get('/api/sales/:id',auth,allow('sales','pos'),(req,res)=>{const s=db.prepare(`SELECT s.*,b.name business_unit FROM sales s JOIN business_units b ON b.id=s.business_unit_id WHERE s.id=?`).get(req.params.id);if(!s)return res.status(404).json({error:'Sale not found'});s.items=db.prepare('SELECT * FROM sale_items WHERE sale_id=? ORDER BY id').all(s.id);res.json(s);});

app.put('/api/sales/:id/void',auth,allow('sales','finance'),(req,res)=>{const s=db.prepare('SELECT * FROM sales WHERE id=?').get(req.params.id);if(!s)return res.status(404).json({error:'Sale not found'});if(s.status==='Voided')return res.json({ok:true});db.prepare("UPDATE sales SET status='Voided' WHERE id=?").run(s.id);db.prepare("UPDATE finance_entries SET status='Voided' WHERE reference=?").run(s.invoice_no);audit(req.user,'sale',s.id,'void',s.invoice_no);res.json({ok:true});});

app.get('/api/sales',auth,allow('sales','pos'),(req,res)=>{let q=`SELECT s.*,b.name business_unit,u.name created_by_name FROM sales s JOIN business_units b ON b.id=s.business_unit_id LEFT JOIN users u ON u.id=s.created_by WHERE 1=1`;const s=unitScope(req,'s.business_unit_id');q+=s.sql;res.json(db.prepare(q+' ORDER BY s.created_at DESC LIMIT 500').all(...s.args));});
app.post('/api/purchases',auth,allow('purchases','inventory'),upload.single('attachment'),(req,res)=>{const b=req.body.business_unit_id,items=JSON.parse(req.body.items||'[]');if(!b||!items.length)return res.status(400).json({error:'Business and items are required'});let total=0,clean=[];for(const it of items){const p=db.prepare('SELECT * FROM products WHERE id=? AND business_unit_id=?').get(it.product_id,b);if(!p)return res.status(400).json({error:'Invalid product'});const q=num(it.quantity),c=num(it.unit_cost||p.cost_price),line=q*c;total+=line;clean.push({p,q,c,line});}const no=nextNo('PO','purchases','id'),file=req.file?.filename||'';const r=db.prepare('INSERT INTO purchases(business_unit_id,purchase_no,supplier_name,payment_method,subtotal,total,attachment_file,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?)').run(b,no,req.body.supplier_name||'',req.body.payment_method||'Cash',total,total,file,req.body.notes||'',req.user.id);const add=db.prepare('INSERT INTO purchase_items(purchase_id,product_id,item_name,quantity,unit_cost,line_total) VALUES(?,?,?,?,?,?)');for(const x of clean){add.run(r.lastInsertRowid,x.p.id,x.p.name,x.q,x.c,x.line);if(x.p.item_type==='PRODUCT'){db.prepare('UPDATE products SET current_stock=current_stock+?,cost_price=? WHERE id=?').run(x.q,x.c,x.p.id);db.prepare('INSERT INTO stock_movements(product_id,type,quantity,unit_cost,reason,reference_type,reference_id,user_id) VALUES(?,?,?,?,?,?,?,?)').run(x.p.id,'PURCHASE',x.q,x.c,no,'PURCHASE',r.lastInsertRowid,req.user.id);}}db.prepare('INSERT INTO finance_entries(business_unit_id,type,category,amount,description,payment_method,reference,receipt_file,created_by) VALUES(?,?,?,?,?,?,?,?,?)').run(b,'Expense','Purchases',total,`Purchase ${no}`,req.body.payment_method||'Cash',no,file,req.user.id);audit(req.user,'purchase',r.lastInsertRowid,'create',no);res.json({id:r.lastInsertRowid,purchase_no:no,total});});
app.put('/api/purchases/:id',auth,allow('purchases','inventory'),(req,res)=>{const p=db.prepare('SELECT * FROM purchases WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'Purchase not found'});db.prepare('UPDATE purchases SET supplier_name=?,payment_method=?,notes=?,status=? WHERE id=?').run(req.body.supplier_name??p.supplier_name,req.body.payment_method??p.payment_method,req.body.notes??p.notes,req.body.status??p.status,p.id);audit(req.user,'purchase',p.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/purchases/:id',auth,allow('purchases','inventory'),(req,res)=>{const p=db.prepare('SELECT * FROM purchases WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'Purchase not found'});db.prepare("UPDATE purchases SET status='Voided' WHERE id=?").run(p.id);audit(req.user,'purchase',p.id,'void',p.purchase_no);res.json({ok:true});});

app.get('/api/purchases',auth,allow('purchases','inventory'),(req,res)=>{let q=`SELECT p.*,b.name business_unit FROM purchases p JOIN business_units b ON b.id=p.business_unit_id WHERE 1=1`;const s=unitScope(req,'p.business_unit_id');q+=s.sql;res.json(db.prepare(q+' ORDER BY p.created_at DESC LIMIT 300').all(...s.args));});

app.get('/api/finance',auth,allow('finance','dashboard'),(req,res)=>{let q=`SELECT f.*,b.name business_unit,u.name created_by_name FROM finance_entries f JOIN business_units b ON b.id=f.business_unit_id LEFT JOIN users u ON u.id=f.created_by WHERE 1=1`;const s=unitScope(req,'f.business_unit_id');q+=s.sql;res.json(db.prepare(q+' ORDER BY f.created_at DESC LIMIT 500').all(...s.args));});
app.post('/api/finance',auth,allow('finance'),upload.single('receipt'),(req,res)=>{const b=req.body.business_unit_id;if(!b)return res.status(400).json({error:'Business unit required'});const r=db.prepare('INSERT INTO finance_entries(business_unit_id,type,category,amount,description,due_date,status,receipt_file,payment_method,reference,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(b,req.body.type||'Expense',req.body.category||'General',num(req.body.amount),req.body.description||'',req.body.due_date||null,req.body.status||'Recorded',req.file?.filename||'',req.body.payment_method||'',req.body.reference||'',req.user.id);audit(req.user,'finance',r.lastInsertRowid,'create',req.body.description||'');res.json({id:r.lastInsertRowid});});
app.get('/api/pnl',auth,allow('finance','dashboard'),(req,res)=>{let units=db.prepare('SELECT id,name FROM business_units ORDER BY name').all();const data=units.map(b=>{const sales=db.prepare('SELECT COALESCE(SUM(total),0)v,COALESCE(SUM(cost_total),0)c,COALESCE(SUM(gross_profit),0)g FROM sales WHERE business_unit_id=? AND status=\'Completed\'').get(b.id);const exp=db.prepare('SELECT COALESCE(SUM(amount),0)v FROM finance_entries WHERE business_unit_id=? AND type=\'Expense\' AND category NOT IN (\'Purchases\')').get(b.id).v;const purchases=db.prepare('SELECT COALESCE(SUM(amount),0)v FROM finance_entries WHERE business_unit_id=? AND type=\'Expense\' AND category=\'Purchases\'').get(b.id).v;return{...b,sales:sales.v,cogs:sales.c,gross_profit:sales.g,operating_expense:exp,purchases,net_profit:sales.g-exp};});res.json(data);});

app.put('/api/finance/:id',auth,allow('finance'),(req,res)=>{const f=db.prepare('SELECT * FROM finance_entries WHERE id=?').get(req.params.id);if(!f)return res.status(404).json({error:'Finance entry not found'});db.prepare('UPDATE finance_entries SET type=?,category=?,amount=?,description=?,due_date=?,status=?,payment_method=?,reference=? WHERE id=?').run(req.body.type??f.type,req.body.category??f.category,num(req.body.amount??f.amount),req.body.description??f.description,req.body.due_date??f.due_date,req.body.status??f.status,req.body.payment_method??f.payment_method,req.body.reference??f.reference,f.id);audit(req.user,'finance',f.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/finance/:id',auth,allow('finance'),(req,res)=>{const f=db.prepare('SELECT * FROM finance_entries WHERE id=?').get(req.params.id);if(!f)return res.status(404).json({error:'Finance entry not found'});db.prepare("UPDATE finance_entries SET status='Voided' WHERE id=?").run(f.id);audit(req.user,'finance',f.id,'void',f.description);res.json({ok:true});});

app.get('/api/approvals',auth,allow('approvals'),(req,res)=>res.json(db.prepare(`SELECT a.*,u.name requester,b.name business_unit,d.name decision_by_name FROM approvals a LEFT JOIN users u ON u.id=a.requester_id LEFT JOIN business_units b ON b.id=a.business_unit_id LEFT JOIN users d ON d.id=a.decided_by ORDER BY a.created_at DESC`).all()));
app.post('/api/approvals',auth,allow('approvals','finance'),upload.single('attachment'),(req,res)=>{const r=db.prepare('INSERT INTO approvals(type,requester_id,business_unit_id,amount,reason,attachment_file) VALUES(?,?,?,?,?,?)').run(req.body.type||'General',req.user.id,req.body.business_unit_id||null,num(req.body.amount),req.body.reason||'',req.file?.filename||'');const ceos=db.prepare('SELECT id FROM users WHERE role=\'CEO / Owner\' AND active=1').all();ceos.forEach(x=>notify(x.id,'warning','Approval requested',`${req.body.type||'Request'} requires review.`));audit(req.user,'approval',r.lastInsertRowid,'create');res.json({id:r.lastInsertRowid});});
app.put('/api/approvals/:id',auth,allow('approvals'),(req,res)=>{const st=req.body.status;if(!['Approved','Rejected','Pending'].includes(st))return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE approvals SET status=?,decided_by=?,decided_at=CURRENT_TIMESTAMP,current_step=? WHERE id=?').run(st,req.user.id,st==='Pending'?'Finance Check':'Completed',req.params.id);const a=db.prepare('SELECT * FROM approvals WHERE id=?').get(req.params.id);notify(a.requester_id,st==='Approved'?'info':'critical',`Approval ${st}`,`Your request has been ${st.toLowerCase()}.`);audit(req.user,'approval',a.id,st);res.json({ok:true});});

app.get('/api/crm',auth,allow('crm','customers'),(req,res)=>{let q=`SELECT c.*,b.name business_unit,u.name owner_name FROM customers c LEFT JOIN business_units b ON b.id=c.business_unit_id LEFT JOIN users u ON u.id=c.owner_id WHERE 1=1`;const s=unitScope(req,'c.business_unit_id');q+=s.sql;res.json(db.prepare(q+' ORDER BY c.next_followup,c.created_at DESC').all(...s.args));});
app.post('/api/crm',auth,allow('crm','customers'),(req,res)=>{const r=db.prepare('INSERT INTO customers(company,contact,phone,email,source,business_unit_id,stage,potential_value,next_followup,notes,owner_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(req.body.company,req.body.contact||'',req.body.phone||'',req.body.email||'',req.body.source||'',req.body.business_unit_id||null,req.body.stage||'Lead',num(req.body.potential_value),req.body.next_followup||null,req.body.notes||'',req.user.id);audit(req.user,'customer',r.lastInsertRowid,'create');res.json({id:r.lastInsertRowid});});

app.put('/api/crm/:id',auth,allow('crm','customers'),(req,res)=>{const c=db.prepare('SELECT * FROM customers WHERE id=?').get(req.params.id);if(!c)return res.status(404).json({error:'Customer not found'});db.prepare('UPDATE customers SET company=?,contact=?,phone=?,email=?,source=?,business_unit_id=?,stage=?,potential_value=?,next_followup=?,notes=? WHERE id=?').run(req.body.company??c.company,req.body.contact??c.contact,req.body.phone??c.phone,req.body.email??c.email,req.body.source??c.source,req.body.business_unit_id||null,req.body.stage??c.stage,num(req.body.potential_value??c.potential_value),req.body.next_followup??c.next_followup,req.body.notes??c.notes,c.id);audit(req.user,'customer',c.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/crm/:id',auth,allow('crm','customers'),(req,res)=>{const c=db.prepare('SELECT * FROM customers WHERE id=?').get(req.params.id);if(!c)return res.status(404).json({error:'Customer not found'});db.prepare('DELETE FROM customers WHERE id=?').run(c.id);audit(req.user,'customer',c.id,'delete',c.company);res.json({ok:true});});

app.get('/api/reports',auth,allow('reports','dashboard'),(req,res)=>{let q=`SELECT r.*,u.name user_name FROM daily_reports r JOIN users u ON u.id=r.user_id ORDER BY r.report_date DESC LIMIT 300`;res.json(db.prepare(q).all());});
app.post('/api/reports',auth,allow('reports'),(req,res)=>{const r=db.prepare(`INSERT INTO daily_reports(user_id,report_date,completed,pending,blockers,tomorrow_priority,need_approval,need_help,status) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,report_date) DO UPDATE SET completed=excluded.completed,pending=excluded.pending,blockers=excluded.blockers,tomorrow_priority=excluded.tomorrow_priority,need_approval=excluded.need_approval,need_help=excluded.need_help,status=excluded.status`).run(req.user.id,req.body.report_date||new Date().toISOString().slice(0,10),req.body.completed||'',req.body.pending||'',req.body.blockers||'',req.body.tomorrow_priority||'',req.body.need_approval?1:0,req.body.need_help||'',req.body.status||'Green');audit(req.user,'daily_report',r.lastInsertRowid,'submit');res.json({ok:true});});
app.get('/api/kpis',auth,allow('kpi','dashboard'),(req,res)=>res.json(db.prepare(`SELECT k.*,u.name user_name,b.name business_unit FROM kpis k LEFT JOIN users u ON u.id=k.user_id LEFT JOIN business_units b ON b.id=k.business_unit_id ORDER BY k.updated_at DESC`).all()));
app.post('/api/kpis',auth,allow('kpi'),(req,res)=>{const r=db.prepare('INSERT INTO kpis(user_id,business_unit_id,name,target,actual,period) VALUES(?,?,?,?,?,?)').run(req.body.user_id||null,req.body.business_unit_id||null,req.body.name,num(req.body.target),num(req.body.actual),req.body.period||'Monthly');audit(req.user,'kpi',r.lastInsertRowid,'create');res.json({id:r.lastInsertRowid});});

app.put('/api/kpis/:id',auth,allow('kpi'),(req,res)=>{const k=db.prepare('SELECT * FROM kpis WHERE id=?').get(req.params.id);if(!k)return res.status(404).json({error:'KPI not found'});db.prepare('UPDATE kpis SET user_id=?,business_unit_id=?,name=?,target=?,actual=?,period=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.body.user_id||null,req.body.business_unit_id||null,req.body.name??k.name,num(req.body.target??k.target),num(req.body.actual??k.actual),req.body.period??k.period,k.id);audit(req.user,'kpi',k.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/kpis/:id',auth,allow('kpi'),(req,res)=>{const k=db.prepare('SELECT * FROM kpis WHERE id=?').get(req.params.id);if(!k)return res.status(404).json({error:'KPI not found'});db.prepare('DELETE FROM kpis WHERE id=?').run(k.id);audit(req.user,'kpi',k.id,'delete',k.name);res.json({ok:true});});

app.get('/api/documents',auth,allow('documents'),(req,res)=>res.json(db.prepare(`SELECT d.*,b.name business_unit,u.name uploaded_by_name FROM documents d LEFT JOIN business_units b ON b.id=d.business_unit_id LEFT JOIN users u ON u.id=d.uploaded_by ORDER BY d.created_at DESC`).all()));
app.post('/api/documents',auth,allow('documents'),upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'File required'});const r=db.prepare('INSERT INTO documents(title,category,version,business_unit_id,file_path,uploaded_by) VALUES(?,?,?,?,?,?)').run(req.body.title||req.file.originalname,req.body.category||'Document',req.body.version||'1.0',req.body.business_unit_id||null,req.file.filename,req.user.id);audit(req.user,'document',r.lastInsertRowid,'upload',req.file.originalname);res.json({id:r.lastInsertRowid});});
app.delete('/api/documents/:id',auth,allow('documents'),(req,res)=>{const d=db.prepare('SELECT * FROM documents WHERE id=?').get(req.params.id);if(!d)return res.status(404).json({error:'Document not found'});db.prepare('DELETE FROM documents WHERE id=?').run(d.id);audit(req.user,'document',d.id,'delete',d.title);res.json({ok:true});});

app.get('/api/meetings',auth,allow('meetings'),(req,res)=>res.json(db.prepare('SELECT * FROM meetings ORDER BY meeting_date DESC LIMIT 100').all()));
app.post('/api/meetings',auth,allow('meetings'),(req,res)=>{const r=db.prepare('INSERT INTO meetings(meeting_date,title,summary) VALUES(?,?,?)').run(req.body.meeting_date,req.body.title||'Weekly Management Meeting',req.body.summary||'');audit(req.user,'meeting',r.lastInsertRowid,'create');res.json({id:r.lastInsertRowid});});
app.put('/api/meetings/:id',auth,allow('meetings'),(req,res)=>{const m=db.prepare('SELECT * FROM meetings WHERE id=?').get(req.params.id);if(!m)return res.status(404).json({error:'Meeting not found'});db.prepare('UPDATE meetings SET meeting_date=?,title=?,summary=? WHERE id=?').run(req.body.meeting_date??m.meeting_date,req.body.title??m.title,req.body.summary??m.summary,m.id);audit(req.user,'meeting',m.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/meetings/:id',auth,allow('meetings'),(req,res)=>{const m=db.prepare('SELECT * FROM meetings WHERE id=?').get(req.params.id);if(!m)return res.status(404).json({error:'Meeting not found'});db.prepare('DELETE FROM meeting_actions WHERE meeting_id=?').run(m.id);db.prepare('DELETE FROM meetings WHERE id=?').run(m.id);audit(req.user,'meeting',m.id,'delete',m.title);res.json({ok:true});});

app.post('/api/meeting-actions',auth,allow('meetings'),(req,res)=>{const r=db.prepare('INSERT INTO meeting_actions(meeting_id,title,owner_id,due_date) VALUES(?,?,?,?)').run(req.body.meeting_id,req.body.title,req.body.owner_id,req.body.due_date||null);notify(req.body.owner_id,'info','Meeting action assigned',req.body.title);res.json({id:r.lastInsertRowid});});

app.put('/api/meeting-actions/:id',auth,allow('meetings'),(req,res)=>{const a=db.prepare('SELECT * FROM meeting_actions WHERE id=?').get(req.params.id);if(!a)return res.status(404).json({error:'Meeting action not found'});db.prepare('UPDATE meeting_actions SET title=?,owner_id=?,due_date=?,status=? WHERE id=?').run(req.body.title??a.title,req.body.owner_id??a.owner_id,req.body.due_date??a.due_date,req.body.status??a.status,a.id);audit(req.user,'meeting_action',a.id,'update',JSON.stringify(req.body));res.json({ok:true});});
app.delete('/api/meeting-actions/:id',auth,allow('meetings'),(req,res)=>{const a=db.prepare('SELECT * FROM meeting_actions WHERE id=?').get(req.params.id);if(!a)return res.status(404).json({error:'Meeting action not found'});db.prepare('DELETE FROM meeting_actions WHERE id=?').run(a.id);audit(req.user,'meeting_action',a.id,'delete',a.title);res.json({ok:true});});

app.get('/api/notifications',auth,res=>res.json(db.prepare('SELECT * FROM notifications WHERE user_id IS NULL OR user_id=? ORDER BY created_at DESC LIMIT 100').all(req.user.id)));
app.put('/api/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND (user_id IS NULL OR user_id=?)').run(req.params.id,req.user.id);res.json({ok:true});});
app.get('/api/audit',auth,allow('dashboard'),(req,res)=>res.json(db.prepare(`SELECT a.*,u.name user_name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 500`).all()));

app.get('/api/restaurant/tables',auth,allow('restaurant','pos'),(req,res)=>{const id=db.prepare("SELECT id FROM business_units WHERE name='MIMI Resturant'").get()?.id;res.json(id?db.prepare('SELECT * FROM restaurant_tables WHERE business_unit_id=? ORDER BY id').all(id):[]);});
app.post('/api/restaurant/tables',auth,allow('restaurant'),(req,res)=>{const id=db.prepare("SELECT id FROM business_units WHERE name='MIMI Resturant'").get()?.id;if(!id)return res.status(404).json({error:'MIMI Resturant business unit not found'});const r=db.prepare('INSERT INTO restaurant_tables(business_unit_id,name,capacity) VALUES(?,?,?)').run(id,req.body.name, num(req.body.capacity)||4);res.json({id:r.lastInsertRowid});});
app.put('/api/restaurant/tables/:id',auth,allow('restaurant'),(req,res)=>{const t=db.prepare('SELECT * FROM restaurant_tables WHERE id=?').get(req.params.id);if(!t)return res.status(404).json({error:'Table not found'});db.prepare('UPDATE restaurant_tables SET name=?,capacity=?,status=? WHERE id=?').run(req.body.name??t.name,num(req.body.capacity??t.capacity),req.body.status??t.status,t.id);res.json({ok:true});});
app.delete('/api/restaurant/tables/:id',auth,allow('restaurant'),(req,res)=>{const t=db.prepare('SELECT * FROM restaurant_tables WHERE id=?').get(req.params.id);if(!t)return res.status(404).json({error:'Table not found'});db.prepare('DELETE FROM restaurant_tables WHERE id=?').run(t.id);res.json({ok:true});});

app.get('/api/restaurant/orders',auth,allow('restaurant','pos'),(req,res)=>res.json(db.prepare(`SELECT o.*,t.name table_name FROM restaurant_orders o LEFT JOIN restaurant_tables t ON t.id=o.table_id WHERE o.business_unit_id=(SELECT id FROM business_units WHERE name='MIMI Resturant') ORDER BY o.created_at DESC LIMIT 300`).all()));
app.post('/api/restaurant/orders',auth,allow('restaurant','pos'),(req,res)=>{const b=db.prepare("SELECT id FROM business_units WHERE name='MIMI Resturant'").get()?.id;if(!b)return res.status(404).json({error:'MIMI Resturant not found'});const items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)return res.status(400).json({error:'Add items'});const orderNo=nextNo('MIMI','restaurant_orders','id');const r=db.prepare('INSERT INTO restaurant_orders(business_unit_id,table_id,order_no,order_type,customer_name,status,created_by) VALUES(?,?,?,?,?,?,?)').run(b,req.body.table_id||null,orderNo,req.body.order_type||'Dine-in',req.body.customer_name||'','Open',req.user.id);const add=db.prepare('INSERT INTO restaurant_order_items(order_id,product_id,item_name,quantity,unit_price,unit_cost,line_total,kitchen_status,notes) VALUES(?,?,?,?,?,?,?,?,?)');for(const it of items){const p=db.prepare('SELECT * FROM products WHERE id=? AND business_unit_id=?').get(it.product_id,b);if(!p)return res.status(400).json({error:'Invalid menu item'});const q=num(it.quantity);const price=it.unit_price===undefined?p.selling_price:num(it.unit_price);if(price<0)return res.status(400).json({error:'Invalid price'});add.run(r.lastInsertRowid,p.id,p.name,q,price,p.cost_price,q*price,'Pending',it.notes||'');}res.json({id:r.lastInsertRowid,order_no:orderNo});});
app.put('/api/restaurant/orders/:id/kitchen',auth,allow('restaurant'),(req,res)=>{db.prepare('UPDATE restaurant_order_items SET kitchen_status=? WHERE id=?').run(req.body.status||'Preparing',req.body.item_id);res.json({ok:true});});
app.post('/api/restaurant/orders/:id/close',auth,allow('restaurant','pos'),(req,res)=>{const o=db.prepare('SELECT * FROM restaurant_orders WHERE id=?').get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});const items=db.prepare('SELECT * FROM restaurant_order_items WHERE order_id=?').all(o.id);createSale({body:{business_unit_id:o.business_unit_id,customer_name:o.customer_name,order_type:o.order_type,payment_method:req.body.payment_method||'Cash',items:items.map(x=>({product_id:x.product_id,quantity:x.quantity,unit_price:x.unit_price})),discount:req.body.discount||0},user:req.user,protocol:'',get:()=>''}, {status:()=>({json:x=>res.status(400).json(x)}),json:x=>{if(x.error)return res.status(400).json(x);db.prepare('UPDATE restaurant_orders SET status=\'Closed\',payment_method=?,subtotal=?,discount=?,tax=?,total=?,sale_id=?,closed_at=CURRENT_TIMESTAMP WHERE id=?').run(req.body.payment_method||'Cash',x.total,0,0,x.total,x.id,o.id);const t=db.prepare('SELECT table_id FROM restaurant_orders WHERE id=?').get(o.id);if(t.table_id)db.prepare('UPDATE restaurant_tables SET status=\'Available\' WHERE id=?').run(t.table_id);res.json(x);}} ,true);});
app.post('/api/restaurant/waste',auth,allow('restaurant','inventory'),(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=?').get(req.body.product_id);if(!p)return res.status(404).json({error:'Product not found'});const q=num(req.body.quantity);if(p.current_stock<q)return res.status(400).json({error:'Insufficient stock'});db.prepare('UPDATE products SET current_stock=current_stock-? WHERE id=?').run(q,p.id);const r=db.prepare('INSERT INTO restaurant_waste(business_unit_id,product_id,quantity,reason,estimated_cost,created_by) VALUES(?,?,?,?,?,?)').run(p.business_unit_id,p.id,q,req.body.reason||'',q*p.cost_price,req.user.id);db.prepare('INSERT INTO stock_movements(product_id,type,quantity,unit_cost,reason,user_id) VALUES(?,?,?,?,?,?)').run(p.id,'WASTE',q,p.cost_price,req.body.reason||'',req.user.id);res.json({id:r.lastInsertRowid});});
app.post('/api/restaurant/closing',auth,allow('restaurant','finance'),(req,res)=>{const b=db.prepare("SELECT id FROM business_units WHERE name='MIMI Resturant'").get()?.id;const d=req.body.business_date||new Date().toISOString().slice(0,10);const sales=db.prepare(`SELECT COALESCE(SUM(CASE WHEN payment_method='Cash' THEN total ELSE 0 END),0)cash,COALESCE(SUM(CASE WHEN payment_method IN ('Card','Bank') THEN total ELSE 0 END),0)card,COALESCE(SUM(CASE WHEN payment_method NOT IN ('Cash','Card','Bank') THEN total ELSE 0 END),0)other FROM sales WHERE business_unit_id=? AND date(created_at)=?`).get(b,d);const variance=num(req.body.cash_counted)-sales.cash;const r=db.prepare(`INSERT INTO restaurant_closings(business_unit_id,business_date,cash_sales,card_sales,other_sales,cash_counted,variance,notes,closed_by) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(business_unit_id,business_date) DO UPDATE SET cash_sales=excluded.cash_sales,card_sales=excluded.card_sales,other_sales=excluded.other_sales,cash_counted=excluded.cash_counted,variance=excluded.variance,notes=excluded.notes,closed_by=excluded.closed_by`).run(b,d,sales.cash,sales.card,sales.other,num(req.body.cash_counted),variance,req.body.notes||'',req.user.id);res.json({id:r.lastInsertRowid,...sales,variance});});

// Basic scheduled alerts: run every 10 minutes while the server is active.
function alertSweep(){const overdue=db.prepare("SELECT id,owner_id,title FROM tasks WHERE status NOT IN ('Completed','Cancelled') AND due_date IS NOT NULL AND date(due_date)<date('now')").all();overdue.forEach(t=>{const exists=db.prepare("SELECT 1 FROM notifications WHERE user_id=? AND title='Overdue task' AND message=? AND date(created_at)=date('now')").get(t.owner_id,t.title);if(!exists)notify(t.owner_id,'warning','Overdue task',t.title);});const low=db.prepare("SELECT p.id,p.name,p.business_unit_id FROM products p WHERE p.active=1 AND p.item_type='PRODUCT' AND p.current_stock<=p.reorder_level AND p.reorder_level>0").all();low.forEach(p=>{const managers=db.prepare('SELECT id FROM users WHERE role IN (\'CEO / Owner\',\'Business Unit Manager\') AND active=1 AND (business_unit_id=? OR role=\'CEO / Owner\')').all(p.business_unit_id);managers.forEach(m=>{const exists=db.prepare("SELECT 1 FROM notifications WHERE user_id=? AND title='Low stock' AND message=? AND date(created_at)=date('now')").get(m.id,p.name);if(!exists)notify(m.id,'warning','Low stock',p.name);});});}
setInterval(alertSweep,10*60*1000);setTimeout(alertSweep,3000);
app.get(/.*/,(req,res)=>res.sendFile(path.join(root,'public','index.html')));
app.listen(PORT,()=>console.log(`Blue Ocean Market V4 running on http://localhost:${PORT}`));
