// Blue Ocean Market V30.20.0 — System Settings UX, smart financial accounts, contact/UI validation support.
'use strict';

const VERSION='30.20.0';

function install({app,db,auth,currentUnit,enforceUnit,audit,access,config}){
  const text=v=>String(v??'').trim();
  const tableExists=name=>!!db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(name);
  const ensureColumn=(table,column,definition)=>{try{if(!tableExists(table))return;const cols=db.prepare(`PRAGMA table_info(${table})`).all().map(x=>x.name);if(!cols.includes(column))db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`)}catch(e){console.error('V30.20 migration',table,column,e.message)}};
  const normalizePhone=v=>text(v).replace(/\D/g,'');
  const validEmail=v=>!text(v)||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text(v));
  const validPhone=v=>{const raw=text(v);if(!raw)return true;const digits=normalizePhone(raw);return /^\+?[0-9][0-9\s().-]{5,24}$/.test(raw)&&digits.length>=6&&digits.length<=15};
  const isSystemAdmin=(req,bu=null)=>req.user.role==='CEO / Owner'||!!config?.isSystemAdmin?.(req,bu);
  const canFinancial=(req,bu=null)=>req.user.role==='CEO / Owner'||(isSystemAdmin(req,bu)&&!!access?.can?.(req.user.id,'sensitive.bank_accounts',bu||req.selected_business_unit_id||req.user.business_unit_id));
  const canSeeBu=(req,bu)=>!bu||req.user.role==='CEO / Owner'||enforceUnit(req,bu);
  const accountType=v=>{const s=text(v).toLowerCase();if(s.includes('cash'))return 'Cash';if(s.includes('card'))return 'Card';if(s.includes('wallet'))return 'Wallet';if(s.includes('other'))return 'Other';return 'Bank'};

  ensureColumn('accounting_payment_accounts','financial_account_type',"TEXT DEFAULT ''");
  ensureColumn('accounting_payment_accounts','card_network',"TEXT DEFAULT ''");
  ensureColumn('accounting_payment_accounts','card_last4',"TEXT DEFAULT ''");
  ensureColumn('accounting_payment_accounts','card_expiry',"TEXT DEFAULT ''");
  ensureColumn('accounting_payment_accounts','linked_bank_account_id','INTEGER');
  ensureColumn('accounting_payment_accounts','cheque_enabled','INTEGER NOT NULL DEFAULT 0');
  ensureColumn('accounting_payment_accounts','archived_at','TEXT');
  ensureColumn('accounting_payment_accounts','archived_by','INTEGER');
  ensureColumn('excavator_buyer_payments','payment_account_id','INTEGER');
  ensureColumn('excavator_buyer_refunds','payment_account_id','INTEGER');
  // V30.20 final integration: preserve the exact configured account selected by the user
  // across legacy/general and Pink Salt payment sources as they flow into Finance/Accounting.
  ensureColumn('excavator_payments','payment_account_id','INTEGER');
  ensureColumn('sales','payment_account_id','INTEGER');
  ensureColumn('purchases','payment_account_id','INTEGER');
  ensureColumn('pink_salt_import_payments','payment_account_id','INTEGER');
  ensureColumn('pink_salt_import_costs','payment_account_id','INTEGER');
  ensureColumn('pink_salt_supplier_advances','payment_account_id','INTEGER');
  ensureColumn('pink_salt_supplier_advance_refunds','payment_account_id','INTEGER');
  ensureColumn('pink_salt_customer_payments','payment_account_id','INTEGER');
  ensureColumn('pink_salt_customer_refunds','payment_account_id','INTEGER');
  ensureColumn('pink_salt_customer_receipts','payment_account_id','INTEGER');

  try{db.prepare("UPDATE accounting_payment_accounts SET financial_account_type=CASE WHEN lower(COALESCE(payment_type,'')) LIKE '%cash%' THEN 'Cash' WHEN lower(COALESCE(payment_type,'')) LIKE '%card%' THEN 'Card' WHEN lower(COALESCE(payment_type,'')) LIKE '%wallet%' THEN 'Wallet' WHEN lower(COALESCE(payment_type,'')) LIKE '%other%' THEN 'Other' ELSE 'Bank' END WHERE COALESCE(financial_account_type,'')='' ").run()}catch(_){ }
  try{db.prepare("UPDATE accounting_payment_accounts SET card_last4=COALESCE(NULLIF(card_last4,''),account_last4,'') WHERE financial_account_type='Card'").run()}catch(_){ }

  function refs(id){const q=(table,col)=>{try{return tableExists(table)?Number(db.prepare(`SELECT COUNT(*) c FROM ${table} WHERE ${col}=?`).get(id).c||0):0}catch(_){return 0}};const out={finance:q('finance_entries','payment_account_id'),statements:q('accounting_bank_statement_lines','payment_account_id'),payroll:q('payroll_payments','payment_account_id'),employee_advances:q('employee_advances','payment_account_id'),inter_bu_from:q('accounting_inter_unit_transfers','from_payment_account_id'),inter_bu_to:q('accounting_inter_unit_transfers','to_payment_account_id')};out.total=Object.values(out).reduce((n,v)=>n+Number(v||0),0);return out}
  function row(id){return db.prepare(`SELECT p.*,b.name business_unit,a.code ledger_code,a.name ledger_name,a.account_type ledger_type,lb.name linked_bank_name FROM accounting_payment_accounts p LEFT JOIN business_units b ON b.id=p.business_unit_id LEFT JOIN accounting_accounts a ON a.id=p.ledger_account_id LEFT JOIN accounting_payment_accounts lb ON lb.id=p.linked_bank_account_id WHERE p.id=?`).get(id)}
  function maskAccount(r){const raw=text(r.account_number),last=text(r.card_last4||r.account_last4||(raw?raw.slice(-4):''));return raw?('*'.repeat(Math.max(0,raw.length-4))+raw.slice(-4)):(last?'•••• '+last:'')}
  function publicRow(r,admin){const type=accountType(r.financial_account_type||r.payment_type),x={...r,financial_account_type:type,payment_type:type,account_number_masked:maskAccount(r),reference_count:0,references:null};if(admin){x.references=refs(r.id);x.reference_count=x.references.total}else{delete x.account_number;delete x.iban;delete x.swift_bic}return x}
  function scopeQuery(req,bu){let q=`SELECT p.*,b.name business_unit,a.code ledger_code,a.name ledger_name,a.account_type ledger_type,lb.name linked_bank_name FROM accounting_payment_accounts p LEFT JOIN business_units b ON b.id=p.business_unit_id LEFT JOIN accounting_accounts a ON a.id=p.ledger_account_id LEFT JOIN accounting_payment_accounts lb ON lb.id=p.linked_bank_account_id WHERE 1=1`,args=[];if(bu){q+=' AND (p.business_unit_id=? OR p.business_unit_id IS NULL)';args.push(bu)}else if(req.user.role!=='CEO / Owner'){const own=Number(req.selected_business_unit_id||req.user.business_unit_id||0);if(!own)return {q:q+' AND 1=0',args};q+=' AND (p.business_unit_id=? OR p.business_unit_id IS NULL)';args.push(own)}q+=' ORDER BY p.active DESC,CASE COALESCE(p.financial_account_type,p.payment_type) WHEN \'Cash\' THEN 1 WHEN \'Bank\' THEN 2 WHEN \'Card\' THEN 3 ELSE 4 END,p.name';return {q,args}}

  app.get('/api/v320/financial-accounts',auth,(req,res)=>{
    const bu=Number(req.query.business_unit_id||req.selected_business_unit_id||currentUnit(req)||0)||null;if(bu&&!canSeeBu(req,bu))return res.status(403).json({error:'You cannot access financial accounts for another business unit.'});const {q,args}=scopeQuery(req,bu),admin=canFinancial(req,bu);let rows=db.prepare(q).all(...args).map(r=>publicRow(r,admin));const status=text(req.query.status);if(status)rows=rows.filter(x=>text(x.status||'Active')===status);const type=text(req.query.type);if(type)rows=rows.filter(x=>accountType(x.financial_account_type||x.payment_type)===accountType(type));res.json(rows)
  });

  app.get('/api/v320/financial-accounts/options',auth,(req,res)=>{
    const bu=Number(req.query.business_unit_id||req.selected_business_unit_id||currentUnit(req)||0)||null;if(bu&&!canSeeBu(req,bu))return res.status(403).json({error:'You cannot access financial accounts for another business unit.'});const method=text(req.query.method),wanted=accountType(method),{q,args}=scopeQuery(req,bu);let rows=db.prepare(q).all(...args).filter(r=>Number(r.active||0)===1&&text(r.status||'Active')==='Active');rows=rows.filter(r=>{const type=accountType(r.financial_account_type||r.payment_type);if(wanted==='Bank'&&/cheque/i.test(method))return type==='Bank'&&Number(r.cheque_enabled||0)===1;return type===wanted});rows=rows.map(r=>publicRow(r,false));res.json({method,wanted_type:wanted,accounts:rows,default_account_id:Number(rows.find(r=>Number(r.default_payment||r.is_default||0)===1)?.id||rows[0]?.id||0)})
  });

  app.get('/api/v320/financial-accounts/ledger-options',auth,(req,res)=>{
    const bu=Number(req.selected_business_unit_id||currentUnit(req)||0)||null;if(!isSystemAdmin(req,bu))return res.status(403).json({error:'System Settings access is required.'});res.json(db.prepare("SELECT id,code,name,account_type FROM accounting_accounts WHERE active=1 AND account_type IN ('Asset','Liability') ORDER BY account_type,code,name").all())
  });

  function payload(body,before={}){const type=accountType(body.financial_account_type??body.payment_type??before.financial_account_type??before.payment_type),status=['Active','Inactive','Closed','Archived'].includes(text(body.status))?text(body.status):text(before.status||'Active');return {business_unit_id:body.business_unit_id===''||body.business_unit_id==null?null:Number(body.business_unit_id),name:text(body.name??before.name),financial_account_type:type,payment_type:type,currency:text(body.currency??before.currency??'KRW').toUpperCase(),ledger_account_id:Number(body.ledger_account_id??before.ledger_account_id??0),bank_name:text(body.bank_name??before.bank_name),account_holder:text(body.account_holder??before.account_holder),account_number:text(body.account_number??before.account_number),iban:text(body.iban??before.iban),swift_bic:text(body.swift_bic??before.swift_bic),branch:text(body.branch??before.branch),account_type:text(body.account_type??before.account_type??(type==='Cash'?'Cash':'Current')),card_network:text(body.card_network??before.card_network),card_last4:text(body.card_last4??before.card_last4??before.account_last4).replace(/\D/g,'').slice(-4),card_expiry:text(body.card_expiry??before.card_expiry),linked_bank_account_id:Number(body.linked_bank_account_id??before.linked_bank_account_id??0)||null,cheque_enabled:body.cheque_enabled===undefined?Number(before.cheque_enabled||0):(body.cheque_enabled?1:0),status,default_payment:body.default_payment===undefined?Number(before.default_payment||0):(body.default_payment?1:0),default_receipt:body.default_receipt===undefined?Number(before.default_receipt||0):(body.default_receipt?1:0),opening_balance_krw:Number(body.opening_balance_krw??before.opening_balance_krw??0),migration_reference:text(body.migration_reference??before.migration_reference),notes:text(body.notes??before.notes)}}
  function validate(req,x,before=null){if(!x.name)throw Object.assign(new Error('Account name / label is required.'),{status:400});if(x.business_unit_id&&!canSeeBu(req,x.business_unit_id))throw Object.assign(new Error('You cannot manage another business unit financial account.'),{status:403});if(!canFinancial(req,x.business_unit_id))throw Object.assign(new Error('Manage Company Financial Accounts permission is required.'),{status:403});const ledger=db.prepare('SELECT id,account_type FROM accounting_accounts WHERE id=? AND active=1').get(x.ledger_account_id);if(!ledger)throw Object.assign(new Error('Select an active GL account.'),{status:400});if(['Bank','Cash','Wallet'].includes(x.financial_account_type)&&ledger.account_type!=='Asset')throw Object.assign(new Error(`${x.financial_account_type} accounts must map to an Asset GL account.`),{status:400});if(x.financial_account_type==='Card'&&!['Asset','Liability'].includes(ledger.account_type))throw Object.assign(new Error('Company Cards must map to an Asset (debit/prepaid) or Liability (credit card payable) GL account.'),{status:400});if(x.financial_account_type==='Card'&&x.card_last4&&x.card_last4.length!==4)throw Object.assign(new Error('Card Last 4 must contain exactly four digits.'),{status:400});if(x.linked_bank_account_id){const linked=row(x.linked_bank_account_id);if(!linked||accountType(linked.financial_account_type||linked.payment_type)!=='Bank')throw Object.assign(new Error('Linked account must be a Company Bank Account.'),{status:400});if(x.business_unit_id&&linked.business_unit_id&&Number(x.business_unit_id)!==Number(linked.business_unit_id))throw Object.assign(new Error('Linked bank account belongs to a different business unit.'),{status:400})}if(before&&refs(before.id).total>0&&Number(x.ledger_account_id)!==Number(before.ledger_account_id)&&!(req.user.role==='CEO / Owner'&&req.body.confirm_existing_transactions===true))throw Object.assign(new Error('This financial account has transaction history. GL mapping can change only with CEO / Owner explicit high-risk confirmation.'),{status:409});}
  function hist(id,before,after,reason,userId){try{db.prepare('INSERT INTO system_bank_account_history(payment_account_id,before_json,after_json,reason,changed_by) VALUES(?,?,?,?,?)').run(id,JSON.stringify(before||{}),JSON.stringify(after||{}),reason,userId)}catch(_){}}

  app.post('/api/v320/financial-accounts',auth,(req,res)=>{try{const x=payload(req.body),reason=text(req.body.reason);if(!reason)return res.status(400).json({error:'Creation reason is required.'});validate(req,x);const r=db.prepare(`INSERT INTO accounting_payment_accounts(business_unit_id,name,payment_type,financial_account_type,currency,ledger_account_id,bank_name,account_last4,is_default,notes,created_by,account_holder,account_number,iban,swift_bic,branch,account_type,status,active,default_payment,default_receipt,opening_balance_krw,migration_reference,updated_by,card_network,card_last4,card_expiry,linked_bank_account_id,cheque_enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(x.business_unit_id,x.name,x.payment_type,x.financial_account_type,x.currency,x.ledger_account_id,x.bank_name,(x.card_last4||x.account_number.slice(-4)),x.default_payment||x.default_receipt?1:0,x.notes,req.user.id,x.account_holder,x.account_number,x.iban,x.swift_bic,x.branch,x.account_type,'Active',1,x.default_payment,x.default_receipt,x.opening_balance_krw,x.migration_reference,req.user.id,x.card_network,x.card_last4,x.card_expiry,x.linked_bank_account_id,x.cheque_enabled);const after=row(r.lastInsertRowid);hist(r.lastInsertRowid,{},after,reason,req.user.id);audit(req.user,'company_financial_account',r.lastInsertRowid,'create',JSON.stringify({reason,type:x.financial_account_type,business_unit_id:x.business_unit_id,ledger_account_id:x.ledger_account_id}));res.json({id:Number(r.lastInsertRowid)})}catch(e){res.status(e.status||500).json({error:e.message})}});
  app.put('/api/v320/financial-accounts/:id',auth,(req,res)=>{try{const before=row(req.params.id);if(!before)return res.status(404).json({error:'Financial account not found.'});const x=payload(req.body,before),reason=text(req.body.reason);if(!reason)return res.status(400).json({error:'Change reason is required.'});validate(req,x,before);db.prepare(`UPDATE accounting_payment_accounts SET business_unit_id=?,name=?,payment_type=?,financial_account_type=?,currency=?,ledger_account_id=?,bank_name=?,account_last4=?,notes=?,account_holder=?,account_number=?,iban=?,swift_bic=?,branch=?,account_type=?,status=?,active=?,default_payment=?,default_receipt=?,is_default=?,opening_balance_krw=?,migration_reference=?,updated_by=?,updated_at=CURRENT_TIMESTAMP,card_network=?,card_last4=?,card_expiry=?,linked_bank_account_id=?,cheque_enabled=? WHERE id=?`).run(x.business_unit_id,x.name,x.payment_type,x.financial_account_type,x.currency,x.ledger_account_id,x.bank_name,(x.card_last4||x.account_number.slice(-4)),x.notes,x.account_holder,x.account_number,x.iban,x.swift_bic,x.branch,x.account_type,x.status,x.status==='Active'?1:0,x.default_payment,x.default_receipt,x.default_payment||x.default_receipt?1:0,x.opening_balance_krw,x.migration_reference,req.user.id,x.card_network,x.card_last4,x.card_expiry,x.linked_bank_account_id,x.cheque_enabled,before.id);const after=row(before.id);hist(before.id,before,after,reason,req.user.id);audit(req.user,'company_financial_account',before.id,'update',JSON.stringify({reason,type:x.financial_account_type,gl_mapping_changed:Number(before.ledger_account_id)!==Number(x.ledger_account_id),references:refs(before.id)}));res.json({ok:true,references:refs(before.id)})}catch(e){res.status(e.status||500).json({error:e.message})}});
  app.post('/api/v320/financial-accounts/:id/close',auth,(req,res)=>{try{const before=row(req.params.id);if(!before)return res.status(404).json({error:'Financial account not found.'});if(!canFinancial(req,before.business_unit_id))return res.status(403).json({error:'Manage Company Financial Accounts permission is required.'});const reason=text(req.body.reason);if(!reason)return res.status(400).json({error:'Closure / archive reason is required.'});const status=text(req.body.status)==='Archived'?'Archived':'Closed';db.prepare("UPDATE accounting_payment_accounts SET active=0,status=?,closed_at=CURRENT_TIMESTAMP,closed_by=?,archived_at=CASE WHEN ?='Archived' THEN CURRENT_TIMESTAMP ELSE archived_at END,archived_by=CASE WHEN ?='Archived' THEN ? ELSE archived_by END,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,req.user.id,status,status,req.user.id,req.user.id,before.id);const after=row(before.id);hist(before.id,before,after,reason,req.user.id);audit(req.user,'company_financial_account',before.id,status==='Archived'?'archive':'close',JSON.stringify({reason,references:refs(before.id)}));res.json({ok:true,status,preserved_history:true,references:refs(before.id)})}catch(e){res.status(e.status||500).json({error:e.message})}});
  app.get('/api/v320/financial-accounts/:id/history',auth,(req,res)=>{const a=row(req.params.id);if(!a)return res.status(404).json({error:'Financial account not found.'});if(!isSystemAdmin(req,a.business_unit_id||Number(req.selected_business_unit_id||0)||null))return res.status(403).json({error:'System Settings access is required.'});res.json(db.prepare('SELECT h.*,u.name changed_by_name FROM system_bank_account_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.payment_account_id=? ORDER BY h.id DESC LIMIT 300').all(a.id).map(x=>{let before={},after={};try{before=JSON.parse(x.before_json||'{}')}catch(_){}try{after=JSON.parse(x.after_json||'{}')}catch(_){}return {...x,before,after}}))});

  app.get('/api/v320/contact-check',auth,(req,res)=>{
    const entity=text(req.query.entity).toLowerCase(),bu=Number(req.query.business_unit_id||req.selected_business_unit_id||currentUnit(req)||0)||null,exclude=Number(req.query.exclude_id||0),phone=text(req.query.phone),email=text(req.query.email);if(!bu||!canSeeBu(req,bu))return res.status(403).json({error:'Select an authorized business unit.'});if(phone&&!validPhone(phone))return res.json({valid:false,field:'phone',message:'Enter a valid phone number (6–15 digits; +, spaces, brackets and hyphens are allowed).'});if(email&&!validEmail(email))return res.json({valid:false,field:'email',message:'Enter a valid email address.'});const pn=normalizePhone(phone),em=email.toLowerCase();let rows=[];if(entity==='supplier')rows=db.prepare('SELECT id,name,phone,email FROM excavator_suppliers WHERE business_unit_id=? AND active=1').all(bu);else if(entity==='buyer')rows=db.prepare('SELECT id,name,phone,email FROM excavator_buyers WHERE business_unit_id=? AND active=1').all(bu);else return res.status(400).json({error:'Unsupported contact entity.'});const dup=rows.find(r=>Number(r.id)!==exclude&&((pn&&normalizePhone(r.phone)===pn)||(em&&text(r.email).toLowerCase()===em)));if(dup){const field=pn&&normalizePhone(dup.phone)===pn?'phone':'email';return res.json({valid:false,duplicate:true,field,message:`This ${field==='phone'?'phone number':'email address'} is already used by ${dup.name}.`,existing_id:dup.id,existing_name:dup.name})}res.json({valid:true,duplicate:false})
  });

  app.get('/api/v320/attachment-policy',auth,(req,res)=>{const bu=Number(req.query.business_unit_id||req.selected_business_unit_id||currentUnit(req)||0)||null,userId=Number(req.user.id||0)||null,cfg=config?.effectiveFor?.('files_attachments',bu,userId)||{};res.json({max_file_size_mb:Number(cfg.max_file_size_mb||20),max_attachments_per_upload:Number(cfg.max_attachments_per_record||30),allowed_file_types:text(cfg.allowed_file_types||'pdf,jpg,jpeg,png,webp,xlsx,xls,csv,doc,docx'),preview_before_store:false,optimize_images:false})});

  return {VERSION};
}
module.exports={install,VERSION};
