// Blue Ocean Market V30.26.0 — Excavator sale/payment lifecycle integrity & controlled status actions.
'use strict';

const VERSION='30.26.0';

function install(ctx){
  const {app,db,auth,allow,audit,notify,upload,financeSync,voidFinanceBySource,configuredPaymentAccount,access,
    maybeCreateApproval,stopForApproval,markApprovalExecuted,approvalRequestSnapshot,storedApprovalSnapshot,
    storedApprovalUser,storedApprovalFiles,captureInternalAction,excavatorGuard,excavatorCostSnapshot,finalizeExcavatorSalePdf}=ctx;
  const num=v=>Number(v||0)||0;
  const text=v=>String(v??'').trim();
  const addColumn=(table,col,def)=>{try{db.exec(`ALTER TABLE ${table} ADD COLUMN ${col} ${def}`)}catch(_) {}};
  addColumn('excavator_buyer_payments','credit_eligible','INTEGER DEFAULT 0');
  addColumn('excavator_assets','archived','INTEGER DEFAULT 0');
  addColumn('excavator_assets','archive_reason',"TEXT DEFAULT ''");
  addColumn('excavator_assets','archived_by','INTEGER');
  addColumn('excavator_assets','archived_at','TEXT');
  addColumn('excavator_transactions','void_reason',"TEXT DEFAULT ''");
  addColumn('excavator_transactions','voided_by','INTEGER');
  addColumn('excavator_transactions','voided_at','TEXT');
  try{db.exec('CREATE INDEX IF NOT EXISTS idx_excavator_assets_archived ON excavator_assets(business_unit_id,archived,lifecycle_stage)')}catch(_){}
  try{db.exec('CREATE INDEX IF NOT EXISTS idx_excavator_buyer_payment_credit ON excavator_buyer_payments(buyer_id,status,credit_eligible,payment_date)')}catch(_){}

  const canAction=(req,action,bu)=>req.user?.role==='CEO / Owner'||!!access?.can?.(req.user.id,`excavator.${action}`,bu);
  const activeSale=assetId=>db.prepare("SELECT * FROM excavator_transactions WHERE asset_id=? AND type IN ('Local Sale','Export Sale') AND status!='Cancelled' ORDER BY id DESC LIMIT 1").get(assetId);
  const anySale=assetId=>db.prepare("SELECT * FROM excavator_transactions WHERE asset_id=? AND type IN ('Local Sale','Export Sale') ORDER BY id DESC LIMIT 1").get(assetId);
  const allocationsForAsset=assetId=>db.prepare(`SELECT al.*,p.payment_date,p.reference,p.currency,p.original_amount,p.fx_rate,p.krw_amount,p.method,p.receipt_file,p.receipt_document_id,p.payment_account_id,p.payment_type,p.source_type,p.source_id,p.credit_eligible,p.status payment_status
    FROM excavator_buyer_payment_allocations al JOIN excavator_buyer_payments p ON p.id=al.payment_id
    WHERE al.asset_id=? AND COALESCE(al.status,'Active')='Active' AND COALESCE(p.status,'Active')!='Voided' ORDER BY al.id`).all(assetId);
  const allocatedTotal=assetId=>Number(db.prepare(`SELECT COALESCE(SUM(al.amount_krw),0) v FROM excavator_buyer_payment_allocations al JOIN excavator_buyer_payments p ON p.id=al.payment_id WHERE al.asset_id=? AND COALESCE(al.status,'Active')='Active' AND COALESCE(p.status,'Active')!='Voided'`).get(assetId)?.v||0);
  const paymentAllocated=paymentId=>Number(db.prepare("SELECT COALESCE(SUM(amount_krw),0) v FROM excavator_buyer_payment_allocations WHERE payment_id=? AND COALESCE(status,'Active')='Active'").get(paymentId)?.v||0);
  const refundedTotal=buyerId=>Number(db.prepare("SELECT COALESCE(SUM(krw_amount),0) v FROM excavator_buyer_refunds WHERE buyer_id=? AND status='Completed'").get(buyerId)?.v||0);

  function paymentAvailableRows(buyerId,excludeAssetId=0){
    const rows=db.prepare(`SELECT p.*,COALESCE((SELECT SUM(al.amount_krw) FROM excavator_buyer_payment_allocations al WHERE al.payment_id=p.id AND COALESCE(al.status,'Active')='Active'),0) allocated
      FROM excavator_buyer_payments p
      WHERE p.buyer_id=? AND COALESCE(p.status,'Active')!='Voided'
        AND (COALESCE(p.source_type,'')!='Excavator Sale' OR COALESCE(p.credit_eligible,0)=1)
      ORDER BY date(p.payment_date),p.id`).all(buyerId);
    return rows.map(p=>{
      const legacyUsed=p.asset_id&&Number(p.asset_id)!==Number(excludeAssetId)&&!Number(p.allocated||0)?Number(p.krw_amount||0):0;
      return {...p,available:Math.max(0,Number(p.krw_amount||0)-Number(p.allocated||0)-legacyUsed)};
    }).filter(p=>p.available>0.005);
  }
  function buyerAvailable(buyerId,excludeAssetId=0){
    const gross=paymentAvailableRows(buyerId,excludeAssetId).reduce((n,p)=>n+p.available,0);
    // Refunds are global buyer-credit reductions. This mirrors existing balance logic while preventing sale receipts from being reused unless explicitly credit-eligible.
    return Math.max(0,gross-refundedTotal(buyerId));
  }
  function allocateAdvance({buyerId,assetId,amount,date,userId,note}){
    let remaining=Number(amount||0);const available=buyerAvailable(buyerId,assetId);
    if(available+0.005<remaining)throw new Error(`Buyer available advance is insufficient. Available: KRW ${available.toLocaleString()} / Required: KRW ${remaining.toLocaleString()}.`);
    const rows=paymentAvailableRows(buyerId,assetId);
    for(const p of rows){if(remaining<=0.005)break;const take=Math.min(p.available,remaining);db.prepare(`INSERT INTO excavator_buyer_payment_allocations(payment_id,buyer_id,asset_id,amount_krw,allocation_date,created_by,notes,status) VALUES(?,?,?,?,?,?,?,'Active')`).run(p.id,buyerId,assetId,take,date,userId,note||'Buyer advance allocated to machine sale');remaining-=take;}
    if(remaining>0.005)throw new Error('Unable to allocate enough buyer advance to this machine.');
    return Number(amount||0)-Math.max(0,remaining);
  }
  function resyncBuyerReceiptFinance(paymentId,userId){
    const p=db.prepare(`SELECT p.*,b.business_unit_id,b.name buyer_name FROM excavator_buyer_payments p JOIN excavator_buyers b ON b.id=p.buyer_id WHERE p.id=?`).get(paymentId);if(!p||text(p.status)==='Voided')return null;
    return financeSync({businessUnitId:p.business_unit_id,type:'Revenue',category:'Excavator Buyer Payment',amount:Number(p.krw_amount||0),description:'Buyer '+(p.buyer_name||p.buyer_id)+' payment',paymentMethod:p.method,reference:p.reference||'',paymentAccountId:p.payment_account_id||null,createdBy:userId||p.created_by,sourceType:'Excavator Buyer Payment',sourceId:p.id,receiptFile:p.receipt_file||'',originalAmount:p.original_amount,originalCurrency:p.currency,fxRate:p.fx_rate,transactionDate:p.payment_date,sourceLabel:'Excavator → Buyer Payment',sourceRecordId:p.buyer_id,sourcePaymentId:p.id,resetVerification:true});
  }
  function releaseAllocationAmount(assetId,amount,user,reason){
    let release=Math.max(0,Number(amount||0));const rows=db.prepare(`SELECT al.*,p.id payment_id FROM excavator_buyer_payment_allocations al JOIN excavator_buyer_payments p ON p.id=al.payment_id WHERE al.asset_id=? AND COALESCE(al.status,'Active')='Active' AND COALESCE(p.status,'Active')!='Voided' ORDER BY al.id DESC`).all(assetId);
    const touched=new Set();
    for(const al of rows){if(release<=0.005)break;const current=Number(al.amount_krw||0),take=Math.min(current,release);if(take+0.005>=current){db.prepare("UPDATE excavator_buyer_payment_allocations SET status='Reversed',void_reason=?,voided_by=?,voided_at=CURRENT_TIMESTAMP WHERE id=?").run(reason,user.id,al.id)}else{db.prepare('UPDATE excavator_buyer_payment_allocations SET amount_krw=? WHERE id=?').run(current-take,al.id);db.prepare(`INSERT INTO excavator_buyer_payment_allocations(payment_id,buyer_id,asset_id,amount_krw,allocation_date,created_by,notes,status,void_reason,voided_by,voided_at) VALUES(?,?,?,?,?,?,?,'Reversed',?,?,CURRENT_TIMESTAMP)`).run(al.payment_id,al.buyer_id,al.asset_id,take,al.allocation_date,user.id,'Released by sale update',reason,user.id)}db.prepare('UPDATE excavator_buyer_payments SET credit_eligible=1 WHERE id=?').run(al.payment_id);touched.add(Number(al.payment_id));release-=take;}
    for(const paymentId of touched)resyncBuyerReceiptFinance(paymentId,user.id);
    if(release>0.005)throw new Error('Unable to release the requested settlement amount.');
  }
  function reverseAllAllocations(assetId,user,reason){
    const rows=db.prepare("SELECT DISTINCT payment_id FROM excavator_buyer_payment_allocations WHERE asset_id=? AND COALESCE(status,'Active')='Active'").all(assetId);
    db.prepare("UPDATE excavator_buyer_payment_allocations SET status='Reversed',void_reason=?,voided_by=?,voided_at=CURRENT_TIMESTAMP WHERE asset_id=? AND COALESCE(status,'Active')='Active'").run(reason,user.id,assetId);
    for(const r of rows){db.prepare('UPDATE excavator_buyer_payments SET credit_eligible=1 WHERE id=?').run(r.payment_id);resyncBuyerReceiptFinance(r.payment_id,user.id)}
  }
  function addBuyerEvidence({buyerId,paymentId,assetId,files,userId,title='Buyer Sale Payment Receipt / Evidence'}){
    if(!files?.length)return null;const ins=db.prepare(`INSERT INTO excavator_buyer_documents(buyer_id,payment_id,asset_id,title,original_name,file_path,mime_type,size_bytes,uploaded_by) VALUES(?,?,?,?,?,?,?,?,?)`);let last=null;for(const file of files){const r=ins.run(buyerId,paymentId,assetId,title,file.originalname,'/uploads/'+file.filename,file.mimetype,file.size,userId);last=Number(r.lastInsertRowid)}db.prepare('UPDATE excavator_buyer_payments SET receipt_document_id=?,receipt_file=? WHERE id=?').run(last,files[0].filename,paymentId);return last;
  }
  function createCashReceipt({req,businessUnitId,buyer,asset,saleId,neededKrw,files,note,requireFull=true}){
    const currency=text(req.body.payment_currency||'KRW').toUpperCase(),fx=currency==='KRW'?1:num(req.body.payment_fx_rate),original=num(req.body.payment_amount),method=text(req.body.payment_method),date=text(req.body.payment_date),reference=text(req.body.payment_reference);
    if(original<=0)throw new Error('Payment Amount is required and must be greater than zero.');if(fx<=0)throw new Error('Conversion Rate to KRW is required.');if(!method)throw new Error('Payment Method is required.');if(!date)throw new Error('Payment Date is required.');if(method.toLowerCase()!=='cash'&&!reference)throw new Error('Payment Reference is required for non-cash sale payments.');if(!files?.length)throw new Error('Receipt / evidence is mandatory for a new buyer payment.');
    const krw=currency==='KRW'?original:original*fx;if(requireFull&&krw+0.005<neededKrw)throw new Error(`Payment is less than the amount required to complete this sale. Received: KRW ${krw.toLocaleString()} / Required: KRW ${Number(neededKrw).toLocaleString()}.`);const allocated=Math.min(krw,Math.max(0,neededKrw));
    let account=null;try{account=configuredPaymentAccount(req,businessUnitId,method,req.body.payment_account_id,{requiredForNonCash:true,direction:'receipt'})}catch(e){throw new Error(e.message)}
    const excess=Math.max(0,krw-Math.max(0,neededKrw)),first=files[0];const r=db.prepare(`INSERT INTO excavator_buyer_payments(buyer_id,asset_id,payment_type,original_amount,currency,fx_rate,krw_amount,payment_date,method,reference,receipt_file,notes,status,created_by,source_type,source_id,payment_account_id,credit_eligible) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(buyer.id,asset.id,'Sale Payment',original,currency,fx,krw,date,method,reference,first.filename,note||'Created from machine sale','Active',req.user.id,'Excavator Sale',saleId,account?.id||null,excess>0.005?1:0);
    const paymentId=Number(r.lastInsertRowid),docId=addBuyerEvidence({buyerId:buyer.id,paymentId,assetId:asset.id,files,userId:req.user.id});financeSync({businessUnitId,type:'Revenue',category:'Excavator Buyer Payment',amount:krw,description:'Buyer '+buyer.name+' payment for '+asset.asset_no,paymentMethod:method,reference,paymentAccountId:account?.id||null,createdBy:req.user.id,sourceType:'Excavator Buyer Payment',sourceId:paymentId,receiptFile:first.filename,originalAmount:original,originalCurrency:currency,fxRate:fx,transactionDate:date,sourceLabel:'Excavator → Buyer Payment',sourceRecordId:buyer.id,sourcePaymentId:paymentId});
    if(allocated>0.005)db.prepare(`INSERT INTO excavator_buyer_payment_allocations(payment_id,buyer_id,asset_id,amount_krw,allocation_date,created_by,notes,status) VALUES(?,?,?,?,?,?,?,'Active')`).run(paymentId,buyer.id,asset.id,allocated,date,req.user.id,note||'New sale payment allocated to machine');
    return {paymentId,documentId:docId,original,currency,fx,krw,allocated,excess,method,date,reference,accountId:account?.id||null,receipt:first.filename};
  }
  function syncMachineSaleMirror(asset,saleId,buyerId,userId,date){
    const total=allocatedTotal(asset.id),rows=allocationsForAsset(asset.id),methods=[...new Set(rows.map(x=>x.method||x.payment_type).filter(Boolean))],refs=rows.map(x=>x.reference).filter(Boolean),method=methods.length===1?methods[0]:(methods.length?'Mixed Settlement':'Buyer Advance'),reference=refs.length===1?refs[0]:(refs.length?'Multiple payment records':'Buyer advance allocation');
    const linked=db.prepare("SELECT * FROM excavator_payments WHERE asset_id=? AND source_type='Excavator Sale' AND source_id=? ORDER BY id DESC LIMIT 1").get(asset.id,saleId);
    if(total<=0.005){if(linked&&linked.status!=='Voided')db.prepare("UPDATE excavator_payments SET status='Voided',notes=COALESCE(notes,'')||' | Settlement removed/reversed.' WHERE id=?").run(linked.id);return null}
    if(linked){db.prepare(`UPDATE excavator_payments SET payment_type='Sale',amount=?,paid_date=?,status='Paid',method=?,reference=?,buyer_id=?,payment_source=?,notes=? WHERE id=?`).run(total,date,method,reference,buyerId,methods.length>1?'mixed':'linked','Settlement mirror — no duplicate Finance cash event',linked.id);return Number(linked.id)}
    const r=db.prepare(`INSERT INTO excavator_payments(asset_id,payment_type,amount,due_date,paid_date,status,method,reference,notes,created_by,source_type,source_id,buyer_id,payment_source) VALUES(?,'Sale',?,NULL,?,'Paid',?,?,?,?, 'Excavator Sale',?,?,?)`).run(asset.id,total,date,method,reference,'Settlement mirror — no duplicate Finance cash event',userId,saleId,buyerId,methods.length>1?'mixed':'linked');return Number(r.lastInsertRowid);
  }
  function ensureFullSettlement(assetId,saleAmount){const paid=allocatedTotal(assetId);if(paid+0.005<saleAmount)throw new Error(`Sale cannot be completed until 100% payment is covered. Paid/allocated: KRW ${paid.toLocaleString()} / Sale: KRW ${Number(saleAmount).toLocaleString()}.`);return paid}

  function richSale(asset,businessUnitId){
    const sale=activeSale(asset.id)||anySale(asset.id);if(!sale)return {sale:null};let meta={};try{meta=sale.metadata?JSON.parse(sale.metadata):{}}catch(_){}
    const buyerId=Number(meta.buyer_id||asset.buyer_id||0)||null,buyer=buyerId?db.prepare('SELECT * FROM excavator_buyers WHERE id=? AND business_unit_id=?').get(buyerId,businessUnitId):null,allocations=allocationsForAsset(asset.id),paid=allocations.reduce((n,x)=>n+Number(x.amount_krw||0),0),amount=Number(sale.amount||0),outstanding=Math.max(0,amount-paid);
    const payments=[];const seen=new Set();
    const pushPayment=(p)=>{if(!p||seen.has(Number(p.id||p.payment_id)))return;const id=Number(p.id||p.payment_id);seen.add(id);const alloc=allocations.filter(z=>Number(z.payment_id)===id).reduce((n,z)=>n+Number(z.amount_krw||0),0);payments.push({id,payment_type:p.payment_type,original_amount:p.original_amount,currency:p.currency,fx_rate:p.fx_rate,krw_amount:p.krw_amount,payment_date:p.payment_date,method:p.method,reference:p.reference,receipt_file:p.receipt_file,receipt_document_id:p.receipt_document_id,payment_account_id:p.payment_account_id,source_type:p.source_type,source_id:p.source_id,status:p.payment_status||p.status||'Active',credit_eligible:Number(p.credit_eligible||0),allocated_to_sale:alloc,receipt_url:p.receipt_file?'/uploads/'+String(p.receipt_file).replace(/^\/+/, ''):''})};
    for(const a of allocations)pushPayment(a);
    // Include direct sale receipts even when an allocation has since been reversed/corrected, so Update Sale can show the original payment status rather than hiding history.
    for(const p of db.prepare("SELECT * FROM excavator_buyer_payments WHERE source_type='Excavator Sale' AND source_id=? ORDER BY id").all(sale.id))pushPayment(p);
    payments.sort((a,b)=>String(a.payment_date||'').localeCompare(String(b.payment_date||''))||Number(a.id)-Number(b.id));
    const document=db.prepare("SELECT * FROM excavator_documents WHERE asset_id=? AND transaction_id=? AND title LIKE 'Machine Sale Document%' ORDER BY id DESC LIMIT 1").get(asset.id,sale.id);
    return {sale:{id:sale.id,sale_type:sale.type,sale_date:sale.transaction_date,customer_name:meta.customer_name||sale.counterparty||buyer?.name||'',selling_price:amount,destination_country:meta.destination_country||'',shipping_reference:meta.shipping_reference||'',sell_note:meta.sell_note||'',notes:sale.notes||'',buyer_id:buyerId,status:sale.status,void_reason:sale.void_reason||'',payment_source:meta.payment_source||'',settlement_mode:meta.settlement_mode||'',paid_krw:paid,outstanding_krw:outstanding,payment_status:sale.status==='Cancelled'?'Voided':outstanding<=0.005?'Paid':paid>0?'Partially Paid':'Pending'},buyer,allocations,payments,document,available_buyer_credit_krw:buyerId?buyerAvailable(buyerId,asset.id):0};
  }

  app.get('/api/v326/excavator/assets/:id/sale',auth,allow('dashboard','sales','finance','purchases','inventory'),(req,res)=>{const b=excavatorGuard(req,res);if(!b)return;const a=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(req.params.id,b);if(!a)return res.status(404).json({error:'Machine not found'});res.json(richSale(a,b))});
  app.get('/api/v326/excavator/assets/:id/status-actions',auth,allow('dashboard','sales','finance','purchases','inventory'),(req,res)=>{const b=excavatorGuard(req,res);if(!b)return;const a=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(req.params.id,b);if(!a)return res.status(404).json({error:'Machine not found'});res.json({asset_id:a.id,stage:a.lifecycle_stage,archived:!!Number(a.archived||0),can_void:canAction(req,'void',b),can_archive:canAction(req,'void',b),can_restore:canAction(req,'void',b),sale:richSale(a,b).sale})});

  function completeSale(req,res,skipApproval=false){
    const b=excavatorGuard(req,res);if(!b)return;const asset=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(req.params.id,b);if(!asset)return res.status(404).json({error:'Machine not found'});if(asset.lifecycle_stage==='Cancelled')return res.status(400).json({error:'Cancelled machines cannot be sold.'});if(Number(asset.archived||0))return res.status(400).json({error:'Archived machines must be restored before sale changes.'});
    const existing=activeSale(asset.id),isUpdate=!!existing,paidPurchase=Number(db.prepare("SELECT COALESCE(SUM(amount),0) v FROM excavator_payments WHERE asset_id=? AND payment_type='Purchase' AND status='Paid'").get(asset.id)?.v||0);if(paidPurchase+0.005<Number(asset.purchase_price||0))return res.status(400).json({error:'This machine cannot be sold until the complete purchase price has been paid.'});
    let saleType=text(req.body.sale_type),destination=text(req.body.destination_country),saleDate=text(req.body.sale_date),customer=text(req.body.customer_name),buyerId=req.body.buyer_id?Number(req.body.buyer_id):null,amount=num(req.body.selling_price),shipping=text(req.body.shipping_reference),sellNote=text(req.body.sell_note);
    let buyer=buyerId?db.prepare('SELECT * FROM excavator_buyers WHERE id=? AND business_unit_id=? AND active=1').get(buyerId,b):null;if(buyerId&&!buyer)return res.status(400).json({error:'Invalid buyer selected.'});
    if(buyer){const c=text(buyer.country).toLowerCase().replace(/\s+/g,' '),local=text(buyer.buyer_type).toLowerCase()==='local'||['south korea','korea','republic of korea','korea, republic of','republic of korea (south korea)'].includes(c);saleType=local?'Local Sale':'Export Sale';destination=local?'':text(buyer.country||destination)}
    if(!['Local Sale','Export Sale'].includes(saleType))return res.status(400).json({error:'Sale Type is required.'});if(!saleDate)return res.status(400).json({error:'Sale Date is required.'});if(!customer)return res.status(400).json({error:'Customer / Buyer is required.'});if(amount<=0)return res.status(400).json({error:'Selling Price is required and must be greater than zero.'});if(saleType==='Export Sale'&&!destination)return res.status(400).json({error:'Destination Country is mandatory for export sales.'});if(!shipping)return res.status(400).json({error:'Shipping / Container Reference is required.'});
    const oldRich=isUpdate?richSale(asset,b):null;let settlementMode=text(req.body.settlement_mode||(!isUpdate?'replace':'keep')).toLowerCase(),paymentSource=text(req.body.payment_source||'').toLowerCase();if(!['buyer_advance','new_payment','advance_plus_new'].includes(paymentSource))paymentSource=buyerId?'buyer_advance':'new_payment';if(!buyerId)paymentSource='new_payment';
    const cost=excavatorCostSnapshot(asset.id),approvalTokens=[];
    if(!skipApproval&&isUpdate){const ap=maybeCreateApproval({req,businessUnitId:b,actionKey:'completed_sale.update',type:'Update Completed Machine Sale',amount,reason:`Update ${asset.asset_no} completed sale`,sourceEntity:'excavator_sale',sourceId:existing.id,priority:'High',snapshot:{...approvalRequestSnapshot(req,{business_unit_id:b,asset_id:asset.id}),v326:true}});if(stopForApproval(res,ap,'Sale update submitted for approval. It will be applied automatically after final approval.'))return;if(ap.approval)approvalTokens.push(ap.approval)}
    if(!skipApproval&&!isUpdate&&amount<Number(cost?.total||0)){const ap=maybeCreateApproval({req,businessUnitId:b,actionKey:'sale.loss_or_low_margin',type:'Loss / Below-Margin Excavator Sale',amount,reason:`Sale price KRW ${amount} is below actual machine cost KRW ${Number(cost?.total||0)}`,sourceEntity:'excavator_asset',sourceId:asset.id,priority:'Critical',snapshot:{...approvalRequestSnapshot(req,{business_unit_id:b,asset_id:asset.id}),v326:true}});if(stopForApproval(res,ap,'Below-margin sale submitted for approval. It will be completed automatically after final approval.'))return;if(ap.approval)approvalTokens.push(ap.approval)}
    try{
      const result=db.transaction(()=>{
        if(!buyerId){const buyerType=text(req.body.new_buyer_type)==='Local'?'Local':'International',name=text(req.body.new_buyer_name||customer),country=text(req.body.new_buyer_country||(buyerType==='Local'?'South Korea':destination));if(!name||!country)throw new Error('Complete new buyer name and country are required.');const r=db.prepare(`INSERT INTO excavator_buyers(business_unit_id,name,country,location,contact_person,phone,whatsapp,email,address,payment_terms,notes,buyer_type,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b,name,country,req.body.new_buyer_location||'',req.body.new_buyer_contact_person||'',req.body.new_buyer_phone||'',req.body.new_buyer_whatsapp||'',req.body.new_buyer_email||'',req.body.new_buyer_address||'',req.body.new_buyer_payment_terms||'',req.body.new_buyer_notes||'',buyerType,req.user.id);buyerId=Number(r.lastInsertRowid);buyer=db.prepare('SELECT * FROM excavator_buyers WHERE id=?').get(buyerId);paymentSource='new_payment'}
        const previousBuyerId=isUpdate?Number(oldRich?.sale?.buyer_id||0)||null:null,buyerChanged=isUpdate&&previousBuyerId&&Number(previousBuyerId)!==Number(buyerId);
        if(buyerChanged){reverseAllAllocations(asset.id,req.user,'Sale buyer changed during update');settlementMode='replace'}
        let saleId=existing?.id||0;
        if(!saleId){const rr=db.prepare(`INSERT INTO excavator_transactions(asset_id,type,stage,transaction_date,counterparty,amount,currency,status,notes,metadata,created_by,updated_by,updated_at) VALUES(?,?,?,?,?,?,'KRW','Completed',?,?,?,?,CURRENT_TIMESTAMP)`).run(asset.id,saleType,'Sold / Completed',saleDate,customer,amount,req.body.notes||'',JSON.stringify({}),req.user.id,req.user.id);saleId=Number(rr.lastInsertRowid)}
        let before=allocatedTotal(asset.id),cashResult=null,advanceAllocated=0;
        const requestedAdvance=Math.max(0,num(req.body.advance_amount_krw));
        const allocateCombined=(needed,notePrefix)=>{
          if(!buyerId)throw new Error('Buyer advance can be used only for an existing buyer.');
          const adv=Math.min(Math.max(0,requestedAdvance),Math.max(0,needed));
          if(adv<=0.005)throw new Error('Enter the buyer advance amount to use for the combined settlement.');
          if(adv>=needed-0.005)throw new Error('Combined settlement requires both buyer advance and a new payment. Reduce the advance amount or choose Buyer Advance only.');
          advanceAllocated+=allocateAdvance({buyerId,assetId:asset.id,amount:adv,date:saleDate,userId:req.user.id,note:notePrefix+' buyer advance allocated'});
          const cashNeeded=Math.max(0,needed-adv);
          cashResult=createCashReceipt({req,businessUnitId:b,buyer,asset,saleId,neededKrw:cashNeeded,files:req.files||[],note:notePrefix+' new buyer payment recorded'});
        };
        if(!isUpdate||settlementMode==='replace'){
          if(isUpdate&&settlementMode==='replace')reverseAllAllocations(asset.id,req.user,'Sale settlement replaced during update');
          if(paymentSource==='buyer_advance'){if(!buyerId)throw new Error('Buyer advance can be used only for an existing buyer.');advanceAllocated+=allocateAdvance({buyerId,assetId:asset.id,amount,date:saleDate,userId:req.user.id,note:isUpdate?'Buyer advance allocated after sale settlement replacement':'Buyer advance allocated to machine sale'})}
          else if(paymentSource==='advance_plus_new')allocateCombined(amount,isUpdate?'Replacement sale settlement:':'Completed machine sale:');
          else cashResult=createCashReceipt({req,businessUnitId:b,buyer,asset,saleId,neededKrw:amount,files:req.files||[],note:isUpdate?'Replacement/new payment recorded during sale update':'Created from completed machine sale'});
        }else{
          // Preserve existing settlement. Release over-allocation on price decrease; require only the increase to be covered.
          before=allocatedTotal(asset.id);if(before>amount+0.005)releaseAllocationAmount(asset.id,before-amount,req.user,'Sale price reduced; excess returned to buyer credit');
          let current=allocatedTotal(asset.id),needed=Math.max(0,amount-current);
          if(needed>0.005){
            if(settlementMode==='keep')throw new Error(`Sale price increased. Additional settlement of KRW ${needed.toLocaleString()} is required.`);
            if(paymentSource==='buyer_advance')advanceAllocated+=allocateAdvance({buyerId,assetId:asset.id,amount:needed,date:saleDate,userId:req.user.id,note:'Additional buyer advance allocated during sale update'});
            else if(paymentSource==='advance_plus_new')allocateCombined(needed,'Additional sale settlement:');
            else cashResult=createCashReceipt({req,businessUnitId:b,buyer,asset,saleId,neededKrw:needed,files:req.files||[],note:'Additional buyer payment recorded during sale update'});
          }
        }
        const paid=ensureFullSettlement(asset.id,amount),allocRows=allocationsForAsset(asset.id),sources=[...new Set(allocRows.map(x=>x.source_type==='Excavator Sale'?'new_payment':'buyer_advance'))],finalSource=sources.length>1?'advance_plus_new':(sources[0]||paymentSource);
        const metadata={destination_country:destination,shipping_reference:shipping,customer_name:customer,payment_source:finalSource,settlement_mode:settlementMode,sell_note:sellNote,buyer_id:buyerId,buyer_payment_allocated_krw:paid,buyer_advance_allocated_krw:advanceAllocated,new_payment_received_krw:cashResult?.krw||0,new_payment_allocated_krw:cashResult?.allocated||0,buyer_credit_added_krw:cashResult?.excess||0,updated_sale:isUpdate};
        db.prepare(`UPDATE excavator_transactions SET type=?,stage='Sold / Completed',transaction_date=?,counterparty=?,amount=?,currency='KRW',status='Completed',notes=?,metadata=?,updated_by=?,updated_at=CURRENT_TIMESTAMP,void_reason='',voided_by=NULL,voided_at=NULL WHERE id=?`).run(saleType,saleDate,customer,amount,req.body.notes||'',JSON.stringify(metadata),req.user.id,saleId);
        const operationalFinanceId=financeSync({businessUnitId:b,type:'Revenue',category:'Excavator Machine Sale',amount,description:'Excavator sale '+asset.asset_no,paymentMethod:'Operational',reference:'Sale '+saleId,createdBy:req.user.id,sourceType:'Excavator Sale',sourceId:saleId,resetVerification:isUpdate,originalAmount:amount,originalCurrency:'KRW',fxRate:1,transactionDate:saleDate,sourceLabel:'Excavator → Machine Sale',sourceRecordId:asset.id});
        db.prepare("UPDATE excavator_assets SET selling_price=?,customer_id=NULL,buyer_id=?,status='Sold',lifecycle_stage='Sold / Completed' WHERE id=? AND business_unit_id=?").run(amount,buyerId,asset.id,b);
        const mirrorId=syncMachineSaleMirror(asset,saleId,buyerId,req.user.id,saleDate);db.prepare('INSERT INTO excavator_lifecycle_events(asset_id,from_stage,to_stage,note,user_id) VALUES(?,?,?,?,?)').run(asset.id,isUpdate?'Sold / Completed':asset.lifecycle_stage,'Sold / Completed',isUpdate?'Sale updated; settlement revalidated':'Sale completed; 100% settlement confirmed',req.user.id);
        return {transaction_id:saleId,buyer_id:buyerId,payment_source:finalSource,settlement_mode:settlementMode,paid_krw:paid,outstanding_krw:0,updated:isUpdate,finance_id:operationalFinanceId,buyer_payment_id:cashResult?.paymentId||null,buyer_payment_document_id:cashResult?.documentId||null,buyer_advance_allocated_krw:advanceAllocated,new_payment_received_krw:cashResult?.krw||0,new_payment_allocated_krw:cashResult?.allocated||0,buyer_credit_added_krw:cashResult?.excess||Math.max(0,before-amount),sale_payment_id:mirrorId};
      })();
      const pdf=finalizeExcavatorSalePdf({assetId:asset.id,businessUnitId:b,saleId:result.transaction_id,userId:req.user.id,language:req.headers['x-language']==='en'?'en':'ko'});for(const ap of approvalTokens)markApprovalExecuted(ap,req.user,{transaction_id:result.transaction_id,asset_id:asset.id});notify(req.user.id,'info',result.updated?'Excavator sale updated':'Excavator machine sold',`${asset.asset_no} ${result.updated?'sale updated':'sold'} for ${amount.toLocaleString()} KRW · payment fully covered.`,b,'excavator_asset',asset.id,'excavator');audit(req.user,'excavator_sale',result.transaction_id,result.updated?'update-v326':'complete-v326',JSON.stringify({...result,pdf_document_id:pdf.document_id}));res.json({ok:true,...result,...pdf,stage:'Sold / Completed',sale_payment_status:'Paid'});
    }catch(e){console.error('V30.26 complete/update sale:',e);res.status(400).json({error:e.message})}
  }
  app.post('/api/v326/excavator/assets/:id/complete-sale',auth,allow('sales','finance','purchases','inventory'),upload.array('payment_evidence',10),(req,res)=>completeSale(req,res,false));

  app.post('/api/v326/excavator/assets/:id/add-buyer-payment',auth,allow('sales','finance'),upload.array('payment_evidence',10),(req,res)=>{const b=excavatorGuard(req,res);if(!b)return;const asset=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(req.params.id,b);if(!asset)return res.status(404).json({error:'Machine not found'});const sale=activeSale(asset.id);if(!sale)return res.status(400).json({error:'No active sale exists for this machine.'});let meta={};try{meta=JSON.parse(sale.metadata||'{}')}catch(_){}const buyerId=Number(meta.buyer_id||asset.buyer_id||0),buyer=db.prepare('SELECT * FROM excavator_buyers WHERE id=? AND business_unit_id=?').get(buyerId,b);if(!buyer)return res.status(400).json({error:'The sale has no valid buyer record.'});const outstanding=Math.max(0,Number(sale.amount||0)-allocatedTotal(asset.id));try{const r=db.transaction(()=>{const receipt=createCashReceipt({req,businessUnitId:b,buyer,asset,saleId:sale.id,neededKrw:outstanding,files:req.files||[],note:outstanding>0?'Additional payment received and allocated to sale':'Additional buyer payment received as unallocated advance/credit',requireFull:false});syncMachineSaleMirror(asset,sale.id,buyer.id,req.user.id,text(req.body.payment_date)||sale.transaction_date);return receipt})();const newOutstanding=Math.max(0,Number(sale.amount||0)-allocatedTotal(asset.id));const pdf=finalizeExcavatorSalePdf({assetId:asset.id,businessUnitId:b,saleId:sale.id,userId:req.user.id,language:req.headers['x-language']==='en'?'en':'ko'});audit(req.user,'excavator_buyer_payment',r.paymentId,'add-another-payment',JSON.stringify({asset_id:asset.id,sale_id:sale.id,allocated:r.allocated,excess:r.excess}));res.json({ok:true,payment_id:r.paymentId,received_krw:r.krw,allocated_to_sale_krw:r.allocated,buyer_credit_added_krw:r.excess,outstanding_krw:newOutstanding,document_id:pdf.document_id,document_url:pdf.document_url})}catch(e){res.status(400).json({error:e.message})}});

  app.post('/api/v326/excavator/buyer-payments/:paymentId/correct',auth,allow('sales','finance'),upload.array('payment_evidence',10),(req,res)=>{
    const p=db.prepare(`SELECT p.*,b.business_unit_id,b.name buyer_name FROM excavator_buyer_payments p JOIN excavator_buyers b ON b.id=p.buyer_id WHERE p.id=?`).get(req.params.paymentId);
    if(!p)return res.status(404).json({error:'Buyer payment not found'});
    if(!canAction(req,'correct',p.business_unit_id)&&req.user.role!=='CEO / Owner')return res.status(403).json({error:'You are not authorized to correct this buyer payment.'});
    const reason=text(req.body.reason);if(!reason)return res.status(400).json({error:'Correction reason is required.'});
    const currency=text(req.body.payment_currency||p.currency||'KRW').toUpperCase(),fx=currency==='KRW'?1:num(req.body.payment_fx_rate||p.fx_rate),original=num(req.body.payment_amount||p.original_amount),method=text(req.body.payment_method||p.method),date=text(req.body.payment_date||p.payment_date),reference=text(req.body.payment_reference??p.reference),newKrw=currency==='KRW'?original:original*fx;
    let account=null;try{account=configuredPaymentAccount(req,p.business_unit_id,method,req.body.payment_account_id||p.payment_account_id,{requiredForNonCash:true,direction:'receipt'})}catch(e){return res.status(e.status||400).json({error:e.message})}
    if(original<=0||fx<=0)return res.status(400).json({error:'Valid payment amount and conversion rate are required.'});
    if(method.toLowerCase()!=='cash'&&!reference)return res.status(400).json({error:'Payment Reference is required for non-cash payments.'});
    const financialChanged=Math.abs(newKrw-Number(p.krw_amount||0))>0.005||currency!==String(p.currency||'KRW')||Math.abs(fx-Number(p.fx_rate||1))>0.000001||method!==String(p.method||'')||Number(account?.id||0)!==Number(p.payment_account_id||0)||date!==String(p.payment_date||'');
    const activeBefore=db.prepare("SELECT * FROM excavator_buyer_payment_allocations WHERE payment_id=? AND COALESCE(status,'Active')='Active' ORDER BY id").all(p.id);
    const affectedAssets=[...new Set([Number(p.asset_id||0),...activeBefore.map(x=>Number(x.asset_id||0))].filter(Boolean))];
    try{
      const out=db.transaction(()=>{
        if(!financialChanged){
          db.prepare("UPDATE excavator_buyer_payments SET reference=?,notes=COALESCE(notes,'')||?,payment_account_id=? WHERE id=?").run(reference,` | Correction: ${reason}`,account?.id||null,p.id);
          if(req.files?.length)addBuyerEvidence({buyerId:p.buyer_id,paymentId:p.id,assetId:p.asset_id,files:req.files,userId:req.user.id,title:'Buyer Payment Corrected Receipt / Evidence'});
          financeSync({businessUnitId:p.business_unit_id,type:'Revenue',category:'Excavator Buyer Payment',amount:Number(p.krw_amount||0),description:'Buyer '+p.buyer_name+' payment',paymentMethod:p.method,reference,paymentAccountId:p.payment_account_id||null,createdBy:req.user.id,sourceType:'Excavator Buyer Payment',sourceId:p.id,receiptFile:req.files?.[0]?.filename||p.receipt_file||'',originalAmount:p.original_amount,originalCurrency:p.currency,fxRate:p.fx_rate,transactionDate:p.payment_date,sourceLabel:'Excavator → Buyer Payment',sourceRecordId:p.buyer_id,sourcePaymentId:p.id});
          return {payment_id:p.id,financial_reversal:false};
        }
        const oldAllocated=activeBefore.reduce((n,x)=>n+Number(x.amount_krw||0),0);
        if(newKrw+0.005<oldAllocated)throw new Error(`Corrected payment would be smaller than the amount currently allocated to sales. Allocated: KRW ${oldAllocated.toLocaleString()}. Add replacement coverage or reduce/reallocate the sale first.`);
        db.prepare("UPDATE excavator_buyer_payment_allocations SET status='Reversed',void_reason=?,voided_by=?,voided_at=CURRENT_TIMESTAMP WHERE payment_id=? AND COALESCE(status,'Active')='Active'").run('Payment corrected: '+reason,req.user.id,p.id);
        db.prepare("UPDATE excavator_buyer_payments SET status='Voided',notes=COALESCE(notes,'')||? WHERE id=?").run(` | Reversed by correction: ${reason}`,p.id);
        voidFinanceBySource('Excavator Buyer Payment',p.id,'Payment corrected: '+reason,req.user.id,p.business_unit_id);
        const first=req.files?.[0],receipt=first?.filename||p.receipt_file||'';if(!receipt)throw new Error('Receipt / evidence is required for the corrected payment.');
        const r=db.prepare(`INSERT INTO excavator_buyer_payments(buyer_id,asset_id,payment_type,original_amount,currency,fx_rate,krw_amount,payment_date,method,reference,receipt_file,receipt_document_id,notes,status,created_by,source_type,source_id,payment_account_id,credit_eligible) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'Active',?,?,?,?,?)`).run(p.buyer_id,p.asset_id,p.payment_type,original,currency,fx,newKrw,date,method,reference,receipt,p.receipt_document_id,`Corrected replacement for payment #${p.id}: ${reason}`,req.user.id,p.source_type,p.source_id,account?.id||null,newKrw>oldAllocated+0.005?1:Number(p.credit_eligible||0));
        const newId=Number(r.lastInsertRowid);
        if(req.files?.length)addBuyerEvidence({buyerId:p.buyer_id,paymentId:newId,assetId:p.asset_id,files:req.files,userId:req.user.id,title:'Buyer Payment Corrected Receipt / Evidence'});
        for(const al of activeBefore)db.prepare(`INSERT INTO excavator_buyer_payment_allocations(payment_id,buyer_id,asset_id,amount_krw,allocation_date,created_by,notes,status) VALUES(?,?,?,?,?,?,?,'Active')`).run(newId,p.buyer_id,al.asset_id,Number(al.amount_krw||0),date,req.user.id,`Reallocated from corrected payment #${p.id}`);
        financeSync({businessUnitId:p.business_unit_id,type:'Revenue',category:'Excavator Buyer Payment',amount:newKrw,description:'Corrected buyer '+p.buyer_name+' payment',paymentMethod:method,reference,paymentAccountId:account?.id||null,createdBy:req.user.id,sourceType:'Excavator Buyer Payment',sourceId:newId,receiptFile:receipt,originalAmount:original,originalCurrency:currency,fxRate:fx,transactionDate:date,sourceLabel:'Excavator → Buyer Payment',sourceRecordId:p.buyer_id,sourcePaymentId:newId});
        return {payment_id:newId,replaced_payment_id:p.id,financial_reversal:true};
      })();
      const refreshed=[];
      for(const assetId of affectedAssets){const a=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(assetId,p.business_unit_id),sale=a&&activeSale(assetId);if(!a||!sale)continue;syncMachineSaleMirror(a,sale.id,Number(a.buyer_id||p.buyer_id),req.user.id,date);try{const pdf=finalizeExcavatorSalePdf({assetId,businessUnitId:p.business_unit_id,saleId:sale.id,userId:req.user.id,language:req.headers['x-language']==='en'?'en':'ko'});refreshed.push({asset_id:assetId,sale_id:sale.id,document_id:pdf.document_id,document_url:pdf.document_url})}catch(e){console.warn('V30.26 payment correction PDF refresh',e.message)}}
      audit(req.user,'excavator_buyer_payment',out.payment_id,'correct-v326',JSON.stringify({reason,financial_reversal:out.financial_reversal,replaced_payment_id:out.replaced_payment_id||null,affected_assets:affectedAssets}));
      res.json({ok:true,...out,refreshed_sales:refreshed});
    }catch(e){res.status(400).json({error:e.message})}
  });

  function voidSaleCore({assetId,businessUnitId,user,reason,language='ko'}){
    const asset=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(assetId,businessUnitId);if(!asset)throw new Error('Machine not found');const sale=activeSale(asset.id);if(!sale)throw new Error('No active completed sale was found.');let previous=db.prepare("SELECT from_stage FROM excavator_lifecycle_events WHERE asset_id=? AND to_stage='Sold / Completed' ORDER BY id DESC LIMIT 1").get(asset.id)?.from_stage||'Ready for Sale';if(!previous||previous==='Sold / Completed')previous='Ready for Sale';
    db.transaction(()=>{reverseAllAllocations(asset.id,user,'Sale voided: '+reason);db.prepare("UPDATE excavator_buyer_payments SET credit_eligible=1,notes=COALESCE(notes,'')||? WHERE source_type='Excavator Sale' AND source_id=? AND COALESCE(status,'Active')!='Voided'").run(` | Sale #${sale.id} voided; receipt retained as buyer credit`,sale.id);db.prepare("UPDATE excavator_payments SET status='Voided',notes=COALESCE(notes,'')||? WHERE asset_id=? AND source_type='Excavator Sale' AND source_id=? AND status!='Voided'").run(' | Sale voided: '+reason,asset.id,sale.id);voidFinanceBySource('Excavator Sale',sale.id,reason,user.id,businessUnitId);db.prepare("UPDATE excavator_transactions SET status='Cancelled',void_reason=?,voided_by=?,voided_at=CURRENT_TIMESTAMP,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(reason,user.id,user.id,sale.id);db.prepare("UPDATE excavator_assets SET selling_price=0,buyer_id=NULL,status='Available',lifecycle_stage=? WHERE id=?").run(previous,asset.id);db.prepare('INSERT INTO excavator_lifecycle_events(asset_id,from_stage,to_stage,note,user_id) VALUES(?,?,?,?,?)').run(asset.id,'Sold / Completed',previous,'Sale voided: '+reason,user.id)})();
    const pdf=finalizeExcavatorSalePdf({assetId:asset.id,businessUnitId,saleId:sale.id,userId:user.id,language,voided:true,voidReason:reason});audit(user,'excavator_sale',sale.id,'void-v326',JSON.stringify({asset_id:asset.id,reason,restored_stage:previous,pdf_document_id:pdf.document_id}));return {sale_id:sale.id,asset_id:asset.id,stage:previous,...pdf};
  }
  app.post('/api/v326/excavator/assets/:id/sale/void',auth,allow('sales','finance','purchases','inventory'),(req,res)=>{const b=excavatorGuard(req,res);if(!b)return;if(!canAction(req,'void',b))return res.status(403).json({error:'You are not authorized to void completed machine sales.'});const reason=text(req.body.reason);if(!reason)return res.status(400).json({error:'Void reason is required.'});const asset=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(req.params.id,b);if(!asset)return res.status(404).json({error:'Machine not found'});const sale=activeSale(asset.id);if(!sale)return res.status(400).json({error:'No active sale was found.'});const ap=maybeCreateApproval({req,businessUnitId:b,actionKey:'completed_sale.void',type:'Void Completed Machine Sale',amount:Number(sale.amount||0),reason,sourceEntity:'excavator_sale',sourceId:sale.id,priority:'Critical',snapshot:{...approvalRequestSnapshot(req,{business_unit_id:b,asset_id:asset.id}),v326:true,void_reason:reason}});if(stopForApproval(res,ap,'Sale void submitted for approval. It will be reversed automatically after final approval.'))return;try{const out=voidSaleCore({assetId:asset.id,businessUnitId:b,user:req.user,reason,language:req.headers['x-language']==='en'?'en':'ko'});if(ap.approval)markApprovalExecuted(ap.approval,req.user,out);notify(req.user.id,'warning','Excavator sale voided',`${asset.asset_no} sale was voided. Buyer settlement was returned to unallocated credit where applicable.`,b,'excavator_asset',asset.id,'excavator');res.json({ok:true,...out})}catch(e){res.status(400).json({error:e.message})}});

  app.post('/api/v326/excavator/assets/:id/archive',auth,allow('sales','inventory'),(req,res)=>{const b=excavatorGuard(req,res);if(!b)return;if(!canAction(req,'void',b))return res.status(403).json({error:'You are not authorized to archive machines.'});const reason=text(req.body.reason);if(!reason)return res.status(400).json({error:'Archive reason is required.'});const a=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(req.params.id,b);if(!a)return res.status(404).json({error:'Machine not found'});if(a.lifecycle_stage!=='Sold / Completed'&&a.lifecycle_stage!=='Cancelled')return res.status(400).json({error:'Only completed or cancelled machines can be archived.'});db.prepare("UPDATE excavator_assets SET archived=1,archive_reason=?,archived_by=?,archived_at=CURRENT_TIMESTAMP WHERE id=?").run(reason,req.user.id,a.id);audit(req.user,'excavator_asset',a.id,'archive-v326',JSON.stringify({reason}));res.json({ok:true,archived:true})});
  app.post('/api/v326/excavator/assets/:id/restore',auth,allow('sales','inventory'),(req,res)=>{const b=excavatorGuard(req,res);if(!b)return;if(!canAction(req,'void',b))return res.status(403).json({error:'You are not authorized to restore archived machines.'});const a=db.prepare('SELECT * FROM excavator_assets WHERE id=? AND business_unit_id=?').get(req.params.id,b);if(!a)return res.status(404).json({error:'Machine not found'});db.prepare("UPDATE excavator_assets SET archived=0,archive_reason='',archived_by=NULL,archived_at=NULL WHERE id=?").run(a.id);audit(req.user,'excavator_asset',a.id,'restore-v326');res.json({ok:true,archived:false})});

  function executeApprovedSale(approval,decider){const snap=storedApprovalSnapshot(approval),requester=storedApprovalUser(approval),assetId=Number(snap.asset_id||0)||Number(db.prepare('SELECT asset_id FROM excavator_transactions WHERE id=?').get(approval.source_id)?.asset_id||0);if(!assetId)return {executed:false,error:'Approved machine sale is missing its linked machine.'};const request={params:{id:assetId},body:snap.body||{},files:storedApprovalFiles(approval),user:requester,selected_business_unit_id:Number(approval.business_unit_id),headers:{'x-language':'ko'}};const result=captureInternalAction(response=>completeSale(request,response,true)),payload=result.payload||{};if(!payload.transaction_id)return {executed:false,error:'Approved sale completed without a transaction identifier.'};db.prepare("UPDATE approvals SET source_entity='excavator_sale',source_id=?,execution_error='',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(Number(payload.transaction_id),approval.id);markApprovalExecuted(approval,decider,{transaction_id:Number(payload.transaction_id),asset_id:assetId,buyer_id:payload.buyer_id,finance_id:payload.finance_id,document_id:payload.document_id});return {executed:true,action:payload.updated?'Machine sale updated':'Machine sale completed',...payload}}
  function executeApprovedVoid(approval,decider){const snap=storedApprovalSnapshot(approval),assetId=Number(snap.asset_id||0)||Number(db.prepare('SELECT asset_id FROM excavator_transactions WHERE id=?').get(approval.source_id)?.asset_id||0);if(!assetId)return {executed:false,error:'Approved sale void is missing its machine.'};try{const out=voidSaleCore({assetId,businessUnitId:Number(approval.business_unit_id),user:decider,reason:text(snap.void_reason||approval.reason),language:'ko'});markApprovalExecuted(approval,decider,out);return {executed:true,action:'Machine sale voided',...out}}catch(e){return {executed:false,error:e.message}}}

  console.info('Blue Ocean Market V30.26.0 Excavator sale/payment lifecycle installed');
  return {VERSION,executeApprovedSale,executeApprovedVoid,buyerAvailable,richSale};
}
module.exports={install,VERSION};
