'use strict';
// Official V30.58 reports. All amounts below derive exclusively from posted GL lines.
function install({app,db,auth,allow,currentUnit,enforceUnit}){
 const round=n=>Math.round((Number(n||0)+Number.EPSILON)*100)/100;
 const bad=(status,message)=>Object.assign(new Error(message),{status});
 const valid=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
 function range(q){let from=String(q.from||''),to=String(q.to||'');const period=String(q.period||''),grain=String(q.grain||'');if(period){if(grain==='month'&&/^\d{4}-\d{2}$/.test(period)){from=period+'-01';to=new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5,7)),0)).toISOString().slice(0,10)}else if(grain==='year'&&/^\d{4}$/.test(period)){from=period+'-01-01';to=period+'-12-31'}else if(grain==='quarter'&&/^\d{4}-Q[1-4]$/.test(period)){const y=Number(period.slice(0,4)),q=Number(period.at(-1)),m=(q-1)*3+1;from=`${y}-${String(m).padStart(2,'0')}-01`;to=new Date(Date.UTC(y,m+2,0)).toISOString().slice(0,10)}else throw bad(400,'Select a valid month, quarter or year.')}if(!to)to=new Date().toISOString().slice(0,10);if(!from)from='0001-01-01';if(!valid(to)||from!=='0001-01-01'&&!valid(from)||from>to)throw bad(400,'Select a valid date range.');const lower=Date.parse(from+'T00:00:00Z'),upper=Date.parse(to+'T00:00:00Z'),priorStart=lower-(upper-lower)-86400000,priorEnd=lower-86400000;return {from,to,prior_from:from==='0001-01-01'||priorStart<Date.parse('0001-01-01T00:00:00Z')?null:new Date(priorStart).toISOString().slice(0,10),prior_to:from==='0001-01-01'?null:new Date(priorEnd).toISOString().slice(0,10)}}
 function scope(req){const selected=Number(currentUnit(req)||0);if(req.user.role==='CEO / Owner')return selected||null;const bu=selected||Number(req.user.business_unit_id||0);if(!bu||!enforceUnit(req,bu))throw bad(403,'Business unit not permitted');return bu}
 function query(req,res,fn){try{res.json(fn())}catch(e){res.status(e.status||500).json({error:e.message})}}
 function lines(bu,to,from='0001-01-01'){return db.prepare(`SELECT l.id line_id,l.journal_entry_id,j.journal_no,j.transaction_date,j.source_type,j.source_id,j.description,j.finance_entry_id,l.account_id,l.business_unit_id,l.debit_krw,l.credit_krw,l.original_amount,l.original_currency,l.fx_rate,l.entity_type,l.entity_id,a.code,a.name,a.account_type,a.subtype,a.system_key
 FROM accounting_journal_lines l JOIN accounting_journal_entries j ON j.id=l.journal_entry_id JOIN accounting_accounts a ON a.id=l.account_id WHERE j.status IN ('Posted','Reversed') AND j.transaction_date>=? AND j.transaction_date<=? ${bu?'AND l.business_unit_id=?':''} ORDER BY j.transaction_date,j.id,l.id`).all(...(bu?[from,to,bu]:[from,to]))}
 const n=(r)=>Number(r.debit_krw)-Number(r.credit_krw),sum=(arr,fn)=>round(arr.reduce((a,x)=>a+fn(x),0));
 const sign=(a,x)=>['Liability','Equity','Revenue'].includes(a)?-x:x;
 function accountRows(all,from,to){const accounts=db.prepare('SELECT id,code,name,account_type,system_key,normal_balance,active FROM accounting_accounts ORDER BY code').all(),by=new Map(accounts.map(a=>[a.id,{...a,opening_debit_krw:0,opening_credit_krw:0,period_debit_krw:0,period_credit_krw:0,closing_debit_krw:0,closing_credit_krw:0}]));for(const l of all){const r=by.get(l.account_id);if(!r)continue;if(l.transaction_date<from){r.opening_debit_krw+=Number(l.debit_krw);r.opening_credit_krw+=Number(l.credit_krw)}else{r.period_debit_krw+=Number(l.debit_krw);r.period_credit_krw+=Number(l.credit_krw)}r.closing_debit_krw+=Number(l.debit_krw);r.closing_credit_krw+=Number(l.credit_krw)}return [...by.values()].map(r=>({...r,opening_debit_krw:round(r.opening_debit_krw),opening_credit_krw:round(r.opening_credit_krw),period_debit_krw:round(r.period_debit_krw),period_credit_krw:round(r.period_credit_krw),opening_balance_krw:round(sign(r.account_type,r.opening_debit_krw-r.opening_credit_krw)),movement_krw:round(sign(r.account_type,r.period_debit_krw-r.period_credit_krw)),closing_balance_krw:round(sign(r.account_type,r.closing_debit_krw-r.closing_credit_krw))}))}
 function statement(bu,r){const all=lines(bu,r.to),rows=accountRows(all,r.from,r.to),period=rows.filter(x=>['Revenue','Expense'].includes(x.account_type)),profit=sum(period.filter(x=>x.account_type==='Revenue'),x=>x.movement_krw)-sum(period.filter(x=>x.account_type==='Expense'),x=>x.movement_krw),prior=accountRows(lines(bu,r.prior_to),r.prior_from,r.prior_to),priorPnl=prior.filter(x=>['Revenue','Expense'].includes(x.account_type)),priorProfit=sum(priorPnl.filter(x=>x.account_type==='Revenue'),x=>x.movement_krw)-sum(priorPnl.filter(x=>x.account_type==='Expense'),x=>x.movement_krw);const bsAll=rows.filter(x=>['Asset','Liability','Equity'].includes(x.account_type)),internal=bsAll.filter(x=>['INTER_BU_RECEIVABLE','INTER_BU_PAYABLE'].includes(x.system_key)),bs=bu===null?bsAll.filter(x=>!['INTER_BU_RECEIVABLE','INTER_BU_PAYABLE'].includes(x.system_key)):bsAll,assets=sum(bs.filter(x=>x.account_type==='Asset'),x=>x.closing_balance_krw),liabilities=sum(bs.filter(x=>x.account_type==='Liability'),x=>x.closing_balance_krw),equity=sum(bs.filter(x=>x.account_type==='Equity'),x=>x.closing_balance_krw),cumulativeProfit=sum(rows.filter(x=>x.account_type==='Revenue'),x=>x.closing_balance_krw)-sum(rows.filter(x=>x.account_type==='Expense'),x=>x.closing_balance_krw);return {business_unit_id:bu,period:{from:r.from,to:r.to},basis:'Authorized Posted/Reversed journal lines only. No operational estimate, pending proposal or Finance-only record enters official balances.',trial_balance:{rows,debit_krw:sum(rows,x=>x.closing_debit_krw),credit_krw:sum(rows,x=>x.closing_credit_krw),difference_krw:sum(rows,x=>x.closing_debit_krw-x.closing_credit_krw)},income_statement:{rows:period,revenue_krw:sum(period.filter(x=>x.account_type==='Revenue'),x=>x.movement_krw),expenses_krw:sum(period.filter(x=>x.account_type==='Expense'),x=>x.movement_krw),profit_krw:profit,comparison:{from:r.prior_from,to:r.prior_to,profit_krw:priorProfit},korea_machine_trading_profit_krw:round((period.find(x=>x.system_key==='EXCAVATOR_SALES_REVENUE')?.movement_krw||0)-(period.find(x=>x.system_key==='EXCAVATOR_COGS')?.movement_krw||0)),pakistan_resale_profit_share_krw:round(period.find(x=>x.system_key==='PAKISTAN_RESALE_REVENUE')?.movement_krw)},balance_sheet:{rows:bs,assets_krw:assets,liabilities_krw:liabilities,equity_krw:equity,cumulative_profit_krw:cumulativeProfit,difference_krw:round(assets-liabilities-equity-cumulativeProfit),internal_due_net_krw:sum(internal,x=>x.account_type==='Asset'?x.closing_balance_krw:-x.closing_balance_krw),consolidated_internal_elimination:bu===null}}}
 app.get('/api/accounting/v358/statements',auth,allow('finance','dashboard'),(req,res)=>query(req,res,()=>{const bu=scope(req),r=range(req.query||{});return statement(bu,r)}));
 app.get('/api/accounting/v358/ledger/:account_id',auth,allow('finance','dashboard'),(req,res)=>query(req,res,()=>{const bu=scope(req),r=range(req.query||{}),aid=Number(req.params.account_id),a=db.prepare('SELECT id,code,name,account_type FROM accounting_accounts WHERE id=?').get(aid);if(!a)throw bad(404,'Account not found');const all=lines(bu,r.to).filter(x=>x.account_id===aid),opening=sum(all.filter(x=>x.transaction_date<r.from),n),filtered=all.filter(x=>x.transaction_date>=r.from),page=Math.max(1,Math.floor(Number(req.query.page)||1)),size=[25,50,100].includes(Number(req.query.page_size))?Number(req.query.page_size):25;let carry=opening;const enriched=filtered.map(x=>({...x,balance_krw:round(carry+=n(x))}));return {account:a,from:r.from,to:r.to,business_unit_id:bu,opening_balance_krw:opening,period_debit_krw:sum(filtered,x=>Number(x.debit_krw)),period_credit_krw:sum(filtered,x=>Number(x.credit_krw)),closing_balance_krw:round(carry),page,page_size:size,total:filtered.length,rows:enriched.slice((page-1)*size,page*size),basis:'Posted journal drill-down, original currency and source reference retained.'}}));
 const CASH_KEYS=new Set(['BANK_CLEARING','CASH_ON_HAND','PAYMENT_GATEWAY_CLEARING']);
 function cashLines(bu,from,to){const all=lines(bu,to),isCash=l=>l.subtype==='Cash & Bank'||CASH_KEYS.has(l.system_key)||l.system_key?.startsWith('BANK_')||l.system_key?.startsWith('CASH_');return {all,cash:all.filter(isCash),isCash}}
 app.get('/api/accounting/v358/cash-flow',auth,allow('finance','dashboard'),(req,res)=>query(req,res,()=>{const bu=scope(req),r=range(req.query||{}),{all,cash,isCash}=cashLines(bu,r.from,r.to),opening=sum(cash.filter(x=>x.transaction_date<r.from),n),current=cash.filter(x=>x.transaction_date>=r.from),groups=new Map();for(const l of current){const k=l.journal_entry_id,entry=groups.get(k)||[];entry.push(l);groups.set(k,entry)}const byJournal=new Map(all.filter(x=>x.transaction_date>=r.from).map(x=>[x.journal_entry_id,[]]));for(const l of all.filter(x=>x.transaction_date>=r.from))byJournal.get(l.journal_entry_id).push(l);const entries=[],totals={Operating:0,Investing:0,Financing:0,Internal_Transfer:0,Unclassified:0};for(const [id,ls] of groups){const full=byJournal.get(id)||[],other=full.filter(x=>!isCash(x)),cashAmount=sum(ls,n),type=String(ls[0].source_type||'');let activity='Operating';if(other.length===0||/transfer/i.test(type)&&(/Inter.?BU|Inter.?Unit|Bank|Cash|Internal/i.test(type)))activity='Internal_Transfer';else if(other.some(x=>x.system_key&&/FIXED_ASSET|ACCUMULATED_DEPRECIATION|INVESTMENT/.test(x.system_key)))activity='Investing';else if(other.some(x=>x.system_key&&/LOAN|LEASE|EQUITY|CAPITAL/.test(x.system_key)))activity='Financing';if(other.some(x=>x.system_key&&/INTER_BU_(RECEIVABLE|PAYABLE)/.test(x.system_key)))activity='Internal_Transfer';if(other.length>1&&new Set(other.map(x=>x.account_type)).size>1&&!['Internal_Transfer'].includes(activity))activity='Unclassified';totals[activity]=round(totals[activity]+cashAmount);entries.push({journal_entry_id:id,journal_no:ls[0].journal_no,date:ls[0].transaction_date,source_type:type,activity,cash_change_krw:cashAmount,finance_entry_id:ls[0].finance_entry_id})}const change=sum(current,n),classified=round(totals.Operating+totals.Investing+totals.Financing);return {business_unit_id:bu,from:r.from,to:r.to,opening_cash_krw:opening,closing_cash_krw:round(opening+change),cash_change_krw:change,activities_krw:totals,external_classified_cash_flow_krw:classified,classification_bridge_krw:round(change-classified),rows:entries,basis:'Posted cash GL lines only. Internal transfers are shown separately and excluded from external cash flow. Mixed-source entries are Unclassified for review; classification requires accountant confirmation.'}}));
 app.get('/api/accounting/v358/management',auth,allow('finance','dashboard'),(req,res)=>query(req,res,()=>{const bu=scope(req),r=range(req.query||{}),s=statement(bu,r),keys=['EXCAVATOR_INVENTORY','PINK_SALT_RAW_INVENTORY','PINK_SALT_FINISHED_INVENTORY','PINK_SALT_PACKAGING_INVENTORY','SALARY_PAYABLE','TAX_PAYABLE','INTER_BU_RECEIVABLE','INTER_BU_PAYABLE','EXCAVATOR_SALES_REVENUE','EXCAVATOR_COGS','PAKISTAN_RESALE_REVENUE'];return {business_unit_id:bu,from:r.from,to:r.to,posted_account_categories:s.trial_balance.rows.filter(x=>keys.includes(x.system_key)),korea_machine_trading_profit_krw:s.income_statement.korea_machine_trading_profit_krw,pakistan_resale_profit_share_krw:s.income_statement.pakistan_resale_profit_share_krw,basis:'GL-grounded category totals only. Source-specific cost and SKU valuations remain in their reconciliation workspaces; no inferred posted SKU amount.'}}));
}
module.exports={install};
