#!/usr/bin/env python3
"""V30.58 evidence update over the protected 499-row matrix; no invented acceptance."""
from pathlib import Path
import json,collections
root=Path(__file__).resolve().parents[1];x=json.loads((root/'accounting_spec/V30_57_CONSOLIDATED_499_ROW_MATRIX.json').read_text());assert len(x['rows'])==499
for r in x['rows']:
 if r['status']!='DEFERRED_V30_58':continue
 s,n=r['sheet'],r['row'];r['decision_owner']='Engineering / accountant where policy applies';r['evidence_level']='Source inspection only; existing-data staging unavailable';r['test_reference']='';r['policy_status']='Accountant mapping and treatment approval remains where applicable';r['next_action']='Check actual subledger and posted GL on a restored Render database copy';r['blocking_reason']='No existing Render database copy, role-complete browser staging, or accountant signoff'
 if s=='Reports':
  if n in (4,5,6,7):r.update(implementation_status='Technical report fixture and fresh runtime verified',code_reference='server/v358-reports.js; public/v358-accounting.js',test_reference='qa/qa_v358_functional.js; qa/runtime_smoke.js',evidence_level='SQLite fixture and fresh Node 22 runtime; no live-data acceptance')
  elif n in (8,9):r.update(implementation_status='Existing journal paging plus new account statement drill-down',code_reference='server/v290.js; server/v358-reports.js',test_reference='qa/qa_v358_functional.js',evidence_level='SQLite fixture; inherited source QA')
  elif n in (12,34):r.update(implementation_status='Technical reconciliation/close view, fresh runtime verified',code_reference='server/v358-control.js; server/v290.js; server/v319.js',test_reference='qa/runtime_smoke.js; qa/qa_v358_functional.js',evidence_level='Fresh runtime and fixture; actual bank statement staging pending')
  elif n in (22,23,24,25,26,27,28,29,30):r.update(implementation_status='Existing operational source and read-only posted GL reconciliation, partial',code_reference='server/v357-inventory-review.js; server/v358-reports.js; server/v358-management-detail.js',test_reference='qa/qa_v3577_inventory_review.js',evidence_level='Source/GL fixture; policy-dependent SKU cost not activated',blocking_reason='SKU/lot costing, landed-cost eligibility and actual-data reconciliation await approval')
  else:r.update(implementation_status='Existing source view or partial technical report; full report unverified',code_reference=r.get('code_reference','') or 'server/v290.js; server/v357-completion.js; server/v358-management-detail.js',test_reference='qa/qa_v358_management_detail.js',next_action='Verify Pink Salt invoice aging with real allocation history; implement other BU aging and approved SKU/lot costing')
 elif s=='Reconciliation & Close':
  if n in (4,24,25,26):r.update(implementation_status='Technical controls extended and runtime verified',code_reference='server/v290.js; server/v319.js; server/v358-control.js',test_reference='qa/runtime_smoke.js; qa/qa_v358_functional.js',evidence_level='Fresh runtime and fixture')
  elif n in (9,10,12,14,15,16,17,19,21):r.update(implementation_status='Source-to-posted review partial',code_reference='server/v357-inventory-review.js; server/v357-completion.js; server/v357-interbu.js; server/v358-source-reconciliation.js',test_reference='qa/qa_v3577_inventory_review.js; qa/qa_v357_consolidated_functional.js; qa/qa_v358_source_reconciliation.js',evidence_level='Isolated fixture; live-data comparison pending')
  else:r.update(implementation_status='Existing checklist and source controls; detailed reconciliation unverified',code_reference='server/v290.js; server/v358-control.js',test_reference='qa/runtime_smoke.js',evidence_level='Fresh runtime checklist; actual balances not supplied')
 elif s=='Migration & Opening':
  if n in (4,6,20,21,22,25):r.update(implementation_status='Staged Excel/CSV validation and balanced noncash Posting Control proposal',code_reference='server/v319.js; server/v358-migration.js; accounting_spec/migration_templates',test_reference='qa/runtime_smoke.js; qa/qa_v358_functional.js',evidence_level='Fresh runtime and fixture; actual historical records unavailable',blocking_reason='Actual records, COA/subledger matching and accountant/owner review required before posting')
  elif n in range(7,20):r.update(implementation_status='Source-linked optional existing-entity matching; subledger creation not activated',code_reference='server/v319.js; server/v358-migration.js',test_reference='qa/runtime_smoke.js',evidence_level='Fresh staging fixture; no actual subledger import acceptance',blocking_reason='Subledger source matching and historical cutover cannot be verified without real records')
  else:r.update(implementation_status='Existing staged migration controls; review required',code_reference='server/v319.js; server/v358-migration.js',test_reference='qa/runtime_smoke.js')
for r in x['rows']:
 if r['status']=='DEFERRED_V30_58' and r['implementation_status'] in ('Technical report fixture and fresh runtime verified','Technical reconciliation/close view, fresh runtime verified','Technical controls extended and runtime verified','Staged Excel/CSV validation and balanced noncash Posting Control proposal','Existing journal paging plus new account statement drill-down'):
  r['status']='V30_58_TECHNICAL_SOURCE_TESTED_PARTIAL'
x['summary']['latest_evidence']='V30.58.0 consolidated engineering build: inherited regressions, isolated functional fixtures and fresh Node 22 runtime recorded separately. Actual Render data copy, authenticated browser coverage, accountant signoff and production acceptance remain outstanding.'
x['summary']['v358_implementation_status_counts']=dict(collections.Counter(r['implementation_status'] for r in x['rows']))
p=root/'accounting_spec/V30_58_CONSOLIDATED_499_ROW_MATRIX.json';p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n');print(p,len(x['rows']))
