#!/usr/bin/env node
'use strict';
// Opt-in, read-only staging benchmark. Never runs as part of server startup or release QA.
const base=String(process.env.BOM_BENCH_BASE_URL||'').replace(/\/+$/,''),token=String(process.env.BOM_BENCH_TOKEN||'');
if(!base||!token||!/^https:\/\//.test(base)){console.error('Set HTTPS BOM_BENCH_BASE_URL and BOM_BENCH_TOKEN for a staging/test user. No requests sent.');process.exit(2)}
const paths=['/api/health','/api/v349/pink-salt/customers/page?page=1&pageSize=25','/api/v349/pink-salt/orders/page?page=1&pageSize=25','/api/v349/accounting/journal/page?page=1&pageSize=25'];
const count=Math.max(1,Math.min(10,Number(process.env.BOM_BENCH_SAMPLES||6))),modes=[1,3,5,10];
const p=(values,k)=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?Math.round(sorted[Math.min(sorted.length-1,Math.max(0,Math.ceil(k*sorted.length)-1))]):0};
async function call(path){const start=performance.now();const controller=new AbortController(),watch=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(base+path,{headers:{Authorization:'Bearer '+token,Accept:'application/json'},signal:controller.signal}),body=await r.arrayBuffer();return {status:r.status,ms:performance.now()-start,bytes:body.byteLength}}catch(e){return {status:0,ms:performance.now()-start,bytes:0,error:String(e.name||e)}}finally{clearTimeout(watch)}}
(async()=>{console.log('Read-only benchmark; target and token omitted from output. No writes.');for(const route of paths){for(const users of modes){let i=0,rows=[];const worker=async()=>{while(i<count){i++;rows.push(await call(route))}};await Promise.all(Array.from({length:users},worker));const ms=rows.map(x=>x.ms),bad=rows.filter(x=>x.status!==200);console.log(JSON.stringify({route,concurrent:users,samples:rows.length,p50_ms:p(ms,.5),p95_ms:p(ms,.95),max_ms:p(ms,1),avg_bytes:Math.round(rows.reduce((n,x)=>n+x.bytes,0)/rows.length),failures:bad.length,status_codes:[...new Set(rows.map(x=>x.status))]}));if(bad.length){console.error('Benchmark contains non-200 responses: STOP; inspect staging permissions/network before judging performance.');process.exitCode=1;return}}}})().catch(e=>{console.error('Benchmark stopped:',e?.message);process.exitCode=1});
