const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..');
let failed=0;
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const check=(name,ok)=>{console.log((ok?'PASS ':'FAIL ')+name);if(!ok)failed++};
const syntax=f=>{const r=cp.spawnSync(process.execPath,['--check',path.join(root,f)],{encoding:'utf8'});check('syntax '+f,r.status===0);if(r.status!==0)console.error(r.stderr)};

const serverFiles=fs.readdirSync(path.join(root,'server')).filter(f=>f.endsWith('.js')&&f!=='server.v6.js').map(f=>'server/'+f);
const publicFiles=fs.readdirSync(path.join(root,'public')).filter(f=>f.endsWith('.js')).map(f=>'public/'+f);
[...serverFiles,...publicFiles,'qa/qa_current.js','qa/runtime_smoke.js'].forEach(syntax);

const pkg=JSON.parse(read('package.json')),lock=JSON.parse(read('package-lock.json'));
const server=read('server/server.js'),index=read('public/index.html'),base=read('public/client.js'),v284=read('public/v284-client.js'),v285=read('public/v285-client.js'),v300=read('public/v300-client.js'),v305=read('public/v305-client.js'),v307=read('public/v307-client.js'),v308=read('public/v308-client.js'),v309=read('public/v309-client.js'),v310=read('public/v310-client.js'),v313=read('public/v313-client.js'),v314=read('public/v314-client.js'),v315=read('public/v315-client.js'),v317=read('public/v317-client.js'),v318=read('public/v318-client.js'),b284=read('server/v284.js'),b290=read('server/v290.js'),b300=read('server/v300.js'),b305=read('server/v305.js'),b307=read('server/v307.js'),b310=read('server/v310.js'),b313=read('server/v313.js'),b315=read('server/v315.js'),b316=read('server/v316.js'),b318=read('server/v318.js'),b319=read('server/v319.js'),b320=read('server/v320.js'),v319=read('public/v319-client.js'),v320=read('public/v320-client.js'),ko=read('public/i18n-ko.js'),reqs=read('REQUIREMENTS_MASTER.md');

check('V30.20 release identity',pkg.version==='30.20.0'&&lock.version==='30.20.0'&&server.includes("version:'30.20.0'")&&server.includes('Blue Ocean Market V30.20.0 running on port'));
check('browser cache identity',index.includes('/client.js?v=30.20.0')&&index.includes('/v310-client.js?v=30.20.0')&&index.includes('/v314-client.js?v=30.20.0')&&index.includes('/v315-client.js?v=30.20.0')&&index.includes('/v317-client.js?v=30.20.0')&&index.includes('/v318-client.js?v=30.20.0'));
const scriptRefs=[...index.matchAll(/<script src="\/([^"?]+\.js)\?v=30\.20\.0"><\/script>/g)].map(m=>m[1]);
check('all browser scripts exist',scriptRefs.length>0&&scriptRefs.every(f=>fs.existsSync(path.join(root,'public',f))));
check('runtime overlay order retained',index.indexOf('/v285-client.js?v=30.20.0')<index.indexOf('/v300-client.js?v=30.20.0')&&index.indexOf('/v300-client.js?v=30.20.0')<index.indexOf('/v310-client.js?v=30.20.0')&&index.indexOf('/v313-client.js?v=30.20.0')<index.indexOf('/v314-client.js?v=30.20.0'));

check('context-aware hint engine installed',v285.includes('PINK_SALT_HINTS')&&v285.includes('RESTAURANT_HINTS')&&v285.includes('NEUTRAL_HINTS')&&v285.includes('selectedBusinessName'));
check('explicit module placeholders preserved',v285.includes('v285ExplicitPlaceholder')&&v285.includes('Module-authored placeholders carry more precise workflow context'));
check('shared placeholders adapt by business unit',v285.includes("related_entity_type:'import, supplier, product, order...'")&&v285.includes("related_entity_type:'order, menu item, table, supplier...'")&&v285.includes("financeSearch:'Search import, supplier, order, customer, reference…'"));
check('Pink Salt source placeholders are field-specific',v300.includes('placeholder="e.g. PK-SALT-INV-2026-015"')&&v300.includes('placeholder="e.g. 500g stand-up pouch"')&&v300.includes('placeholder="Packaging supplier"')&&v300.includes('Mixed Pink Salt Gift Box 500g Pouches'));
check('Pink Salt storage context uses warehouse not yard',v300.includes('placeholder="Warehouse / Rack / Zone"')&&!v300.includes('placeholder="Yard / Rack / Zone"'));
check('Pink Salt source has no Excavator example leakage',!v300.includes('Seoul Heavy Equipment')&&!v300.includes('Customer / supplier / employee name')&&!v300.includes('Volvo EC220'));
check('V30.10 safety placeholder fixer retained',v310.includes('fixPinkPlaceholders')&&v310.includes('e.g. 500g stand-up pouch')&&v310.includes('e.g. PK-SALT-INV-2026-015'));
check('new context strings have Korean mappings',ko.includes("'Warehouse / Rack / Zone':'창고 / 랙 / 구역'")&&ko.includes("'e.g. Pink Salt operations review':'예: 핑크 소금 운영 검토'")&&ko.includes("'Search order, supplier, menu item, reference…':'주문, 공급업체, 메뉴 항목, 참조 검색…'"));
check('master requirement defines mandatory context integrity',reqs.includes('Mandatory business-unit context integrity')&&reqs.includes('Context correctness is a release-blocking requirement')&&reqs.includes('Business Context Audit'));

check('V30.13 backend installed',server.includes("require('./v313').install")&&b313.includes("VERSION='30.13.0'")&&b313.includes('/api/pink-salt/customers-v313')&&b313.includes('/api/pink-salt/orders-v313'));
check('V30.13 browser overlay retained before V30.14',index.includes('/v313-client.js?v=30.20.0')&&index.indexOf('/v310-client.js?v=30.20.0')<index.indexOf('/v313-client.js?v=30.20.0')&&index.indexOf('/v313-client.js?v=30.20.0')<index.indexOf('/v314-client.js?v=30.20.0'));
check('customer account and aging implemented',b313.includes('account-v313')&&b313.includes('unallocated_credit_krw')&&b313.includes('d31_60')&&v313.includes('psCustomerAccount313'));
check('grouped receipts and multi-order allocation implemented',b313.includes('pink_salt_customer_receipt_allocations')&&b313.includes('gross_settlement_krw')&&v313.includes('data-alloc-order')&&v313.includes('psAllocateReceipt313'));
check('marketplace settlement fee accounting implemented',b313.includes('Pink Salt Marketplace Settlement Fee')&&read('server/v290.js').includes("st==='Pink Salt Marketplace Settlement Fee'")&&server.includes("st==='Pink Salt Marketplace Settlement Fee'"));
check('flexible pricing hierarchy implemented',b313.includes("pricing_source:'Customer Specific'")&&b313.includes('Price Tier ·')&&b313.includes("pricing_source:'Product Default'")&&b313.includes("'Manual Override'"));
check('historical pricing snapshot retained',b313.includes('pricing_snapshot_json')&&b313.includes('list_price_krw')&&b313.includes('price_override_reason'));
check('below-cost protection implemented',b313.includes('below current unit cost')&&b313.includes("req.user.role!=='CEO / Owner'"));
check('customer statements and exports implemented',b313.includes('statement-v313.csv')&&b313.includes('statement-v313.pdf')&&v313.includes('psDownloadStatement313'));
check('Pink Salt list controls implemented',v313.includes('enhanceGenericList')&&v313.includes('enhancePackaging')&&v313.includes("['psImports','psRawStock','psProduction','psFinished','psWaste']"));
check('new account and pricing UI is bilingual-ready',v313.includes("'Customer Accounts':'고객 계정'")&&v313.includes("'Pricing Tier':'가격 등급'")&&v313.includes("'Unallocated Credit':'미배정 크레딧'"));
check('master requirements include V30.13 receivables and pricing',reqs.includes('V30.13 mandatory Pink Salt customer accounts')&&reqs.includes('active customer/store-specific price → assigned price tier → product default price → authorized manual override')&&reqs.includes('Pink Salt list search, sorting and filtering'));

check('V30.14 Review & Confirm retained before V30.15 supplier overlay',index.includes('/v314-client.js?v=30.20.0')&&index.indexOf('/v313-client.js?v=30.20.0')<index.indexOf('/v314-client.js?v=30.20.0')&&index.indexOf('/v314-client.js?v=30.20.0')<index.indexOf('/v315-client.js?v=30.20.0')&&v314.includes("const VERSION='30.14.0'"));
check('system-wide form Review & Confirm capture implemented',v314.includes("document.addEventListener('submit'")&&v314.includes('formReview(form,submitter)')&&v314.includes('collectForm(form)')&&v314.includes('Review & Confirm'));
check('edit review supports old to new presentation',v314.includes('bom314-review-change')&&v314.includes('initialValue(el)')&&v314.includes('<span class="arrow">→</span>'));
check('explicit confirmation workflows grant review allowance',v314.includes("wrapDecision('confirmAction'")&&v314.includes("wrapDecision('reasonAction'")&&v314.includes('grantReview()'));
check('mutating API calls require review and show processing state',v314.includes('window.api=async function')&&v314.includes('genericApiReview(url,opt)')&&v314.includes('showProcessing(url,buttonText)')&&v314.includes('markButtonBusy(actionButton)')&&v314.includes('hideProcessing()'));
check('non-business auth/notification/download actions bypass V30.14 blocker',v314.includes('if(noReview(url))return oldApi(url,opt)'));
check('contextual processing messages implemented',v314.includes('Receiving import…')&&v314.includes('Completing production…')&&v314.includes('Recording payment…')&&v314.includes('Allocating balance…'));
check('persistent mutation idempotency protection retained',v284.includes('X-Idempotency-Key')&&v284.includes('X-Request-Fingerprint')&&b284.includes('request_idempotency')&&b284.includes("app.use('/api',mutationIdempotency)")&&v314.includes("opt.headers['X-Idempotency-Key']=randomKey()"));
check('long-running mutations receive extended client timeout',base.includes("timeoutMs=(method==='GET'||method==='HEAD')?30000:120000")&&base.includes('setTimeout(()=>controller.abort(),timeoutMs)'));
check('Review and processing UI has Korean localization',ko.includes("'Review & Confirm':'검토 및 확인'")&&ko.includes("'Receiving import…':'수입 입고 처리 중…'")&&ko.includes("'Processing…':'처리 중…'")&&ko.includes("'Confirm & Save':'확인 후 저장'"));
check('semantic Pink Salt account position replaces raw negative presentation',v313.includes('accountPosition313')&&v313.includes("?'Due':")&&v313.includes("?'Credit':'Settled'")&&v313.includes('Account Position')&&v313.includes('Math.abs(n)'));
check('available customer credit can be selected on new completed order',v313.includes('Available Customer Credit')&&v313.includes('name="apply_available_credit"')&&v313.includes('ps313RefreshCreditBox')&&b313.includes('applyExistingCustomerCredit')&&b313.includes('apply_available_credit')&&b313.includes('existing_credit_applied_krw'));
check('customer credit application preserves allocation accounting',b313.includes("sourceType:'Pink Salt Customer Receipt Allocation'")&&b313.includes("accounting.accountId('CUSTOMER_ADVANCES')")&&b313.includes("accounting.accountId('ACCOUNTS_RECEIVABLE')"));
check('V30.14 account/review strings are bilingual-ready',ko.includes("'Available Customer Credit':'사용 가능한 고객 크레딧'")&&ko.includes("'Account Position':'계정 상태'")&&ko.includes("'Credit':'크레딧'"));
check('master requirements include V30.14 review processing and account position',reqs.includes('V30.14 mandatory system-wide Review & Confirm')&&reqs.includes('server-side transaction and idempotency/request-fingerprint protection')&&reqs.includes('Do not present a customer/store credit position as a confusing raw negative account balance'));


check('V30.15 supplier backend installed',server.includes("require('./v315').install")&&b315.includes("VERSION='30.15.0'")&&b315.includes('/api/pink-salt/suppliers-v315')&&b315.includes('/account-v315'));
check('dedicated Pink Salt Suppliers sidebar is installed before Imports',v300.includes("['psSuppliers','Suppliers','🤝'],['psImports','Imports / Purchases'")&&v300.includes("if(view==='psSuppliers')return window.psSuppliersView"));
check('Imports header no longer owns Supplier Management',!v310.includes('onclick="psSuppliers()"')&&!v310.includes("t('Supplier Management')"));
check('unified supplier categories support multi-category profiles',b315.includes('supplier_categories_json')&&b315.includes('Import / Raw Salt Supplier')&&b315.includes('Packaging Material Supplier')&&v315.includes('supplierTypes')&&v315.includes('name="supplier_category"'));
check('legacy suppliers are categorized from operational history',b315.includes('Classify existing suppliers from their actual Pink Salt history')&&b315.includes("set.add('Import / Raw Salt Supplier')")&&b315.includes("set.add('Packaging Material Supplier')"));
check('category-specific supplier selection is enforced client and server',v300.includes("Import / Raw Salt Supplier')})")||v300.includes("includes('Import / Raw Salt Supplier')")&&b300.includes("supplierHasCategoryV315(supplier,'Import / Raw Salt Supplier')")&&b300.includes("supplierHasCategoryV315(supplier,'Packaging Material Supplier')")&&v315.includes("includes('Packaging Material Supplier')"));
check('supplier account exposes payables credit aging and obligations',b315.includes('total_outstanding_krw')&&b315.includes('available_credit_krw')&&b315.includes('function aging(')&&v315.includes('Total Payables')&&v315.includes('Available Supplier Credit')&&v315.includes('agingCards'));
check('supplier profile has context-specific operational/document/history sections',v315.includes('supplierProfileTabs315')&&v315.includes("cats.includes('Import / Raw Salt Supplier')")&&v315.includes("cats.includes('Packaging Material Supplier')")&&v315.includes('Documents / Evidence')&&v315.includes('Audit / History')&&b315.includes('documents,history'));
check('central supplier payments reuse audited advance payment pool',v315.includes('/api/pink-salt/suppliers/${id}/advances')&&b305.includes("app.post('/api/pink-salt/suppliers/:id/advances'")&&b305.includes('Advance payment receipt / evidence is required.'));
check('supplier payment balance is shared across import and packaging allocations',b305.includes('packagingAllocated')&&b305.includes('pink_salt_supplier_packaging_allocations x WHERE x.advance_id=a.id')&&b307.includes('packagingAllocated')&&b307.includes('imports or packaging receipts'));
check('packaging receipt creates payable not cash payment',b300.includes("paymentMethod:'Supplier Payable'")&&server.includes("st==='Pink Salt Packaging Purchase')return ['Packaging Purchase / Payable',0]")&&b290.includes("st==='Pink Salt Packaging Purchase'")&&b290.includes("accountId('ACCOUNTS_PAYABLE')"));
check('packaging receipt requires supplier invoice and evidence',b300.includes('supplier invoice/reference')&&b300.includes('Packaging invoice / delivery evidence is required.')&&v315.includes('Supplier Invoice / Reference')&&v315.includes('Invoice / Delivery Evidence'));
check('packaging supplier credit can auto-apply on receipt',v315.includes('name="apply_available_credit"')&&b300.includes('apply_available_credit')&&b300.includes('allocatePackagingCreditV315')&&b300.includes('allocated_credit_krw'));
check('manual and automatic packaging allocation endpoints implemented',b315.includes('/packaging-allocations-v315')&&b315.includes('/auto-allocate-v315')&&v315.includes('psSupplierAllocate315')&&v315.includes('psSupplierAutoAllocate315'));
check('supplier packaging allocation posts non-cash AP settlement',b315.includes("accounting.accountId('ACCOUNTS_PAYABLE')")&&b315.includes("accounting.accountId('PINK_SALT_SUPPLIER_ADVANCES')")&&b315.includes('Pink Salt Supplier Packaging Allocation'));
check('simple accounting balances include packaging payables and allocations',b305.includes("'PACK-'||m.id import_no")&&b305.includes('pink_salt_supplier_packaging_allocations x WHERE x.supplier_id=s.id'));
check('supplier statements support JSON CSV and PDF',b315.includes('/statement-v315')&&b315.includes('/statement-v315.csv')&&b315.includes('/statement-v315.pdf')&&v315.includes('psSupplierStatementDownload315'));
check('V30.15 supplier UI is bilingual-ready',v315.includes("'Supplier Accounts':'공급업체 계정'")&&v315.includes("'Packaging Material Supplier':'포장 자재 공급업체'")&&v315.includes("'Available Supplier Credit':'사용 가능한 공급업체 크레딧'"));
check('V30.15 requirements documented',reqs.includes('V30.15 mandatory Pink Salt unified supplier architecture')&&reqs.includes('one unified supplier master')&&reqs.includes('Stock receipt and supplier payment are separate but linked business events'));


check('V30.16 backend installed',server.includes("require('./v316').install")&&b316.includes('access_role_templates')&&b316.includes('user_business_units')&&b316.includes('user_access_overrides')&&b316.includes('user_access_limits'));
check('live auth resolves current user instead of stale token role',server.includes('const decoded=jwt.verify')&&server.includes('SELECT id,name,email,role,business_unit_id,active')&&server.includes('Your account is inactive or no longer available'));
check('effective permission middleware replaces role-only allow path',server.includes('accessV316.canAnyModule')&&b316.includes('effectiveAccess')&&b316.includes('canModule'));
check('multi-business-unit assignments and switching implemented',b316.includes('user_business_units')&&b316.includes('replaceAssignments')&&base.includes('unitOptions.length>1')&&base.includes('await hydrateAccess()'));
check('CEO global and delegated user access administration implemented',b316.includes('canManageTarget')&&b316.includes('delegate.bu_users')&&b316.includes('delegate.finance_users')&&b316.includes('You cannot change your own role or access.'));
check('Finance Head and Finance User templates implemented',b316.includes("role:'Finance Head'")&&b316.includes("role:'Finance User'")&&base.includes("'Finance Head','Finance User'"));
check('granular module actions supported',b316.includes("const ACTIONS=['view','create','edit','delete','void','approve','export','print','verify','correct','allocate']")&&v317.includes('access-matrix'));
check('sensitive and delegated rights supported',b316.includes('sensitive.user_management')&&b316.includes('sensitive.accounting_adjustments')&&b316.includes('delegate.access')&&v317.includes('Sensitive Permissions'));
check('limits and threshold controls supported',b316.includes('finance_payment_max')&&b316.includes('finance_approval_max')&&b316.includes('max_discount_pct')&&v317.includes('Limits / Thresholds'));
check('role template apply and access copy implemented',b316.includes('/apply-template')&&b316.includes('/copy')&&v317.includes('applyAccessTemplate')&&v317.includes('copyAccessDialog'));
check('access change history implemented',b316.includes('access_change_history')&&b316.includes('history(target')&&v317.includes('Access History'));
check('Pink Salt navigation honors effective permissions',v317.includes("psSuppliers:'purchases'")&&v317.includes("if(module&&!allowed(key))btn.remove()"));
check('V30.17 bilingual access UI included',v317.includes("'Users & Access':'사용자 및 접근 권한'")&&v317.includes("'Effective Access':'유효 접근 권한'")&&v317.includes("'Finance Head':'재무 책임자'"));
check('V30.16 requirements documented',reqs.includes('V30.16 mandatory system-wide Users & Access requirements')&&reqs.includes('effective permissions are authoritative')&&reqs.includes('Finance Head delegated administration'));
check('V30.19 overlay loads last',index.indexOf('/v315-client.js?v=30.20.0')<index.indexOf('/v317-client.js?v=30.20.0')&&index.indexOf('/v317-client.js?v=30.20.0')<index.indexOf('/v318-client.js?v=30.20.0')&&index.indexOf('/v318-client.js?v=30.20.0')<index.indexOf('/v319-client.js?v=30.20.0')&&index.trim().endsWith('</body></html>'));


check('V30.17 Access button handler is explicitly exported',v317.includes('window.userAccessOpen=async function')&&v317.includes('onclick="userAccessOpen(${x.id})"'));
const accessHandlers=['userAccessOpen','syncAccessPrimaryOptions','applyAccessTemplate','copyAccessDialog','copyAccessNow','saveAccessAssignments','saveAccessPermissions','saveAccessSpecial','saveAccessLimits','userForm','saveUser','userEdit','saveUserEdit'];
check('all V30.17 inline access handlers are window exported',accessHandlers.every(n=>v317.includes(`window.${n}=`)));
check('self access editor is read-only',v317.includes('function selectedUserCanManage(data){return !!data?.can_manage}')&&b316.includes('You cannot change your own role or access.'));
check('multi-BU access scope selector implemented',v317.includes("'Access Scope':'접근 범위'")&&v317.includes('accessScopeSelector')&&v317.includes('/effective${bu?'));
check('primary BU must be assigned and valid',b316.includes('Primary business unit must also be assigned.')&&b316.includes('One or more selected business units are invalid or archived.')&&server.includes('Primary business unit must also be assigned.'));
check('delegated access save requires delegate.access',b316.includes("function requireAccessDelegation")&&b316.includes("'delegate.access'"));
check('Finance-only delegated scope is bounded',b316.includes('financeOnlyAdmin')&&b316.includes('Finance delegated administration is restricted to Finance-related permissions.')&&b316.includes('Finance delegated administration may change only Finance amount limits.'));
check('role-template ceiling includes limits',b316.includes('for(const [k,v] of Object.entries(desired.limits||{}))'));
check('copy access is CEO-only',b316.includes("Only CEO / Owner can copy another user’s complete access profile."));
check('access history records before and after state',b316.includes("'permissions_update',{before,after")&&b316.includes("'limits_update',{before,after")&&b316.includes("'template_apply',{before,after")&&b316.includes("'access_copy',{before,after"));
check('module aliases resolve legacy route permissions',b316.includes("MODULE_ALIASES={staff:'users',crm:'sales',customers:'sales',kpi:'performance',pos:'sales'}")&&b316.includes('normalizeModule'));
check('Payroll is in granular module catalog',b316.includes("'audit','payroll']")&&v317.includes("payroll:'Employees & Payroll'"));
check('sensitive payroll is enforced server-side',server.includes("module==='payroll'&&!accessV316.can(live.id,'sensitive.payroll'")&&b290.includes("hasAccess?.(req.user.id,'sensitive.payroll'"));
check('sensitive accounting adjustment is enforced server-side',b290.includes("hasAccess?.(req.user.id,'sensitive.accounting_adjustments'"));
check('sensitive approval-rule configuration is enforced',server.includes("startsWith('/approval-rules')&&action!=='view'")&&server.includes('canManageApprovalRules(req)'));
check('sensitive audit-log access is enforced',server.includes("module==='audit'&&!accessV316.can(live.id,'sensitive.audit_logs'"));
check('missing centralized route mappings are covered',server.includes("p.startsWith('/payroll')")&&server.includes("p.startsWith('/performance')||p.startsWith('/kpis')")&&server.includes("p.startsWith('/sales')||p.startsWith('/customers')||p.startsWith('/crm')")&&server.includes("p.startsWith('/statements')||p.startsWith('/pnl')"));
check('legacy role-based allowed is superseded late',v317.includes('allowed=function(key)')&&v317.includes("return canDo(accessKeyForView(key),'view')"));
check('Users & Access mutations use Review & Confirm',v317.includes("title:'Confirm Access Changes'")&&v317.includes("title:'Confirm User Creation'")&&v317.includes("title:'Apply Role Template'"));
check('Render Dockerfile installs native build prerequisites',read('Dockerfile').includes('python3 make g++')&&read('Dockerfile').includes('npm ci --omit=dev'));
check('V30.17 requirements documented',reqs.includes('V30.17 mandatory Users & Access hardening requirements')&&reqs.includes('Every People & Access button/action must be functional and regression-tested.'));


// V30.18 — Finance review -> Posting Control -> official ledger.
check('V30.18 backend and UI overlays installed',server.includes("require('./v318').install")&&server.includes('upload,accounting:accountingV29,access:accessV316')&&b318.includes("VERSION='30.18.0'")&&v318.includes("const VERSION='30.18.0'"));
check('Finance and Accounting remain separate modules',base.includes("['finance','Finance','💰']")&&read('public/v290-client.js').includes("['accounting','Accounting','📚']")&&b316.includes("'finance','accounting'")&&v318.includes('Finance controls daily transactions; Accounting contains only finalized postings'));
check('operational journal proposals default to Pending Review',b290.includes("postingStatus='Pending Review'")&&b290.includes("const status=postingStatus==='Posted'?'Posted':'Pending Review'")&&b290.includes("accounting_status='Pending Review'"));
check('official accounting reports exclude unposted proposals',b290.includes("j.status IN ('Posted','Reversed')")&&b290.includes("LEFT JOIN accounting_journal_entries j ON j.id=l.journal_entry_id AND j.status IN ('Posted','Reversed')"));
check('V30.18 simple accounting summary uses ledger-effective reversal population',b305.includes("j.status IN ('Posted','Reversed')"));
check('Posting Control queue, summary and detail APIs exist',b318.includes("app.get('/api/accounting/posting-control'")&&b318.includes("app.get('/api/accounting/posting-control/summary'")&&b318.includes("app.get('/api/accounting/posting-control/:id'"));
check('Posting Control view is permission scoped',b318.includes('function canViewPosting(req,j)')&&b318.includes("'accounting','view'")&&b318.includes("'finance','verify'")&&b318.includes("'finance','correct'")&&b318.includes('.filter(j=>canViewPosting(req,j))'));
check('Final Accounting post requires granular approval in every affected BU',b318.includes('function canPost(req,j)')&&b318.includes("permissionOnAllUnits(req,'accounting',['approve'],j)")&&b318.includes('return units.every(bu=>')&&b318.includes('Final Accounting posting permission is required for every business unit affected'));
check('Final post validates balance, period, Finance readiness and review note',b318.includes('if(!j.balanced)')&&b318.includes('periodClosedUnits(j)')&&b318.includes('financeReadiness(j)')&&b318.includes("A final-post review note is required."));
check('linked Finance records require verification and resolved corrections',b318.includes("['Verified','Verified / Correct'].includes(verification)")&&b318.includes('A Finance correction request is still open.')&&b318.includes('pendingReversalForFinance'));
check('Posting Control exposes source evidence safely',b318.includes('function safeEvidencePath(value)')&&b318.includes("v.startsWith('/uploads/')")&&b318.includes("v.includes('..')")&&b318.includes('function postingEvidence(j,financeInfo=null)')&&v318.includes('(d.evidence||[])'));
check('manual journal creation requires sensitive accounting permission and evidence',b290.includes('function requireAccountingWrite')&&b290.includes("'sensitive.accounting_adjustments'")&&b290.includes("upload.single('evidence')")&&b290.includes('Evidence / supporting document is required for a manual journal proposal.'));
check('manual journal lines require active manual-postable balanced accounts',b290.includes('a.allow_manual')&&b290.includes('either a debit or a credit greater than zero')&&b290.includes('Manual journal must have equal debit and credit totals.'));
check('manual journal UI submits multipart evidence',v318.includes('window.manualJournalV29=async')&&v318.includes('new FormData(f)')&&v318.includes("name=\"evidence\"")&&v318.includes("fd.set('lines_json'"));
check('manual proposal correction and cancellation workflows exist',b318.includes("app.put('/api/accounting/posting-control/:id/manual'")&&b318.includes("app.post('/api/accounting/posting-control/:id/cancel-proposal'")&&v318.includes('saveManualJournalEditV318')&&v318.includes('postingCancelV318'));
check('controlled reversal does not silently change official GL',b290.includes("'Accounting Reversal',entry.id")&&b290.includes("'Pending Review'")&&b290.includes('keep the original Posted until')&&b318.includes("SET status='Reversed',reversed_by_id=?"));
check('unposted operational proposals cancel cleanly when source is reversed',b290.includes("['Pending Review','Correction Required'].includes(entry.status)")&&b290.includes("status='Cancelled'")&&b310.includes("!['Reversed','Cancelled'].includes(j.status)"));
check('reversal final-post clears stale bank reconciliation',b318.includes("SET status='Unreconciled',matched_journal_entry_id=NULL")||b318.includes("matched_journal_entry_id=NULL"));
check('corrected Finance source waits for prior official reversal',b318.includes('function pendingReversalForFinance')&&b318.includes('Previous official posting must be reversed first')&&b318.includes('!reversal'));
check('period close blocks pending Posting Control proposals',b290.includes("status IN ('Pending Review','Correction Required')")&&b290.includes('Posting Control proposals waiting'));
check('V2 period close readiness enforces finance bank trial-balance and clearing controls',b290.includes('function periodCloseReadiness(businessUnitId,key)')&&b290.includes('Unverified Finance transactions')&&b290.includes('Unreconciled bank statement lines')&&b290.includes('Unbalanced official journals')&&b290.includes('Suspense / temporary clearing balances')&&b290.includes('Inter-BU Clearing mismatch'));
check('V2 reconciliation checklist is persisted with user date and evidence',b290.includes('accounting_period_reconciliations')&&b290.includes("app.post('/api/accounting/periods/reconciliation-status'")&&b290.includes('completed_by')&&b290.includes('completed_at')&&b290.includes('evidence_file'));
check('period close requires reconciliation signoff and a review note',b290.includes('Required reconciliation checklist items still Open')&&b290.includes('Period-close review note is required.')&&b290.includes('Period close is blocked until reconciliation and accounting controls are complete.'));
check('period reopen requires reason and resets reconciliation signoff',b290.includes('A reason is required to reopen a closed accounting period.')&&b290.includes("UPDATE accounting_period_reconciliations SET status='Open'"));
check('Accounting Periods UI exposes close readiness and reconciliation review',read('public/v290-client.js').includes('Period Close Readiness')&&read('public/v290-client.js').includes('loadCloseReadinessV29')&&read('public/v290-client.js').includes('periodReconReviewV29')&&read('public/v290-client.js').includes('savePeriodReconV29'));
check('period close and reconciliation status use granular accounting actions',server.includes('accounting\\/periods\\/(close|reopen)')&&server.includes('accounting\\/periods\\/reconciliation-status'));
check('duplicate active proposal guards cover core operational paths',b300.includes("status IN ('Pending Review','Correction Required','Posted')")&&b310.includes("status IN ('Pending Review','Correction Required','Posted')")&&b313.includes("status IN ('Pending Review','Correction Required','Posted')"));
check('Posting Control UI shows explicit finance-to-ledger flow',v318.includes("t('Operational Transaction')")&&v318.includes("t('Finance Review')")&&v318.includes("t('Posting Control')")&&v318.includes("t('Official Ledger')"));
check('Posting Control final post uses required Review & Confirm reason',v318.includes('window.postingFinalV318')&&v318.includes("title:'Review & Final Post'")&&v318.includes('required:true')&&v318.includes("body:JSON.stringify({note})"));
check('Posting Control correction uses controlled reason workflow',v318.includes('window.postingCorrectionV318')&&v318.includes("title:'Request Accounting Correction'")&&v318.includes('required:true'));
check('Posting Control visibility uses effective permissions',v318.includes('function canViewPosting318')&&v318.includes("hasPermission('module.accounting.view')")&&v318.includes("hasPermission('module.finance.verify')"));
check('action counters include posting viewers beyond approvers',server.includes('const accountingViewer=')&&server.includes('const postingViewer=')&&server.includes('counts.accounting=postingReview'));
check('V30.18 bilingual Posting Control strings included',v318.includes("'Posting Control':'전기 통제'")||v318.includes("'Posting Control':")&&v318.includes('검토')&&v318.includes('원장'));
check('V30.18 requirements documented',reqs.includes('V30.18 mandatory Finance & Accounting Posting Control requirements')&&reqs.includes('Operational Transaction')&&reqs.includes('Posting Control')&&reqs.includes('Official Ledger'));

// V30.19 — System Settings / Administration + QA hardening.
check('V30.19 backend and browser overlays installed',server.includes("require('./v319').install")&&b319.includes("VERSION='30.19.0'")&&index.includes('/v319-client.js?v=30.20.0'));
check('System Settings central configuration service implemented',b319.includes('system_settings')&&b319.includes('effectiveFor')&&b319.includes('getSetting')&&b319.includes("scope_type")&&b319.includes("'company','business_unit','user'"));
check('System Settings sections cover consolidated requirements',b319.includes("overview:{label:'System Overview'")&&b319.includes('company_profile_branding')&&b319.includes('business_units')&&b319.includes('email_smtp')&&b319.includes('files_attachments')&&b319.includes('migration')&&b319.includes('finance_accounting')&&b319.includes('bank_accounts')&&b319.includes('security_access')&&b319.includes('approvals')&&b319.includes('notifications')&&b319.includes('numbering')&&b319.includes('localization')&&b319.includes('backup_storage_maintenance')&&b319.includes("audit:{label:'System Audit'")&&b319.includes('ai_assistant'));
check('System Administrator sensitive permissions implemented',b316.includes('System Administrator')&&b316.includes('sensitive.system_admin')&&b316.includes('sensitive.smtp')&&b316.includes('sensitive.storage')&&b316.includes('sensitive.data_migration')&&b316.includes('sensitive.bank_accounts')&&b316.includes('sensitive.ai_settings')&&b316.includes('sensitive.accounting_configuration'));
check('SMTP credentials encrypted and never returned plaintext',b319.includes('aes-256-gcm')&&b319.includes('system_secrets')&&b319.includes('password_set')&&b319.includes('smtp_password')&&b319.includes('Secrets never come back through settings APIs'));
check('secure SMTP-backed password reset implemented',b319.includes("app.post('/api/auth/forgot'")&&b319.includes("app.post('/api/auth/reset'")&&b319.includes('password_resets')&&b319.includes('If the account exists, password-reset instructions will be sent shortly.')&&b319.includes('expires_at')&&b319.includes('resetRate'));
check('Company Bank Accounts are centrally configured and history-preserving',b319.includes('/api/system-settings-v319/bank-accounts')&&b319.includes("status='Closed'")&&b319.includes('system_bank_account_history')&&b319.includes('GL mapping can change only with CEO / Owner explicit high-risk confirmation'));
check('operational payment accounts are BU scoped and safe',b319.includes('account_number_masked')&&b319.includes('ledger_mapped')&&v319.includes('v319PaymentAccounts')&&v319.includes('Company Bank / Payment Account'));
check('Posting/verification blocks invalid bank GL mapping',server.includes('Posting Control blocked this ${actual} account because it has no valid active')&&server.includes('configuredPaymentAccount'));
check('shared attachment policy consumes System Settings',server.includes('attachmentPolicyMiddleware')&&server.includes("effectiveFor?.('files_attachments'")&&server.includes('allowed_file_types')&&server.includes('max_attachments_per_record'));
check('V30.20 direct attachment upload replaces preview compression workflow',!v319.includes('reviewFileV319')&&!v319.includes('optimizeImageV319')&&b319.includes('optimize_images:false')&&b319.includes('preview_before_store:false')&&v320.includes('Max ${Number(p.max_file_size_mb||20)} MB per file')&&v320.includes('max_attachments_per_upload')&&v320.includes('allowed_file_types')&&!v320.includes('Use Optimized')&&!v320.includes('Confirm Readability'));
check('data migration uses staged validate preview import workflow',b319.includes('system_migration_jobs')&&b319.includes('system_migration_rows')&&b319.includes('/validate')&&b319.includes('/import')&&v319.includes('v319ValidateMigration')&&v319.includes('v319ImportMigration'));
check('AI Assistant obeys existing authorization chain',b319.includes('User → Business Unit → Module → Record → Sensitive Permission')&&b319.includes('review_confirm_for_actions')&&v319.includes('AI Assistant'));
check('supplier phone email and duplicate validation implemented',server.includes('validateContactFormat')&&server.includes('normalizePhone')&&server.includes('supplierContactDuplicate')&&server.includes('Open the existing supplier instead of saving a duplicate.'));
check('supplier modal lifecycle and machine notes regressions addressed',v319.includes('v319SuppressSupplierModal')||v319.includes('supplier')&&server.includes('req.body.notes??x.notes'));
check('chassis duplication is checked across supplier and machine history',server.includes('duplicateChassis')&&server.includes('Serial / Chassis')&&server.includes('already exists'));
check('routine documents bypass business Review Confirm and use preview/archive',v314.includes('documents(?:\\?|$)')&&v319.includes('previewAttachmentV319')&&v319.includes('Delete / Archive Document')&&b319.includes('documents-history-v319'));
check('payment method reference account and FX are standardized in QA paths',server.includes('Payment Method / Mode of Payment is mandatory for every payment-related entry')&&server.includes('Payment Reference is required for non-cash payments')&&v319.includes('FX Rate to KRW')&&v319.includes('payment_account_id'));
check('machine costs use controlled edit reversal and token visibility',v319.includes('Delete / Reverse Machine Cost')&&server.includes('verified or posted')&&base.includes('Purchase Payment')&&server.includes('Token/Partial Paid'));
check('finance verification actions are state-driven',v319.includes("['Pending Verification','Resubmitted'].includes(status)")&&v319.includes("correction&&d.can_correct")&&v319.includes("verified||voided?'Finance Record':'Finance Verification'"));
check('verified and voided finance records use View',v319.includes("?'View':'Open Verification'")&&v319.includes('View Full History'));
check('finance correction preserves previous evidence',v319.includes('Current / Previous Evidence')&&v319.includes('Remove from active')&&v319.includes('Old files are never physically erased'));
check('successful finance void closes modal',v319.includes("closeModal(true);toast(r.approval_required"));
check('language selection persists using server preference',v319.includes('/api/me/language')&&v319.includes('localStorage')&&v319.includes('preferred_language'));
check('Accounting Simple View responsive hardening included',v319.includes('v319-accounting-fix')&&v319.includes('MutationObserver'));
check('Business Unit administration is non-destructive',b319.includes('/business-units/:id/archive')&&b319.includes("status='Archived'")&&b319.includes('archive-from-system-settings')&&b319.includes('history_preserved:true'));
check('backup diagnostics audit and maintenance tools implemented',b319.includes('/backup')&&b319.includes('attachment-diagnostics')&&b319.includes('/system-audit'));
check('V30.19 requirements documented',reqs.includes('V30.19')&&reqs.includes('System Settings')&&reqs.includes('QA hardening'));

check('V30.20 backend and browser overlay installed',server.includes("require('./v320').install")&&b320.includes("VERSION='30.20.0'")&&index.includes('/v320-client.js?v=30.20.0')&&index.indexOf('/v319-client.js?v=30.20.0')<index.indexOf('/v320-client.js?v=30.20.0'));
check('System Settings receives V30.20 friendly grouped UX',v320.includes('v320-hero')&&v320.includes('Communication & Files')&&v320.includes('Finance & Governance')&&v320.includes('Company Financial Accounts')&&v320.includes('v320-type'));
check('Supplier and buyer contacts use immediate UI validation',v320.includes('validateContactFieldV320')&&v320.includes('v320-validation')&&v320.includes('/api/v320/contact-check')&&b320.includes('/api/v320/contact-check'));
check('smart method-compatible financial account routing implemented',v320.includes('/api/v320/financial-accounts/options')&&v320.includes('Cash Account')&&v320.includes('Company Card')&&server.includes('payments can use only configured')&&server.includes('cheque-enabled'));
check('multiple Bank Cash Card financial accounts support Accounting GL mapping',b320.includes('financial_account_type')&&b320.includes("financial_account_type==='Card'")&&b320.includes("['Bank','Cash','Wallet']")&&b320.includes('ledger_account_id')&&b320.includes('linked_bank_account_id')&&b320.includes('cheque_enabled'));
check('financial account close/archive preserves history',b320.includes("/:id/close")&&b320.includes('preserved_history:true')&&b320.includes('system_bank_account_history')&&v320.includes("action+' Financial Account'")&&v320.includes("status==='Archived'?'Archive':'Close'"));
check('legacy Finance sync resolves method-compatible default account',server.includes('V30.20: even legacy payment flows resolve a method-compatible configured financial account')&&server.includes('configuredPaymentAccount(null'));
check('generic Sales and Purchases persist the exact selected financial account',server.includes('sales(business_unit_id,invoice_no,customer_id,customer_name,order_type,payment_method,subtotal,discount,tax,total,cost_total,gross_profit,receipt_file,notes,created_by,payment_account_id)')&&server.includes('purchases(business_unit_id,purchase_no,supplier_name,payment_method,subtotal,total,attachment_file,notes,created_by,payment_account_id)')&&server.includes('paymentAccountId:paymentAccount?.id||null'));
check('MIMI POS selects and forwards the exact compatible financial account',v320.includes('chooseFinancialAccountV320')&&v320.includes('Select Company Financial Account')&&v320.includes('payment_account_id:accountId')&&server.includes('payment_account_id:req.body.payment_account_id||null'));
check('Pink Salt cash movement sources preserve selected financial accounts',b300.includes('payment_account_id')&&b300.includes('paymentAccountId:p.payment_account_id||null')&&b305.includes('payment_account_id')&&b307.includes('payment_account_id')&&b313.includes('payment_account_id')&&b313.includes('paymentAccountId:paymentAccount?.id||null'));
check('Excavator token sale and buyer payments persist selected financial accounts',server.includes('tokenPaymentAccount=configuredPaymentAccount')&&server.includes('salePaymentAccount=configuredPaymentAccount')&&server.includes("payment_account_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)")&&server.includes('paymentAccountId:salePaymentAccount?.id||null'));
check('non-cash references are required while cash references remain optional',server.includes('Payment Reference is required for non-cash sale payments.')&&base.includes('Payment Reference is required for non-cash payments.')&&v320.includes("ref.required=!cash"));
check('attachment Settings UI exposes only simple user-facing limits',v320.includes('Maximum file size')&&v320.includes('Maximum attachments per upload')&&v320.includes('Allowed file formats')&&v320.includes('upload directly'));
check('V30.20 requirements documented',reqs.includes('V30.20')&&reqs.includes('Company Financial Accounts')&&reqs.includes('Remove upload-time attachment preview'));

check('V30.17 Access button regression retained',v317.includes('window.userAccessOpen=async function')&&v317.includes('onclick="userAccessOpen(${x.id})"'));


check('V30.10 import management retained',server.includes("require('./v310').install")&&b310.includes('/manage-v310')&&b310.includes('/history-v310')&&b310.includes('/cancel-v310')&&b310.includes('/void-v310')&&b310.includes('/delete-v310'));
check('import approval and downstream safeguards retained',b310.includes('pink_salt.import_sensitive_edit')&&b310.includes('production_inputs')&&b310.includes('controlled correction/reversal workflow'));
check('terminal import states block new activity',b300.includes("['Cancelled','Voided'].includes(imp.status)")&&v305.includes('Supplier Advance'));
check('whole-number count integrity retained',v310.includes('Quantity must be a whole number.')&&b300.includes('Packing recipe quantities must be whole numbers.')&&server.includes('countQuantityRequired'));
check('measurement values preserve decimals',v310.includes('/weight|kg|\\(g\\)|amount|price|cost|rate|percent|percentage/'));
check('integer step-base regression fixed',v310.includes('normalizeCountInput')&&v310.includes('!Number.isInteger(min)')&&v310.includes('i.min=String(min>0?Math.ceil(min):Math.floor(min))'));
check('generic Quantity no longer forces restaurant measurements to integers',v310.includes("if(bu==='Excavator')return true;return false")&&v310.includes("explicit==='measurement'")&&v310.includes("explicit==='count'"));
check('Pink Salt packaging receive is unit-aware',v300.includes("data-quantity-kind=\"${String(x?.unit||'pcs').toLowerCase()==='kg'?'measurement':'count'}\"")&&v300.includes("step=\"${String(x?.unit||'pcs').toLowerCase()==='kg'?'0.001':'1'}\""));
check('Pink Salt packaging reorder is unit-aware',v300.includes('psPackagingUnitChanged')&&b300.includes('Packaging reorder level must be a whole number unless the unit is kg.'));
check('Pink Salt waste quantity follows source unit',v300.includes("q.dataset.quantityKind=count?'count':'measurement'")&&b300.includes("source==='Packaging'&&String(unit).toLowerCase()!=='kg'&&!Number.isInteger(qty)"));
check('Finance corrections preserve quantity precision',server.includes("number('quantity','Quantity',true,'1')")&&server.includes('packaging_unit')&&server.includes('Packaging quantity must be a whole number unless the unit is kg.'));
check('master requirement defines quantity step-base integrity',reqs.includes('integer field using `step=1` must not retain a fractional step base')&&reqs.includes('Restaurant/POS fractional quantity support must not be broken'));
check('Pink Salt duplicate generic nav tabs remain hidden only there',v300.includes("'businesses','sales','purchases','inventory'")&&!v300.includes("'approvals','tasks','performance'"));
check('gift-box and production integrity retained',v300.includes('Gift Box Composition')&&v300.includes('gift_pouch_weight_g')&&b300.includes('production_inputs'));
check('production PDF retained',v308.includes('Production PDF')||v308.includes('production PDF')||read('server/v308.js').includes('production-pdf'));
check('import received PDF retained',v307.includes('Download Import PDF')&&read('server/v307.js').includes('received-pdf'));
check('Finance / Accounting layers retained',server.includes("require('./v290').install")&&server.includes("require('./v302').install")&&server.includes("require('./v305').install"));
check('CEO business-unit scope retained',server.includes("req.user.role==='CEO / Owner'")&&server.includes("x-business-unit-id"));
check('responsive sidebar retained',index.includes('overflow-y:auto')||index.includes('sidebar'));
check('local test data preservation',read('.env.example').includes('SEED_DEMO_USERS=false')&&read('.env.example').includes('SEED_DEMO_DATA=false'));
check('local launcher identifies current release',read('START_LOCAL_MAC.command').includes('V30.20.0')&&read('START_LOCAL_MAC.command').includes('Creating local-only .env'));
check('release does not require a committed .env',pkg.scripts.start.includes('--env-file-if-exists=.env')&&read('.dockerignore').includes('.env'));
check('Pink Salt reference blueprint retained under docs',fs.existsSync(path.join(root,'docs/reference/PINK_SALT_WORKING_BLUEPRINT.pdf')));
check('package scripts consolidated to current release',Object.keys(pkg.scripts||{}).sort().join('|')===['dev','dev:local','qa:current','qa:runtime','start','start:local'].sort().join('|'));
const pinkContextFiles=['public/v300-client.js','public/v305-client.js','public/v307-client.js','public/v308-client.js','public/v309-client.js'];
const pinkContextText=pinkContextFiles.map(read).join('\n');
check('Pink Salt active UI files contain no copied Excavator examples',!/(Seoul Heavy Equipment|Customer \/ supplier \/ employee name|Volvo EC220|Yard \/ Rack \/ Zone)/.test(pinkContextText));

const bannedRoot=fs.readdirSync(root).filter(f=>/^(README_V|CHANGELOG_V|QA_REPORT_V|QA_RUN_V|RELEASE_MANIFEST_V|GIT_RELEASE_CHECKLIST_V|DEPENDENCY_CHECK_V)/.test(f));
check('historical release clutter removed from root',bannedRoot.length===0);
check('obsolete duplicate root clients removed',!fs.existsSync(path.join(root,'client.js'))&&!fs.existsSync(path.join(root,'v300-client.js'))&&!fs.existsSync(path.join(root,'v305-client.js')));
check('obsolete V6 snapshots removed',!fs.existsSync(path.join(root,'server/server.v6.js'))&&!fs.existsSync(path.join(root,'public/index.v6.html')));

if(failed){console.error(`\nV30.20 CURRENT QA FAILED: ${failed} check(s)`);process.exit(1)}
console.log('\nV30.20 CURRENT QA PASS');
