'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..');let pass=0,fail=0;
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const has=(f,s)=>read(f).includes(s);
const check=(name,ok,detail='')=>{if(ok){pass++;console.log('PASS',name)}else{fail++;console.error('FAIL',name,detail)}};
const pkg=JSON.parse(read('package.json')),lock=JSON.parse(read('package-lock.json')),html=read('public/index.html'),server=read('server/server.js'),runtime=read('public/runtime-v30392.js'),req=read('REQUIREMENTS_MASTER.md');
const v290=read('server/v290.js'),v300=read('server/v300.js'),v302=read('server/v302.js'),v315=read('server/v315.js'),v316=read('server/v316.js'),v319=read('server/v319.js'),v325=read('server/v325.js'),perf=read('server/v339-performance.js'),core=read('server/v3392-core.js'),client=read('public/v3392-client.js'),v335=read('public/v335-client.js');
check('release identity is 30.39.2',pkg.version==='30.39.2'&&lock.version==='30.39.2'&&lock.packages?.['']?.version==='30.39.2'&&server.includes("version:'30.39.2'")&&server.includes('Blue Ocean Market V30.39.2 running on port'));
check('qa:v3392 registered',pkg.scripts?.['qa:v3392']==='node qa/qa_v3392_core.js');
check('live browser remains three scripts',(html.match(/<script\s+src=/g)||[]).length===3);
check('all live browser assets use 30.39.2 cache identity',html.includes('/i18n-ko.js?v=30.39.2')&&html.includes('/client.js?v=30.39.2')&&html.includes('/runtime-v30392.js?v=30.39.2'));
check('V30.39.2 runtime preserves V30.39.1 before new overlay',runtime.includes('===== v3391-client.js =====')&&runtime.includes('===== v3392-client.js =====')&&runtime.indexOf('===== v3391-client.js =====')<runtime.indexOf('===== v3392-client.js ====='));
for(const f of ['public/i18n-ko.js','public/client.js','public/runtime-v30392.js']){const gz=path.join(root,f+'.gz');check(f+'.gz exists',fs.existsSync(gz));if(fs.existsSync(gz))check(f+'.gz smaller than source',fs.statSync(gz).size<fs.statSync(path.join(root,f)).size)}
check('Accounting queue is bounded by count and time',v290.includes('function processQueue(limit=40,timeBudgetMs=25)')&&v290.includes('Math.min(Number(limit)||40,100)')&&v290.includes('Math.min(Number(timeBudgetMs)||25,50)')&&v290.includes('Date.now()-started>=budget'));
check('Accounting queue uses recursive background scheduler',v290.includes('function scheduleQueue(delay=250)')&&v290.includes('setTimeout')&&v290.includes('scheduleQueue(r?.remaining?100:750)'));
check('Accounting initial historical queue is migration-ledgered',v290.includes("v30.39.2-accounting-initial-queue")&&v290.includes('system_migrations'));
const forced=[];for(const f of fs.readdirSync(path.join(root,'server')).filter(x=>x.endsWith('.js'))){const txt=read('server/'+f);if(/processQueue\s*\(\s*(1000|5000)/.test(txt)||/\.processQueue\?\.\(\s*(1000|5000)/.test(txt))forced.push(f)}
check('no forced 1000/5000 Accounting queue drains remain',forced.length===0,forced.join(','));
check('P&L schedules Accounting instead of draining it',server.includes("accountingV29?.scheduleQueue?.(0)"));
check('Pink Salt historic Finance backfill is one-time',v300.includes("v30.39.2-pink-salt-finance-backfill")&&v300.includes('INSERT OR REPLACE INTO system_migrations'));
check('Finance integrity bootstrap is one-time',v302.includes("v30.39.2-v302-finance-integrity-bootstrap")&&v302.includes('system_migrations'));
check('V30.25 finance separation backfill is one-time',v325.includes("v30.39.2-v325-finance-separation")&&v325.includes('system_migrations'));
check('effective access cache is short-lived and bounded',v316.includes('BOM_ACCESS_CACHE_MS')&&v316.includes('Math.max(500,Math.min(Number(process.env.BOM_ACCESS_CACHE_MS||5000),30000))')&&v316.includes('ACCESS_CACHE_TTL_MS'));
check('access cache exposes invalidation',v316.includes('function invalidateAccess(userId=null)')&&v316.includes('invalidateAccess(target.id)')&&v316.includes('cache_ttl_ms:ACCESS_CACHE_TTL_MS'));
check('central auth gate reuses verified request identity',server.includes('req._bomPreAuth={token,decoded,live,requested}')&&server.includes('req._bomPreAuth&&req._bomPreAuth.token===h.slice(7)'));
check('notification read endpoints no longer run alert sweep',!server.slice(server.indexOf("app.get('/api/notifications'"),server.indexOf("app.get('/api/notifications/unread-count'")).includes('runOperationalAlertSweep'));
check('alert sweep is scheduled independently',server.includes('operationalAlertTimer=setInterval')&&server.includes('initialAlertTimer=setTimeout'));
check('alert families are staged across low-priority ticks',server.includes('operationalAlertSweepRunning')&&server.includes('const stages=[ensureReportReminders,ensurePerformanceAlerts,ensurePinkSaltOperationalAlerts]')&&server.includes('runStage(i+1)'));
check('approval action-count path uses SQL for ordinary levels and row checks only for dual L5',server.includes('COALESCE(a.required_level,2)<>5')&&server.includes('COALESCE(a.required_level,2)<=?')&&server.includes('dualRows.filter(a=>approvalCanReview(a,req.user)).length'));
check('API gzip uses asynchronous zlib',perf.includes('zlib.gzip(')&&!perf.includes('gzipSync'));
check('main attachment hashing streams file data',server.includes('fs.createReadStream(filePath)')&&server.includes("crypto.createHash('sha256')"));
check('System Settings interactive uploads use streaming hash',v319.includes('hashFileAsync')&&v319.includes('await hashFileAsync(req.file.path)')&&v319.includes('async (req,res)=>'));
check('Pink Salt supplier list uses set-based summaries',v315.includes('WITH import_amount')&&v315.includes('advance_summary')&&!v315.includes('.map(s=>accountState'));
const custStart=v300.indexOf("app.get('/api/pink-salt/customers'");const custEnd=v300.indexOf("app.",custStart+10);const custBlock=v300.slice(custStart,custEnd>custStart?custEnd:custStart+12000);
check('Pink Salt customer list avoids per-customer summary loop',custStart>=0&&custBlock.includes('WITH')&&!custBlock.includes('customerSummary('));
const ordStart=v300.indexOf("app.get('/api/pink-salt/orders'");const ordEnd=v300.indexOf("app.",ordStart+10);const ordBlock=v300.slice(ordStart,ordEnd>ordStart?ordEnd:ordStart+12000);
check('Pink Salt order list avoids per-order financial loop',ordStart>=0&&ordBlock.includes('WITH')&&!ordBlock.includes('orderFinancials('));
check('Finance list endpoint is truly server paged',core.includes("app.get('/api/finance/v3392-page'")&&core.includes('LIMIT ? OFFSET ?')&&core.includes('[25,50,100]'));
check('Finance filters execute before LIMIT/OFFSET',core.indexOf("if(q){filters.push")<core.indexOf('LIMIT ? OFFSET ?')&&core.indexOf("if(from){filters.push")<core.indexOf('LIMIT ? OFFSET ?'));
check('Finance KPIs use separate scoped aggregate query',core.includes('KPI summary intentionally bypasses the evidence-enriched row CTE')&&core.includes('FROM finance_entries f WHERE 1=1${scopeSql}'));
check('Finance list has SQL evidence counts instead of row-by-row JS',core.includes('attachment_count')&&core.includes('linked_evidence_count')&&core.includes('open_request_count'));
check('legacy Finance endpoint removed per-row evidence N+1',!server.includes('.map(x=>({...x,evidence:financeLinkedEvidence(x)'));
check('V30.39.2 client uses paged Finance endpoint',client.includes("/api/finance/v3392-page")&&client.includes('pageSize:String(st.size)'));
check('Finance client sends search/status/type/evidence/date filters server-side',client.includes("search:st.search")&&client.includes('status:st.status')&&client.includes('evidence:st.evidence')&&client.includes('from:st.from')&&client.includes('to:st.to'));
check('Finance master and corrections reads start independently and secondary corrections do not block primary rows',client.includes('const correctionsPromise=loadCorrections()')&&client.includes('const d=await api(pageUrl())')&&client.includes('finally{void correctionsPromise}'));
check('old client pager skips server-paged sections',v335.includes("dataset?.serverPaged==='1'")&&v335.includes("closest?.('[data-server-paged=\"1\"]')"));
check('V30.39.2 diagnostics include event-loop lag',core.includes('event_loop_lag_ms')&&core.includes('setInterval'));
check('V30.39.2 diagnostics include Accounting queue age/depth',core.includes('accounting_sync_queue')&&core.includes('oldest_accounting_queue_seconds'));
check('V30.39.2 diagnostics include memory/access-cache/migrations',core.includes('memory_mb')&&core.includes('access_cache_ttl_ms')&&core.includes('system_migrations'));
check('V30.39.2 indexes are narrowly targeted and guarded',core.includes('idx_ps_orders_v3392_summary')&&core.includes('idx_notifications_v3392_unread')&&core.includes('/no such table|no such column/i'));
check('permanent non-blocking/set-based rule documented',req.includes('Non-blocking runtime, set-based data access & one-time migration standard — V30.39.2+ PERMANENT RULE'));
check('permanent rule forbids request-path queue draining',req.includes('Interactive user requests must not drain large background queues'));
check('permanent rule forbids N+1 growing lists',req.includes('must avoid application-level N+1 patterns'));
check('permanent rule requires access-cache invalidation',req.includes('immediate invalidation when role, BU assignment, permission override, limits, templates or copied access change'));
check('permanent rule requires ledgered migrations',req.includes('Historical data backfills and upgrade migrations must be ledgered/idempotent'));
check('permanent smart-context rule retained',req.includes('Smart context-aware change & impact-control standard')&&req.includes('Never implement a requirement blindly')&&req.includes('smallest correct scope'));
const observerCount=(runtime.match(/new MutationObserver/g)||[]).length;check('V30.39.2 does not add to audited 33-observer compatibility baseline',observerCount<=33,'found '+observerCount);
for(const f of ['server/server.js','server/v290.js','server/v300.js','server/v302.js','server/v315.js','server/v316.js','server/v319.js','server/v325.js','server/v339-performance.js','server/v3392-core.js','public/v335-client.js','public/v3392-client.js','public/runtime-v30392.js','qa/qa_v3392_core.js']){const r=cp.spawnSync(process.execPath,['--check',path.join(root,f)],{encoding:'utf8'});check('syntax '+f,r.status===0,r.stderr)}
console.log(`\nV30.39.2 CORE QA: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
