'use strict';
const assert=require('node:assert/strict'),Database=require('better-sqlite3'),db=new Database(':memory:');
db.exec(`CREATE TABLE pink_salt_suppliers(id INTEGER PRIMARY KEY,name TEXT,business_unit_id INTEGER);
CREATE TABLE pink_salt_supplier_advances(supplier_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE pink_salt_supplier_advance_allocations(supplier_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE pink_salt_supplier_packaging_allocations(supplier_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE pink_salt_supplier_advance_refunds(supplier_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE pink_salt_imports(id INTEGER PRIMARY KEY,supplier_id INTEGER,status TEXT);
CREATE TABLE pink_salt_import_items(import_id INTEGER,line_amount_krw REAL);
CREATE TABLE pink_salt_import_payments(import_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE pink_salt_packaging_movements(supplier_id INTEGER,movement_type TEXT,status TEXT,quantity REAL,unit_cost_krw REAL);
CREATE TABLE excavator_buyers(id INTEGER PRIMARY KEY,name TEXT,business_unit_id INTEGER);
CREATE TABLE excavator_buyer_payments(id INTEGER PRIMARY KEY,buyer_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE excavator_buyer_payment_allocations(buyer_id INTEGER,payment_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE excavator_buyer_refunds(buyer_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE payroll_runs(id INTEGER PRIMARY KEY,payroll_no TEXT,business_unit_id INTEGER,status TEXT,period_end TEXT,approval_journal_id INTEGER,outstanding_krw REAL);
CREATE TABLE payroll_payments(payroll_run_id INTEGER,journal_entry_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,system_key TEXT);
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,status TEXT);
CREATE TABLE accounting_journal_lines(journal_entry_id INTEGER,account_id INTEGER,business_unit_id INTEGER,entity_type TEXT,entity_id INTEGER,debit_krw REAL,credit_krw REAL);`);
db.exec(`INSERT INTO pink_salt_suppliers VALUES(1,'Salt supplier',1),(2,'Other unit',2);
INSERT INTO pink_salt_supplier_advances VALUES(1,100,'Active'),(2,900,'Active');
INSERT INTO pink_salt_supplier_advance_allocations VALUES(1,20,'Active');
INSERT INTO pink_salt_supplier_packaging_allocations VALUES(1,10,'Active');
INSERT INTO pink_salt_supplier_advance_refunds VALUES(1,5,'Active');
INSERT INTO pink_salt_imports VALUES(1,1,'Received');
INSERT INTO pink_salt_import_items VALUES(1,100);
INSERT INTO pink_salt_import_payments VALUES(1,30,'Active');
INSERT INTO pink_salt_packaging_movements VALUES(1,'Purchase Receipt','Active',5,10);
INSERT INTO excavator_buyers VALUES(1,'Buyer',1);
INSERT INTO excavator_buyer_payments VALUES(1,1,100,'Active');
INSERT INTO excavator_buyer_payment_allocations VALUES(1,1,70,'Active');
INSERT INTO excavator_buyer_refunds VALUES(1,10,'Completed');
INSERT INTO payroll_runs VALUES(1,'PAY-1',1,'Approved','2026-09-25',10,60);
INSERT INTO payroll_payments VALUES(1,11,40,'Active');
INSERT INTO accounting_accounts VALUES(1,'PINK_SALT_SUPPLIER_ADVANCES'),(2,'SALARY_PAYABLE'),(3,'CUSTOMER_ADVANCES'),(4,'ACCOUNTS_PAYABLE');
INSERT INTO accounting_journal_entries VALUES(1,'Posted'),(10,'Posted'),(11,'Posted'),(12,'Posted'),(13,'Posted');
INSERT INTO accounting_journal_lines VALUES(1,1,1,'Pink Salt Supplier',1,65,0),(10,2,1,'',NULL,0,100),(11,2,1,'',NULL,40,0),(12,3,1,'Buyer',1,0,20),(13,4,1,'Pink Salt Supplier',1,0,90);`);
const routes=new Map(),app={get:(path,...args)=>routes.set(path,args.at(-1))},auth=()=>{},allow=()=>auth;
require('../server/v358-source-reconciliation').install({app,db,auth,allow,currentUnit:r=>r.selected_business_unit_id,enforceUnit:(r,bu)=>r.user.role==='CEO / Owner'||r.user.business_unit_id===bu});
function call(bu,role='CEO / Owner',query={}){let status=200,result;const res={status:s=>(status=s,res),json:x=>{result=x;return res}};routes.get('/api/accounting/v358/source-reconciliation')({query,user:{role,business_unit_id:bu},selected_business_unit_id:bu},res);return {status,result}}
let r=call(1);assert.equal(r.status,200);assert.equal(r.result.counts.aligned,4);assert.equal(r.result.rows[0].source_balance_krw,65);assert.equal(r.result.rows[1].posted_balance_krw,60);assert.equal(r.result.rows[2].source_balance_krw,20);assert.equal(r.result.rows[3].source_balance_krw,90);assert.equal(call(1,'BU Manager').result.rows.length,4);
db.prepare("UPDATE accounting_journal_entries SET status='Pending Review' WHERE id=11").run();r=call(1);assert.equal(r.result.counts.pending,1);assert.equal(r.result.rows[1].difference_krw,null);
db.prepare("UPDATE accounting_journal_lines SET debit_krw=60 WHERE journal_entry_id=1").run();db.prepare("UPDATE accounting_journal_lines SET credit_krw=15 WHERE journal_entry_id=12").run();db.prepare("UPDATE accounting_journal_lines SET credit_krw=80 WHERE journal_entry_id=13").run();r=call(1);assert.equal(r.result.counts.difference,3);assert.equal(r.result.rows[0].difference_krw,5);assert.equal(r.result.rows[2].difference_krw,5);assert.equal(r.result.rows[3].difference_krw,10);assert.equal(call(2,'BU Manager').result.rows.length,2);
for(let id=3;id<=34;id++)db.prepare('INSERT INTO pink_salt_suppliers VALUES(?,?,1)').run(id,'Supplier '+id);
r=call(1,'BU Manager',{kind:'supplier_advance',page:1});assert.equal(r.result.total,33);assert.equal(r.result.rows.length,25);assert.equal(r.result.rows[0].source_id,1);assert.equal(r.result.counts_scope,'page');
r=call(1,'BU Manager',{kind:'supplier_advance',page:2});assert.equal(r.result.rows.length,8);assert.equal(r.result.rows[0].source_id,27);
assert.equal(call(2,'BU Manager',{kind:'supplier_advance'}).result.total,1);
r=call(1,'BU Manager',{page:2});assert.equal(r.result.total,68);assert.equal(r.result.rows.length,25);assert.equal(r.result.rows[0].kind,'supplier_advance');assert.equal(r.result.rows[8].kind,'payroll_liability');assert.equal(r.result.rows[9].kind,'buyer_advance');assert.equal(r.result.rows[10].kind,'supplier_payable');
db.close();console.log('PASS V30.58 supplier/payroll/buyer/AP source reconciliation, pending exclusion, BU isolation and mismatch');
