'use strict';
const assert=require('node:assert/strict');
const Database=require('better-sqlite3');
const db=new Database(':memory:');
db.exec(`CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,code TEXT,name TEXT,account_type TEXT,subtype TEXT,normal_balance TEXT,system_key TEXT,active INTEGER,allow_manual INTEGER);
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,business_unit_id INTEGER,status TEXT,transaction_date TEXT,source_type TEXT,source_id INTEGER,finance_entry_id INTEGER,reversal_of_id INTEGER);
CREATE TABLE accounting_journal_lines(id INTEGER PRIMARY KEY,journal_entry_id INTEGER,account_id INTEGER,business_unit_id INTEGER,debit_krw REAL,credit_krw REAL,entity_type TEXT,entity_id INTEGER);
CREATE TABLE accounting_fixed_assets_v357(id INTEGER PRIMARY KEY,business_unit_id INTEGER,asset_no TEXT,name TEXT,acquisition_date TEXT,cost_krw REAL,source_journal_id INTEGER);
CREATE TABLE accounting_fixed_asset_improvements_v357(id INTEGER PRIMARY KEY,asset_id INTEGER,source_journal_id INTEGER,amount_krw REAL);
CREATE TABLE accounting_fixed_asset_events_v357(id INTEGER PRIMARY KEY,asset_id INTEGER,event_type TEXT,amount_krw REAL,journal_id INTEGER);
CREATE TABLE payroll_runs(id INTEGER PRIMARY KEY,payroll_no TEXT,business_unit_id INTEGER,period_end TEXT,status TEXT,approval_journal_id INTEGER,outstanding_krw REAL,pay_date TEXT,payment_journal_id INTEGER,payment_method TEXT,payment_account_id INTEGER,payment_reference TEXT,payment_evidence_file TEXT,paid_by INTEGER,paid_at TEXT,updated_at TEXT,total_paid_krw REAL);
CREATE TABLE payroll_run_items(id INTEGER PRIMARY KEY,payroll_run_id INTEGER,net_salary_krw REAL,outstanding_krw REAL,paid_krw REAL,status TEXT,updated_at TEXT);
CREATE TABLE payroll_payments(id INTEGER PRIMARY KEY,payroll_run_id INTEGER,amount_krw REAL,payment_date TEXT,payment_method TEXT,payment_account_id INTEGER,reference TEXT,evidence_file TEXT,journal_entry_id INTEGER,status TEXT,created_by INTEGER);
CREATE TABLE payroll_payment_allocations(id INTEGER PRIMARY KEY,payroll_payment_id INTEGER,payroll_run_item_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE finance_entries(id INTEGER PRIMARY KEY,business_unit_id INTEGER,source_type TEXT,category TEXT,type TEXT,cash_effect INTEGER,status TEXT,verification_status TEXT,accounting_status TEXT,accounting_journal_id INTEGER,receipt_file TEXT,krw_amount REAL,amount REAL,transaction_date TEXT,reference TEXT,payment_method TEXT,payment_account_id INTEGER);
CREATE TABLE finance_attachments(id INTEGER PRIMARY KEY,finance_entry_id INTEGER,archived INTEGER,file_path TEXT);
CREATE TABLE pink_salt_suppliers(id INTEGER PRIMARY KEY,name TEXT,business_unit_id INTEGER);
CREATE TABLE pink_salt_supplier_advances(id INTEGER PRIMARY KEY,supplier_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE pink_salt_supplier_advance_allocations(id INTEGER PRIMARY KEY,supplier_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE pink_salt_supplier_packaging_allocations(id INTEGER PRIMARY KEY,supplier_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE pink_salt_supplier_advance_refunds(id INTEGER PRIMARY KEY,supplier_id INTEGER,krw_amount REAL,status TEXT);`);
const proposal=require('../accounting_spec/V30_57_COA_COMPATIBILITY_PROPOSAL.json');
const ins=db.prepare('INSERT INTO accounting_accounts(id,code,name,account_type,subtype,normal_balance,system_key,active,allow_manual) VALUES(?,?,?,?,?,?,?,?,?)');
for(let i=0;i<proposal.seed_accounts.length;i++){const a=proposal.seed_accounts[i];ins.run(i+1,a.code,a.name,a.account_type,a.subtype,a.normal_balance,a.system_key,1,Number(a.allow_manual))}
const salary=db.prepare("SELECT id FROM accounting_accounts WHERE system_key='SALARY_PAYABLE'").get().id,bank=db.prepare("SELECT id FROM accounting_accounts WHERE system_key='BANK_CLEARING'").get().id,asset=db.prepare("SELECT id FROM accounting_accounts WHERE system_key='GENERAL_INVENTORY'").get().id;
db.prepare("INSERT INTO accounting_journal_entries VALUES(1,1,'Posted','2026-09-15','Payroll Accrual',1,NULL,NULL)").run();
db.prepare("INSERT INTO accounting_journal_entries VALUES(2,1,'Posted','2026-09-20','Manual',10,10,NULL)").run();
db.prepare('INSERT INTO accounting_journal_lines VALUES(1,1,?,1,0,100,\'Payroll Run\',1)').run(salary);
db.prepare('INSERT INTO accounting_journal_lines VALUES(2,2,?,1,60,0,\'\',NULL)').run(salary);
db.prepare('INSERT INTO accounting_journal_lines VALUES(3,2,?,1,0,60,\'\',NULL)').run(bank);
db.prepare("INSERT INTO payroll_runs(id,payroll_no,business_unit_id,period_end,status,approval_journal_id,outstanding_krw,total_paid_krw) VALUES(1,'PAY-1',1,'2026-09-15','Approved',1,100,0)").run();
db.prepare("INSERT INTO payroll_run_items(id,payroll_run_id,net_salary_krw,outstanding_krw,paid_krw,status) VALUES(1,1,100,100,0,'Approved')").run();
db.prepare("INSERT INTO finance_entries VALUES(10,1,'Manual','Payroll Liability Settlement','Expense',-1,'Recorded','Verified / Correct','Posted',2,'evidence.pdf',60,60,'2026-09-20','PAY-REAL-10','Bank',1)").run();
db.prepare("INSERT INTO accounting_fixed_assets_v357 VALUES(1,1,'FA-1','Operating asset','2026-01-01',80,4)").run();
db.prepare("INSERT INTO accounting_journal_entries VALUES(4,1,'Posted','2026-01-01','Fixed Asset Acquisition',1,NULL,NULL)").run();
db.prepare('INSERT INTO accounting_journal_lines VALUES(4,4,?,1,80,0,\'Fixed Asset\',1)').run(asset);
db.prepare("INSERT INTO pink_salt_suppliers VALUES(1,'Supplier 1',1)").run();
db.prepare("INSERT INTO pink_salt_supplier_advances VALUES(1,1,100,'Active')").run();
db.prepare("INSERT INTO pink_salt_supplier_advance_allocations VALUES(1,1,30,'Active')").run();
const routes=new Map(),app={get:(p,...h)=>routes.set('GET '+p,h.at(-1)),post:(p,...h)=>routes.set('POST '+p,h.at(-1))},noop=()=>{},audit=()=>{};
const scope=(r,b)=>r.user.role==='CEO / Owner'||Number(r.user.business_unit_id)===Number(b);
require('../server/v357-completion').install({app,db,auth:noop,allow:()=>noop,currentUnit:r=>r.selected_business_unit_id,enforceUnit:scope,audit,accounting:{isPeriodClosed:()=>false},hasAccess:()=>false});
require('../server/v357-payroll-link').install({app,db,auth:noop,requirePayroll:noop,enforceUnit:scope,isPeriodClosed:()=>false,audit,refreshPayrollRunTotals:id=>{const t=db.prepare('SELECT SUM(outstanding_krw) outstanding,SUM(paid_krw) paid FROM payroll_run_items WHERE payroll_run_id=?').get(id),status=t.outstanding<=.005?'Paid':t.paid>0?'Partially Paid':'Approved';db.prepare('UPDATE payroll_runs SET outstanding_krw=?,total_paid_krw=?,status=? WHERE id=?').run(t.outstanding,t.paid,status,id);return {...t,status}}});
function call(method,path,body={},role='CEO / Owner',bu=1){let status=200,payload;const req={params:{id:body.path_id||1},body,user:{id:1,role,business_unit_id:bu},selected_business_unit_id:role==='CEO / Owner'?0:bu,query:{}};const res={status:n=>(status=n,res),json:x=>payload=x};routes.get(method+' '+path)(req,res);return {status,payload}}
let r=call('GET','/api/accounting/coa-compatibility-v357');assert.equal(r.status,200,r.payload?.error);assert.equal(r.payload.rows.length,138);assert.equal(r.payload.seed_collision_count,30);assert.equal(r.payload.seed_differences.length,0);
assert.equal(call('GET','/api/accounting/coa-compatibility-v357',{},'Business Unit Manager').status,403);
r=call('POST','/api/accounting/policy-drafts-v357',{kind:'Tax',jurisdiction:'KR',label:'Unapproved rule',effective_from:'2026-10-01',rate_percent:10,evidence_reference:'OWNER-DRAFT-1'});assert.equal(r.status,201,r.payload?.error);assert.equal(r.payload.posting_enabled,false);
assert.equal(call('POST','/api/accounting/policy-drafts-v357',{kind:'Tax',jurisdiction:'KR',label:'Bad rate',effective_from:'2026-10-01',rate_percent:200,evidence_reference:'OWNER-DRAFT-2'}).status,400);
r=call('POST','/api/accounting/fixed-asset-intents-v357',{asset_id:1,event_type:'Ownership Transfer',effective_date:'2026-10-01',amount_krw:0,target_business_unit_id:2,external_reference:'MOVE-1',evidence_reference:'OWNER-DRAFT-3'});assert.equal(r.status,201,r.payload?.error);assert.equal(r.payload.posting_enabled,false);
assert.equal(call('POST','/api/accounting/fixed-asset-intents-v357',{asset_id:1,event_type:'Ownership Transfer',effective_date:'2026-10-01',amount_krw:0,target_business_unit_id:2,external_reference:'MOVE-1',evidence_reference:'OWNER-DRAFT-3'}).status,409);
r=call('GET','/api/accounting/supplier-credit-review-v357');assert.equal(r.status,200,r.payload?.error);assert.equal(r.payload.rows[0].operational_available_krw,70);
r=call('GET','/api/payroll/runs/:id/eligible-finance-v357');assert.equal(r.status,200,r.payload?.error);assert.equal(r.payload.rows.length,1);
const beforeFinance=db.prepare('SELECT COUNT(*) n FROM finance_entries').get().n,beforeJournals=db.prepare('SELECT COUNT(*) n FROM accounting_journal_entries').get().n;
r=call('POST','/api/payroll/runs/:id/pay',{finance_entry_id:10});assert.equal(r.status,200,r.payload?.error);assert.equal(r.payload.status,'Partially Paid');assert.equal(r.payload.outstanding_krw,40);assert.equal(call('POST','/api/payroll/runs/:id/pay',{finance_entry_id:10}).status,400);
assert.equal(db.prepare('SELECT COUNT(*) n FROM finance_entries').get().n,beforeFinance);assert.equal(db.prepare('SELECT COUNT(*) n FROM accounting_journal_entries').get().n,beforeJournals);assert.equal(db.prepare('SELECT finance_entry_id FROM payroll_payments').get().finance_entry_id,10);
r=call('GET','/api/accounting/payroll-liability-review-v357');assert.equal(r.payload.rows[0].posted_linked_finance_payment_krw,60);
assert.equal(call('GET','/api/accounting/payroll-liability-review-v357',{},'Business Unit Manager').status,403);
r=call('GET','/api/accounting/consolidated-external-view-v357');assert.equal(r.status,200,r.payload?.error);assert.equal(r.payload.internal_balanced,true);
db.close();console.log('PASS live-COA preservation, inactive policy/asset drafts, supplier scope, Finance-linked payroll settlement and read-only consolidation');
