const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..');
const client=fs.readFileSync(path.join(root,'public/client.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server/server.js'),'utf8');
const db=fs.readFileSync(path.join(root,'server/db.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
let fail=0;function check(name,ok){console.log((ok?'PASS ':'FAIL ')+name);if(!ok)fail++}
check('current version',pkg.version==='27.9.0'&&server.includes("version:'27.9.0'")&&html.includes('/client.js?v=27.9.0'));
check('confirmation root present',html.includes('id="confirmRoot"')&&client.includes('function confirmAction')&&client.includes('function reasonAction'));
check('no native browser confirm dialogs',!client.match(/\bconfirm\s*\(/));
check('no native browser prompt dialogs',!client.match(/\bprompt\s*\(/));
check('no periodic client polling',!client.includes('setInterval(')&&!client.match(/addEventListener\(['\"]focus/));
check('targeted mutation refresh helper only',client.includes('function scheduleDataSync')&&client.includes('No background/polling screen refreshes'));
check('finance correction confirmation before PUT',client.includes('Save Finance Correction')&&client.includes('Save & Resubmit'));
check('finance verification queue',client.includes('Pending Review')&&client.includes('Needs Correction')&&client.includes('Resubmitted')&&client.includes('Void / Change Requests'));
check('finance source/evidence workspace',client.includes('Source & Evidence')&&client.includes('Verification Warnings')&&client.includes('Transaction Timeline'));
check('finance dedicated detail API',server.includes("app.get('/api/finance/:id/detail'")&&server.includes('financeWarnings'));
check('finance verify evidence enforced',server.includes('Supporting receipt/evidence is required before final verification'));
check('finance critical warning CEO escalation',server.includes('Critical verification warning must be resolved or reviewed by CEO'));
check('finance correction/rejection reason required',server.includes('A reason is required for this decision'));
check('finance decision notifications',server.includes('Finance correction required')&&server.includes('Finance record rejected'));
check('finance bulk verify low risk',server.includes("app.post('/api/finance/bulk-verify'")&&client.includes('Bulk Verify Low-Risk'));
check('verified finance records locked',server.includes('Verified finance entries are locked. Use Request Change'));
check('finance request change approval',server.includes("app.post('/api/finance/:id/request-change'")&&server.includes("actionKey:'finance.verified_change'"));
check('source-linked duplicate protection',server.includes('business_unit_id=? AND source_type=? AND source_id=?')&&db.includes('idx_finance_unit_source_v274'));
check('purchase/sale source backfill',server.includes('function backfillCoreFinanceSources')&&server.includes("source_type='Purchase'")&&server.includes("source_type='Sale'"));
check('voided finance excluded from dashboards',server.includes("type='Revenue' AND status!='Voided'")&&server.includes("type='Expense' AND status!='Voided'"));
check('voided finance excluded from P&L',server.includes("status!=\\'Voided\\' AND category NOT IN"));
check('English/Korean language selector',html.includes('v275-ui')&&client.includes('한국어')&&client.includes('class="language-switch"'));
check('per-user language persistence',db.includes("v27EnsureColumn('users','preferred_language'")&&server.includes("app.put('/api/me/language'")&&client.includes("localStorage.setItem('bo_language'"));
check('Korean is the company default',client.includes("let currentLanguage=localStorage.getItem('bo_language')||'ko'"));
check('Korean UI dictionary external catalog',html.includes('/i18n-ko.js?v=27.9.0')&&client.includes('window.BO_I18N_KO'));
check('responsive UI overrides',html.includes('@media(max-width:700px)')&&html.includes('.finance-review-grid')&&html.includes('.confirm-layer'));
check('business unit erroneous lifecycle removed',!client.includes("name=\"lifecycle_stage\"${['Purchased'"));
check('sidebar Business Units CEO consolidated only',client.includes("key==='businesses')return me.role==='CEO / Owner'&&!selectedUnitId"));
check('CRM/KPI sidebar remain removed',!client.match(/\['crm','CRM'/)&&!client.match(/\['kpi','KPIs'/));
check('navigation history remains',client.includes('function appBack()')&&client.includes('function appForward()')&&client.includes("window.addEventListener('popstate'"));
check('notification close behavior remains',client.includes('onclick="closeNotifDialog()">✕')&&client.includes('if(e.target===wrap)closeNotifDialog()'));
check('sell PDF remains generated after DB commit',server.includes('const result=execute(); // database commit completes before PDF generation starts')&&server.includes('Every value used by the PDF is re-read from the authoritative database'));
check('sale update same finance source',server.includes("sourceType:'Excavator Sale',sourceId:saleId")&&server.includes('resetVerification:isUpdate'));
check('supplier machine purchase linkage preserved',server.includes("UPDATE excavator_supplier_machines SET status='Purchased'")&&client.includes('selectSupplierListedMachine'));
check('buyer country rules preserved',client.includes("o.country='South Korea'")&&server.includes("buyerType==='Local'?'South Korea'"));
check('Docker/live host binding',server.includes("app.listen(PORT,'0.0.0.0'"));
if(fail){console.error(`V27.5 QA failed: ${fail}`);process.exit(1)}console.log('V27.5 complete QA PASS');
