'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..');let pass=0,fail=0;
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const check=(name,ok,detail='')=>{if(ok){pass++;console.log('PASS',name)}else{fail++;console.error('FAIL',name,detail)}};
const pkg=JSON.parse(read('package.json')),lock=JSON.parse(read('package-lock.json'));
const html=read('public/index.html'),client=read('public/client.js'),runtime=read('public/runtime-v30392.js'),v340=read('public/v340-client.js');
const server=read('server/server.js'),v316=read('server/v316.js'),v331=read('server/v331.js'),v338=read('server/v338.js'),v330=read('server/v330.js');
check('release identity is 30.40.0',pkg.version==='30.40.0'&&lock.version==='30.40.0'&&lock.packages?.['']?.version==='30.40.0'&&server.includes("version:'30.40.0'")&&server.includes('Blue Ocean Market V30.40.0 running on port'));
check('V30.40 client is loaded last',html.includes('/v340-client.js?v=30.40.0')&&html.indexOf('/runtime-v30392.js?v=30.40.0')<html.indexOf('/v340-client.js?v=30.40.0'));
check('Chrome translation suppression is declared in HTML',html.includes('name="google" content="notranslate"')&&html.includes('class="notranslate"')&&html.includes('translate="no"'));
check('Chrome translation suppression is maintained at runtime',v340.includes('suppressBrowserTranslation')&&v340.includes("meta.name='google'")&&v340.includes("meta.content='notranslate'"));
check('sidebar navigation becomes real links for new-tab support',v340.includes("document.createElement('a')")&&v340.includes('v340-nav-link')&&v340.includes('ev.ctrlKey||ev.metaKey')&&v340.includes('routeFromHash'));
check('hash navigation restores full-screen route in new tabs',v340.includes("window.addEventListener('hashchange'")&&v340.includes('v340InitialRouteTimer')&&v340.includes('go(raw)'));
check('self-navigation cleanup removes redundant Posting Control action',v340.includes('removeRedundantCurrentPageActions')&&v340.includes('/^posting control$/i'));
check('Actions columns are detected and moved to far right',v340.includes('isActionHeader')&&v340.includes('row.appendChild(row.children[actionIdx])'));
check('Actions column is sticky and right aligned',v340.includes('position:sticky;right:0;text-align:right!important')&&v340.includes('justify-content:flex-end'));
check('wide tables remain scroll-capable rather than globally blocked',!v340.includes('overflow-x:hidden')&&!v340.includes('overflow-x: hidden'));
check('Accounting Proposal wraps to multiple lines',v340.includes('v340-proposal-col')&&v340.includes('white-space:normal!important')&&v340.includes('overflow-wrap:anywhere'));
check('table enhancement is idempotent for newly paged rows',!v340.includes("if(!table||table.dataset.v340Table==='1')return"));
check('Finance and Posting filters default collapsed',runtime.includes("const filterState338={finance:{collapsed:true")&&runtime.includes("posting:{collapsed:true"));
check('dedicated Filter cards default collapsed',v340.includes('upgradeGenericFilterCards')&&v340.includes("v340-filter-collapsed")&&v340.includes("tr('Show Filters')"));
check('redundant Date Range labels are removed',v340.includes('removeDateRangeLabels')&&runtime.includes('From Date')&&runtime.includes('To Date'));
check('machine purchase cost sorts first then entry order',client.includes("const allCosts=tx.filter(x=>costTypes.includes(x.type)).sort")&&client.includes("a.type==='Purchase'?0:1")&&client.includes('Number(a.id||0)-Number(b.id||0)'));
check('verified machine cost Void UI is removed for non-CEO',v340.includes('protectedRecord')&&v340.includes("me?.role!=='CEO / Owner'")&&v340.includes('deleteExcavatorCostV319'));
check('verified/posted generic rows hide Void for non-CEO',v340.includes('protectVerifiedVoidButtons')&&v340.includes('Accounting Posted'));
check('verified/posted Finance void is server restricted to CEO/Owner',v331.includes('protectedVerifiedStage')&&v331.includes("req.user.role!=='CEO / Owner'")&&v331.includes('Verified/posted records can be voided or reversed only by CEO / Owner.'));
check('verified Excavator payments/costs enforce same server restriction',server.match(/Verified\/posted records can be voided or reversed only by CEO \/ Owner\./g)?.length>=2);
check('receiver bank account validation is server-side',v338.includes('Receiver account number may contain only numbers, spaces and hyphens, with at least 4 digits.'));
check('receiver account validation is client-side with minimum digit count',v340.includes("input[name=\"account_number\"]")&&v340.includes("digits=(v.match(/\\d/g)||[]).length")&&v340.includes('digits<4'));
check('account manager closes after successful save',runtime.includes('v338CloseAccountManager()'));
check('supplier machine modal closes after successful save',client.includes('saveExcavatorSupplierMachine')&&client.includes('closeModalAfterSave'));
check('Cash UI clears/disables receiver account fields',v340.includes('cashReceiverSync')&&v340.includes("text(method.value).toLowerCase()==='cash'")&&v340.includes("input.disabled=true;input.value=''"));
check('machine payment backend requires receiver only for electronic methods',server.includes("const receiverRequired=paymentType==='Purchase'&&/bank|card|cheque|check|wallet/i.test(method)"));
check('buyer refund Cash no longer requires receiver account',server.includes("buyerRefundReceiverAccount")&&server.includes("required:method.toLowerCase()!=='cash'"));
check('Pakistan resale Cash refund no longer requires receiver account',v330.includes("required:refundMethod.toLowerCase()!=='cash'"));
check('multi-profile access tables exist',v316.includes('CREATE TABLE IF NOT EXISTS user_access_profiles')&&v316.includes('CREATE TABLE IF NOT EXISTS access_permission_groups')&&v316.includes('CREATE TABLE IF NOT EXISTS user_permission_groups'));
check('approval authority is separate from feature profiles',v316.includes('CREATE TABLE IF NOT EXISTS user_approval_authority')&&v316.includes('approval_level')&&v316.includes('payment_limit'));
check('multiple profiles are additive in effective access',v316.includes('assignedProfiles(userId')&&v316.includes('permission_sources')&&v316.includes("type:'profile'"));
check('permission groups are additive in effective access',v316.includes('assignedGroups(userId')&&v316.includes("type:'group'"));
check('user overrides remain last-mile effective access controls',v316.includes('user_access_overrides')&&v316.includes("effect==='Allow'")&&v316.includes("effect==='Deny'"));
check('existing legacy roles migrate safely into profiles',v316.includes('Migrat')||v316.includes('migration'));
check('new users receive an initial access profile',server.includes('ensureInitialProfile?.(')&&v316.includes('function ensureInitialProfile'));
check('per-profile and per-group BU scope is stored',v316.includes('user_access_profiles')&&v316.includes('business_unit_id')&&v316.includes('user_permission_groups'));
check('removing a BU cleans its scoped access objects',v316.includes("const scopedTables=['user_access_profiles','user_permission_groups','user_approval_authority','user_access_overrides','user_access_limits']")&&v316.includes('business_unit_id NOT IN'));
check('Access Profile CRUD and duplicate endpoints exist',v316.includes("app.post('/api/access/profiles'")&&v316.includes("app.put('/api/access/profiles/:role_key'")&&v316.includes("/duplicate'"));
check('multi-profile assignment endpoint exists',v316.includes("app.put('/api/access/users/:id/profiles'"));
check('permission-group assignment endpoint exists',v316.includes("app.put('/api/access/users/:id/groups'"));
check('approval-authority endpoint exists',v316.includes("app.put('/api/access/users/:id/approval-authority'"));
check('bulk profile assignment endpoint exists',v316.includes("app.post('/api/access/users/bulk-profiles'"));
check('V30.40 clone/copy endpoint exists',v316.includes("app.post('/api/access/users/:id/copy-v340'"));
check('simple Access UI uses profiles/groups/scope/authority/advanced tabs',v340.includes("['summary','Effective Access']")&&v340.includes("['profiles','Access Profiles']")&&v340.includes("['groups','Permission Groups']")&&v340.includes("['authority','Approval Authority']")&&v340.includes("['advanced','Advanced Access']"));
check('granular exceptions are explicitly advanced-only',v340.includes('Advanced / Individual Exceptions')&&v340.includes('Normal administrators should not need this section.'));
check('Effective Access exposes permission source',v340.includes('permissionSourcesHtml')&&v340.includes("Profile: ${x.name}")&&v340.includes("Group: ${x.name}"));
check('profile library shows affected/assigned users',v340.includes('Profile Library')&&v340.includes('Assigned Users'));
check('bulk user selection UI exists',v340.includes('v340ToggleAllUsers')&&v340.includes('v340BulkAssignProfile'));
check('profile edits warn they affect assigned users',v340.includes('This profile change affects assigned users immediately after confirmation.'));
check('approval level remains visibly separate in UI',v340.includes('Approval Authority')&&v340.includes('Approval Level')&&v340.includes('payment_limit'));
check('global profile/group/authority scope is uniquely constrained',v316.includes('ux_user_access_profiles_scope')&&v316.includes('ux_user_permission_groups_scope')&&v316.includes('ux_user_approval_authority_scope')&&v316.includes('COALESCE(business_unit_id,0)'));
check('shared profile library mutation is restricted',v316.includes('function canManageProfileLibrary')&&v316.includes("req.user.role==='System Administrator'")&&v316.includes('Only CEO / Owner or an authorized System Administrator can manage the shared Access Profile library.'));
check('legacy apply-template synchronizes Access Profiles',v316.includes("template_apply")&&v316.includes("DELETE FROM user_access_profiles WHERE user_id=?")&&v316.includes("INSERT INTO user_access_profiles(user_id,role_key,business_unit_id,is_primary,assigned_by)"));
check('clone respects target BU scope and protects CEO profile',v316.includes('function cloneAccessSetup')&&v316.includes('scopeOk=r=>r.business_unit_id==null||allowed.has')&&v316.includes("source.role==='CEO / Owner'"));
check('approval authority global scope uses null-safe replace',v316.includes("business_unit_id IS NULL").toString()&&v316.includes("DELETE FROM user_approval_authority WHERE user_id=? AND business_unit_id IS NULL"));
check('Finance maker-checker blocks own verification',server.includes('Maker/checker control: you cannot review or verify your own Finance transaction.')&&server.includes("Number(f.created_by)===Number(req.user.id)"));
check('Accounting maker-checker blocks own final posting',read('server/v318.js').includes('Maker/checker control: you cannot final-post an Accounting proposal you created.'));
check('L5 finance reviewer uses configured authority plus Finance verify permission',server.includes("roleApprovalLevel(user,bu)")&&server.includes("accessV316.canAction(user.id,'finance','verify',bu)"));
check('Profile Library editing controls are hidden for ordinary delegated users',v340.includes("canLibrary=me?.role==='CEO / Owner'||me?.role==='System Administrator'")&&v340.includes('Read-only profile library'));
check('V30.40 QA scripts are registered',pkg.scripts?.['qa:v340']==='node qa/qa_v340_access_ui.js'&&pkg.scripts?.['qa:v340:runtime']==='node qa/runtime_v340_access.js');
check('legacy performance runtime remains loaded and unchanged as compatibility layer',html.includes('/runtime-v30392.js?v=30.40.0')&&runtime.includes('V30.39.2 consolidated compatibility runtime'));
for(const f of ['server/server.js','server/v316.js','server/v331.js','server/v330.js','server/v338.js','public/client.js','public/runtime-v30392.js','public/v340-client.js']){try{cp.execFileSync(process.execPath,['-c',path.join(root,f)],{stdio:'pipe'});check('syntax '+f,true)}catch(e){check('syntax '+f,false,e.stderr?.toString()||e.message)}}
console.log(`\nV30.40 QA: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
