'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const financing=read('server/v356-financing.js'),posting=read('server/v318.js'),client=read('public/v356-accounting.js');
let routes=[];const app={get:(url,...f)=>routes.push(['GET',url,f.at(-1)]),post:(url,...f)=>routes.push(['POST',url,f.at(-1)])};
const mockDb={exec:()=>{},prepare:sql=>({get:()=>null,all:()=>[],run:()=>({})}),transaction:fn=>fn};
require('../server/v356-financing').install({app,db:mockDb,auth:()=>{},allow:()=>()=>{},currentUnit:()=>1,enforceUnit:()=>true,audit:()=>{},accounting:{postJournal:()=>{throw new Error('should not be called')}},hasAccess:()=>false});
const endpoint=routes.find(x=>x[0]==='POST'&&x[1].endsWith('/prepare-reclassification'));
assert(endpoint,'Reclassification route exists');
let status=0,response=null;endpoint[2]({params:{id:1,repaymentId:1},body:{},user:{id:2,role:'Staff'}},{status:n=>({json:o=>{status=n;response=o}}),json:o=>{response=o}});
assert.equal(status,403);assert(response.error.includes('authority'));
assert(financing.includes('accounting.postJournal('));assert(financing.includes("sourceType:'Financing Repayment Reclassification'"));
assert(financing.includes('single-expense/single-bank payment'));
assert(financing.includes('reversal_of_id=?'));
assert(financing.includes('finance_entry_id INTEGER NOT NULL UNIQUE'));
assert(financing.includes('idx_financing_reclassification_unique'));
assert(!financing.includes('INSERT INTO finance_entries'));
assert(posting.includes("j.source_type==='Financing Repayment Reclassification'"));
assert(posting.includes('original posted journal is no longer eligible'));
assert(client.includes('v356PrepareRepayment'));assert(client.includes('v356r_global_liability'));new vm.Script(client);
for(const file of ['server/server.js','server/v318.js','server/v356-financing.js','public/v356-accounting.js'])new vm.Script(read(file),{filename:file});
console.log('V30.56.2 financing: permission denial, unique-source/single-bank safeguards, posting gate and script parsing passed (static/mock checks; no authenticated live DB test).');
