const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server/server.js'),'utf8');
const db=fs.readFileSync(path.join(root,'server/db.js'),'utf8');
const client=fs.readFileSync(path.join(root,'public/client.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
let fail=0;
function check(name,cond){if(cond)console.log('PASS',name);else{console.log('FAIL',name);fail++}}
check('version package 27.1.0',pkg.version==='27.1.0');
check('health version 27.1.0',server.includes("version:'27.1.0'"));
check('client cache 27.1.0',html.includes('/client.js?v=27.1.0'));
check('buyer runtime status migration',db.includes("v27EnsureColumn('excavator_buyer_payments','status'"));
check('supplier machines fix preserved',client.includes('excavatorSupplierMachines') && client.includes("Deal ${esc(a.asset_no||'—')}"));
check('excavator overview endpoint',server.includes("app.get('/api/excavator/overview'"));
check('overview scoped to business unit',server.includes("SELECT * FROM excavator_assets WHERE business_unit_id=? ORDER BY id DESC"));
check('overview total machine cost',server.includes('totalCost=purchase+logistics+repair+partCost+other'));
check('overview sale profit loss',server.includes("profit_loss_status:sale<=0?'Not Sold'"));
check('dashboard uses overview',client.includes("api('/api/excavator/overview')"));
check('dashboard purchase/logistics/repair/parts',client.includes('Purchase Cost')&&client.includes('Logistics')&&client.includes('Repairs + Parts'));
check('dashboard lifecycle',client.includes('Lifecycle')&&client.includes('Sold / Completed'));
check('existing sale GET endpoint',server.includes("app.get('/api/excavator/assets/:id/sale'"));
check('sell form loads existing sale',client.includes("isUpdate=!!existing")&&client.includes("isUpdate?'Update Sale':'Sell Machine'"));
check('update sale action label',client.includes("isUpdate?'Update Sale':'Complete Sale'"));
check('sale updates same transaction',server.includes('saleId=existingSale.id')&&server.includes('UPDATE excavator_transactions SET type=?'));
check('sale finance sync by same source',server.includes("sourceType:'Excavator Sale',sourceId:saleId")&&server.includes('resetVerification:isUpdate'));
check('finance sync updates existing entry',server.includes('UPDATE finance_entries SET business_unit_id=?,type=?,category=?,amount=?'));
check('existing buyer auto sale type frontend',client.includes("const autoType=isKoreanBuyer(b)?'Local Sale':'Export Sale'"));
check('existing buyer auto sale type backend',server.includes("saleType=local?'Local Sale':'Export Sale'"));
check('buyer country drives export destination backend',server.includes("destination=local?'':String(selectedBuyer.country||destination).trim()"));
check('approval rule schema',db.includes('CREATE TABLE IF NOT EXISTS approval_rules'));
check('approval history schema',db.includes('CREATE TABLE IF NOT EXISTS approval_history'));
check('approval center endpoint',server.includes("app.get('/api/approvals'"));
check('approval rule endpoints',server.includes("app.get('/api/approval-rules'")&&server.includes("app.post('/api/approval-rules'"));
check('dual finance CEO approval',server.includes("required===5")&&server.includes("Finance Approved")&&server.includes("CEO Approved"));
check('void reason required',server.includes("Void reason is required."));
check('document workflow',db.includes("['documents','workflow_status'")&&client.includes('Draft')&&client.includes('Submitted')&&client.includes('Final'));
check('performance KPI rules schema',db.includes('CREATE TABLE IF NOT EXISTS performance_kpi_rules'));
check('performance reviews schema',db.includes('CREATE TABLE IF NOT EXISTS performance_reviews'));
check('people performance UI',client.includes("async function peoplePerformance"));
check('task assignment manager restriction',server.includes('Only CEO or authorized managers can create and assign work.'));
check('task work points',db.includes("['tasks','work_points'")&&client.includes('Work Points'));
check('task comments',db.includes('CREATE TABLE IF NOT EXISTS task_comments'));
check('daily weekly monthly reporting schema',db.includes('CREATE TABLE IF NOT EXISTS work_reports')&&db.includes('CREATE TABLE IF NOT EXISTS work_report_rules'));
check('work report versions',db.includes('CREATE TABLE IF NOT EXISTS work_report_versions'));
check('work report action history',db.includes('CREATE TABLE IF NOT EXISTS work_report_actions'));
check('work report UI cadences',client.includes('Daily · Weekly · Monthly Reports'));
check('manager CEO both reporting',client.includes('Manager + CEO')&&server.includes("mode==='CEO'")&&server.includes("mode==='Manager'"));
check('follow-up task from report',client.includes('Create Follow-up Task')||server.includes('follow-up'));
check('unit scoped approvals',server.includes("unitScope(req,'a.business_unit_id')"));
check('unit scoped reports',server.includes("unitScope(req,'r.business_unit_id')"));
check('unit scoped performance',server.includes("business_unit_id")&&client.includes('People & Performance'));
check('purchase form undefined existing fixed',!client.includes("esc(existing?.notes||'')"));
check('sidebar icons and collapse preserved',client.includes('sidebar-collapsed')||client.includes('toggleSidebar'));
check('unit switch opens dashboard',client.includes("view='dashboard'")&&client.includes('switchUnit'));
if(fail){console.error(`V27.1 QA failed: ${fail}`);process.exit(1)}
console.log('V27.1 complete static regression QA: PASS');
