const fs=require('fs'),assert=require('assert'),path=require('path'),zlib=require('zlib');const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');let count=0;function check(label,fn){fn();console.log('PASS '+label);count++}
const backend=read('server/v343.js'),simple=read('public/v343-client.js'),advanced=read('public/runtime-v30392.js'),detail=read('public/v355-client.js'),html=read('public/index.html');
check('overview is authorized, BU scoped, read-only',()=>{assert(backend.includes("app.get('/api/v355/accounting/payment-accounts/overview',auth,allow('finance','accounting')"));assert(backend.includes('.filter(a=>canSeeAccount(req,a))'));assert(!backend.includes("app.post('/api/v355/accounting"))});
check('summary derives movements from existing accountEvents, not a new cash record',()=>{assert(backend.includes('const events=accountEvents(a.id)'));assert(backend.includes('opening_balance_krw'));assert(backend.includes("balance_basis:'Recorded account movements"))});
check('posted GL separate, unique mapping only, and shared mappings excluded',()=>{assert(backend.includes('mappings===1?db.prepare'));assert(backend.includes("j.status IN ('Posted','Reversed')"));assert(backend.includes('shared_ledger:mappings!==1'))});
check('both cash layouts use a single scoped overview',()=>{assert(simple.includes("/api/v355/accounting/payment-accounts/overview"));assert(advanced.includes("/api/v355/accounting/payment-accounts/overview"));assert(advanced.includes('Recorded Balance (KRW)'))});
check('existing account actions still present in both layouts',()=>{assert(simple.includes('v343OpenAccount(${Number(p.id)})'));assert(advanced.includes('v343OpenAccount(${Number(p.id)})'));assert(detail.includes('journalDetailV29'))});
check('detail includes posted GL, movement, trend, reconciliation, statements',()=>{for(const word of ['balanceTrend355','v355ShowReconciliation','v355ShowRelatedJournals','v343DownloadStatementPdf','v355ExportAccountCsv','statementRows343(d)','summary.posted_gl_balance_krw'])assert(simple.includes(word),word)});
check('read-only detail reconciliation and journal calls',()=>{assert(detail.includes("api('/api/accounting/reconciliation')"));assert(detail.includes("api('/api/accounting/journal?account_id='"));assert(!detail.includes('method:\'POST\''))});
check('differentiate recorded cash, posted GL and bank-confirmed balance',()=>{assert(simple.includes('not bank-confirmed available funds'));assert(detail.includes('bank-confirmed available funds'));assert(!simple.includes('Last Reconciled Bank Balance'))});
check('CSV formula protection and UTF8 export',()=>{assert(detail.includes('if(/^\\s*[=+@-]/.test(x))'));assert(detail.includes("'\\uFEFF'"))});
check('EN/KR translations and responsive stylesheet',()=>{assert(detail.includes('기록된 계좌 잔액'));assert(detail.includes('@media(max-width:680px)'))});
check('browser script loaded after prior extensions',()=>{assert(html.indexOf('/v355-client.js')>html.indexOf('/v353-client.js'))});
check('gzip mirrors loaded source assets',()=>{for(const file of ['runtime-v30392.js','v343-client.js','v355-client.js','index.html'])assert.deepStrictEqual(zlib.gunzipSync(fs.readFileSync(path.join(root,'public',file+'.gz'))),fs.readFileSync(path.join(root,'public',file)))});
check('package version and production health version updated',()=>{assert.equal(require('../package.json').version,'30.55.0');assert(read('server/server.js').includes("version:'30.55.0'"))});
console.log('V30.55 static QA: '+count+' checks passed; authenticated staging/database QA still required.');
