'use strict';
const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const db=new DatabaseSync(':memory:');
db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,code TEXT,account_type TEXT,active INTEGER,allow_manual INTEGER,name TEXT,subtype TEXT,system_key TEXT);
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,status TEXT,business_unit_id INTEGER,transaction_date TEXT,finance_entry_id INTEGER,reversal_of_id INTEGER);
CREATE TABLE accounting_journal_lines(id INTEGER PRIMARY KEY,journal_entry_id INTEGER,account_id INTEGER,debit_krw REAL,credit_krw REAL);
INSERT INTO accounting_accounts VALUES(1,'A1','Asset',1,1,'Equipment','Fixed Asset',NULL),(2,'A2','Asset',1,1,'Accumulated','Fixed Asset',NULL),(3,'E1','Expense',1,1,'Depreciation','Depreciation',NULL),(4,'C1','Asset',1,0,'Bank','Cash & Bank','BANK_CLEARING');
INSERT INTO accounting_journal_entries VALUES(10,'Posted',1,'2026-01-01',NULL,NULL),(11,'Posted',1,'2026-02-15',NULL,NULL),(12,'Posted',2,'2026-02-15',NULL,NULL),(13,'Posted',1,'2026-02-15',99,NULL),(14,'Posted',1,'2026-02-15',NULL,NULL);
INSERT INTO accounting_journal_lines(journal_entry_id,account_id,debit_krw,credit_krw) VALUES(10,1,1000,0),(10,2,0,1000),(11,1,200,0),(11,2,0,200),(12,1,300,0),(12,2,0,300),(13,1,400,0),(13,2,0,400),(14,1,500,0),(14,4,0,500);`);
db.transaction=fn=>()=>{db.exec('BEGIN');try{const v=fn();db.exec('COMMIT');return v}catch(e){db.exec('ROLLBACK');throw e}};
const routes=new Map(),app={get:(path,...h)=>routes.set('GET '+path,h.at(-1)),post:(path,...h)=>routes.set('POST '+path,h.at(-1))};
const postJournal=p=>{assert.equal(p.lines.reduce((n,l)=>n+l.debit_krw-l.credit_krw,0),0);const id=Number(db.prepare("INSERT INTO accounting_journal_entries(status,business_unit_id,transaction_date) VALUES('Pending Review',?,?)").run(p.businessUnitId,p.transactionDate).lastInsertRowid);for(const l of p.lines)db.prepare('INSERT INTO accounting_journal_lines(journal_entry_id,account_id,debit_krw,credit_krw) VALUES(?,?,?,?)').run(id,l.account_id,l.debit_krw,l.credit_krw);return id};
require('../server/v357-realworld').install({app,db,auth:()=>{},allow:()=>()=>{},currentUnit:()=>1,enforceUnit:(req,bu)=>bu===1,audit:()=>{},accounting:{isPeriodClosed:()=>false,postJournal},hasAccess:()=>true});
const base='/api/accounting/fixed-assets-v357';
function call(method,path,body={},params={id:'1'}){let status=200,payload;const res={status:n=>(status=n,res),json:x=>payload=x};const handler=routes.get(method+' '+path);assert(handler,path);handler({body,params,query:{},user:{id:1,role:'CEO / Owner'}},res);return {status,payload};}
const policy='Approved FA policy 2026';
const create=call('POST',base,{asset_no:'FA-100',name:'Workshop compressor',category:'Equipment',acquisition_date:'2026-01-02',cost_krw:1000,residual_krw:0,useful_life_months:10,asset_account_id:1,contra_account_id:2,expense_account_id:3,source_journal_id:10,policy_reference:policy});assert.equal(create.status,201,create.payload.error);
const dep=(date)=>call('POST',base+'/:id/depreciation',{period_end:date,policy_reference:policy});
let first=dep('2026-01-31');assert.equal(first.payload.amount_krw,100);db.prepare("UPDATE accounting_journal_entries SET status='Posted' WHERE id=?").run(first.payload.journal_id);
let improvement=call('POST',base+'/:id/improvements',{improvement_date:'2026-02-15',amount_krw:200,source_journal_id:11,policy_reference:policy});assert.equal(improvement.status,201,improvement.payload.error);
let state=call('GET',base+'/:id').payload;assert.equal(state.capitalized_cost_krw,1200);assert.equal(state.carrying_value_krw,1100);assert(state.depreciation_schedule_requires_review);assert.equal(dep('2026-03-31').status,409);
assert.equal(call('POST',base+'/:id/improvements',{improvement_date:'2026-02-15',amount_krw:200,source_journal_id:11,policy_reference:policy}).status,409);
for(const [source,amount] of [[12,300],[13,400],[14,500]])assert.equal(call('POST',base+'/:id/improvements',{improvement_date:'2026-02-15',amount_krw:amount,source_journal_id:source,policy_reference:policy}).status,409);
const held=Number(db.prepare("INSERT INTO accounting_journal_entries(status,business_unit_id,transaction_date,reversal_of_id) VALUES('Pending Review',1,'2026-02-16',11)").run().lastInsertRowid);
assert.equal(call('GET',base+'/:id').payload.carrying_value_krw,1100);
assert.equal(call('POST',base+'/:id/depreciation-schedule',{effective_date:'2026-03-01',remaining_months:10,policy_reference:policy}).status,409);
db.prepare("UPDATE accounting_journal_entries SET status='Rejected' WHERE id=?").run(held);
const schedule=call('POST',base+'/:id/depreciation-schedule',{effective_date:'2026-03-01',remaining_months:10,policy_reference:policy});assert.equal(schedule.status,201,schedule.payload.error);
assert.equal(call('POST',base+'/:id/depreciation-schedule',{effective_date:'2026-03-01',remaining_months:10,policy_reference:policy}).status,409);
const location=call('POST',base+'/:id/location',{effective_date:'2026-03-02',location:'Seoul workshop',reason:'Moved to service area'});assert.equal(location.status,201,location.payload.error);
assert.equal(call('GET',base+'/:id').payload.current_location,'Seoul workshop');
assert.equal(call('POST',base+'/:id/location',{effective_date:'2026-02-01',location:'Old location',reason:'Backdated move'}).status,409);
for(let m=3;m<=12;m++){const x=dep('2026-'+String(m).padStart(2,'0')+'-28');assert.equal(x.status,201,x.payload.error);assert.equal(x.payload.amount_krw,110);if(m===3)assert.equal(call('GET',base+'/:id').payload.carrying_value_krw,1100);db.prepare("UPDATE accounting_journal_entries SET status='Posted' WHERE id=?").run(x.payload.journal_id)}
state=call('GET',base+'/:id').payload;assert.equal(state.posted_depreciation_krw,1200);assert.equal(state.carrying_value_krw,0);
const disposal=call('POST',base+'/:id/dispose-fully-depreciated',{disposal_date:'2027-01-02',policy_reference:policy});assert.equal(disposal.status,201,disposal.payload.error);assert.equal(db.prepare('SELECT SUM(debit_krw) d,SUM(credit_krw) c FROM accounting_journal_lines WHERE journal_entry_id=?').get(disposal.payload.journal_id).d,1200);
db.prepare("UPDATE accounting_journal_entries SET status='Posted' WHERE id=?").run(disposal.payload.journal_id);state=call('GET',base+'/:id').payload;assert.equal(state.disposed,true);assert.equal(state.carrying_value_krw,0);assert.equal(call('POST',base+'/:id/location',{effective_date:'2027-01-03',location:'Another area',reason:'After disposal'}).status,409);
assert.equal(db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE name='finance_entries'").get().n,0);
console.log('PASS source-linked capitalized improvement, duplicate/BU/Finance source guards, schedule revision, posted-only values, location history, full disposal, and no fabricated Finance');
