#!/usr/bin/env node
'use strict';
// Current-source gate. Does not alter historical version-specific QA assertions.
const {spawnSync}=require('node:child_process');const fs=require('node:fs');const zlib=require('node:zlib');const assert=require('node:assert/strict');const path=require('node:path');
const root=path.resolve(__dirname,'..'),files=['qa_v357_coa_compatibility.js','qa_v3572_consolidated.js','qa_v3572_fixed_asset_fixture.js','qa_v3572_real_sqlite.js','qa_v3573_interbu_readonly.js','qa_v3575_integrity_review.js','qa_v3576_asset_lifecycle.js','qa_v3576_interbu_elimination.js','qa_v3577_accrual_settlement.js','qa_v3577_inventory_review.js','qa_v3562_financing_integration.js'];let failures=0;
for(const f of files){const r=spawnSync(process.execPath,[path.join('qa',f)],{cwd:root,encoding:'utf8',timeout:60000});if(r.status){failures++;console.error('FAIL',f,(r.stderr||r.stdout).slice(-900));}else console.log('PASS',f);}
const mirror=spawnSync('python3',['qa/sql_v354_integrity.py'],{cwd:root,encoding:'utf8',timeout:60000});if(mirror.status){failures++;console.error('FAIL historical sale/purchase Finance duplicate fixture',(mirror.stderr||mirror.stdout).slice(-900));}else console.log('PASS historic ₩9,500 sale mirror and ₩500 actual receipt regression');
for(const f of ['server/v357-realworld.js','server/v357-inventory-review.js','public/v357-inventory-review.js','public/v357-fixed-assets.js','public/v357-expenses.js','public/v357-integrity-review.js','public/v357-accounting-workspace.js','public/v357-interbu.js']){const r=spawnSync(process.execPath,['--check',f],{cwd:root,encoding:'utf8'});if(r.status){failures++;console.error('FAIL syntax',f);}else console.log('PASS syntax',f);}
for(const f of ['v357-inventory-review.js','v357-fixed-assets.js','v357-expenses.js','v357-integrity-review.js','v357-accounting-workspace.js','v357-interbu.js']){try{assert.deepEqual(zlib.gunzipSync(fs.readFileSync(path.join(root,'public',f+'.gz'))),fs.readFileSync(path.join(root,'public',f)));console.log('PASS compressed asset',f);}catch(e){failures++;console.error('FAIL compressed asset',f,e.message)}}
const js=fs.readFileSync(path.join(root,'server/v357-realworld.js'),'utf8'),html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),nav=fs.readFileSync(path.join(root,'public/v357-accounting-workspace.js'),'utf8');
const invariants={no_new_finance_inserts:!/INSERT\s+INTO\s+finance_entries/i.test(js),review_read_only:js.includes("'/api/accounting/v357-integrity-review'")&&js.includes('no_cash_movement:true'),source_journal_picker:js.includes("'/api/accounting/fixed-assets-v357/source-journals'")&&js.includes('NOT EXISTS(SELECT 1 FROM accounting_fixed_assets_v357'),ui_wired:html.includes('/v357-integrity-review.js?v=30.59.0')&&nav.includes("['Accounting Integrity Review','integrity']"),official_prepaid_recognition:js.includes('pending_recognition_krw:')&&js.includes('remaining_prepaid_krw:recognized?'),inventory_read_only:fs.readFileSync(path.join(root,'server/v357-inventory-review.js'),'utf8').includes("app.get('/api/accounting/v357-inventory-review'")&&html.includes('/v357-inventory-review.js?v=30.59.0')&&nav.includes("['Inventory & Cost Review','inventory']"),source_register_constraints:js.includes('source_journal_id INTEGER NOT NULL UNIQUE')};
for(const [k,v] of Object.entries(invariants)){console.log(v?'PASS':'FAIL',k);if(!v)failures++}
console.log(`V30.59.0 CONSOLIDATED CURRENT GATE ${failures?'FAIL':'PASS'}; ${files.length} suites + Finance mirror fixture, 8 syntax checks, 6 compressed assets, ${Object.keys(invariants).length} invariants; historical qa:release and Render are separate obligations.`);if(failures)process.exitCode=1;
