'use strict';
const fs=require('fs');
const read=f=>fs.readFileSync(f,'utf8');
const pkg=JSON.parse(read('package.json')),lock=JSON.parse(read('package-lock.json'));
const server=read('server/server.js'),controls=read('server/v360-accounting-controls.js'),acct=read('server/v290.js'),feedback=read('public/v345-client.js'),ui=read('public/v360-accounting-controls.js'),idx=read('public/index.html'),reports=read('public/v358-accounting.js'),source=read('server/v358-source-reconciliation.js');
let fail=0;const check=(n,v)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);if(!v)fail++};
check('V30.60 release identity',pkg.version==='30.60.0'&&lock.version==='30.60.0'&&lock.packages?.['']?.version==='30.60.0'&&server.includes("version:'30.60.0'")&&server.includes('Blue Ocean Market V30.60.0 running on port'));
check('V30.60 client loaded last',idx.includes('/v360-accounting-controls.js?v=30.60.0')&&idx.indexOf('v360-accounting-controls.js')>idx.indexOf('v3592-payroll-ui.js'));
check('Posting batch schema',controls.includes('accounting_posting_batches_v360')&&controls.includes('accounting_posting_batch_items_v360'));
check('Bulk preview + post endpoints',controls.includes("posting-control-v360/bulk-preview")&&controls.includes("posting-control-v360/bulk-post"));
check('Bulk all-or-nothing transaction',controls.includes('const tx=db.transaction')&&controls.includes('Bulk posting rolled back. No entries were posted.'));
check('Bulk eligibility preserves exceptional workflows',controls.includes("j.source_type==='Accounting Reversal'")&&controls.includes("j.source_type==='Manual Journal'")&&controls.includes("/^Financing\\b/i")&&controls.includes('/Opening|Migration/i'));
check('Bulk maker checker and period controls',controls.includes('Maker/checker: creator cannot post')&&controls.includes('Accounting period is closed')&&controls.includes('Finance/source verification incomplete'));
check('Select all ready endpoint',controls.includes('posting-control-v360/ready-ids')&&controls.includes('slice(0,100)'));
check('Posting Control KPI summary',controls.includes('ready_count')&&controls.includes('blocked_count')&&controls.includes('reversal_duplicate_count')&&controls.includes('posted_today_count')&&controls.includes('oldest_ready_days'));
check('Posting Control UI bulk controls',ui.includes('Select Page')&&ui.includes('Select All Ready')&&ui.includes('Post Selected')&&ui.includes('Bulk Posting Review'));
check('Correction resolved detection',acct.includes('resolvedFinanceCorrection')&&acct.includes("status='Resolved'")&&acct.includes("outcome='Verified / Correct'"));
check('Automatic exact reversal posting',acct.includes('autoPostCorrectionReversal')&&acct.includes('Automatic Correction Reversal Posted')&&acct.includes('System - Correction Workflow'));
check('Duplicate reversal guard',acct.includes('DUPLICATE_CORRECTION_REVERSAL')&&acct.includes('reversalRowsForOriginal'));
check('No deployment blind historical reversal creation',controls.includes('reversal-reconciliation')&&controls.includes('Deployment does not create historical reversals'));
check('Closed-period reversal safeguard',acct.includes('CORRECTION_REVERSAL_PERIOD_CLOSED'));
check('Top-level mutation overlay',feedback.includes('.bom345-global{position:fixed;inset:0;z-index:31000')&&feedback.includes("return 'transaction'")&&feedback.includes("document.getElementById('processingRoot')||document.body"));
check('Escape locked while mutation active',feedback.includes("e.key==='Escape'")&&feedback.includes('stopImmediatePropagation'));
check('Single coordinated feedback channel',feedback.includes('Single success channel')&&feedback.includes('recentToasts'));
check('Core accounting PDFs',controls.includes('trial-balance.pdf')&&controls.includes('income-statement.pdf')&&controls.includes('balance-sheet.pdf')&&controls.includes('general-ledger/:accountId.pdf'));
check('Extended accounting PDFs',controls.includes('cash-flow.pdf')&&controls.includes('management.pdf')&&controls.includes('bank-reconciliation.pdf')&&controls.includes('source-reconciliation.pdf')&&controls.includes('year-end-readiness.pdf')&&controls.includes('posting-control.pdf'));
check('PDFs built from accounting data not screen',controls.includes('Content is built from official posted GL/report data, not the screen DOM')&&controls.includes('Official Posted/Reversed'));
check('Report-specific PDF UI',ui.includes("topMap={cashflow:'cashflow',management:'management',bank:'bank',source:'source',year:'year',ledger:'ledger'}")&&ui.includes("tx.includes('balance sheet')")&&ui.includes("tx.includes('profit & loss')")&&ui.includes("tx.includes('trial balance')"));
check('V358 report state exposed for correct PDF context',reports.includes('window.__v358ReportState=state')&&reports.includes("state.active=kind")&&reports.includes("state.ledgerId=Number(id)"));
check('Source reconciliation builder remains read-only',source.includes('module.exports.build')&&source.includes('No proposed correction, Finance movement or GL adjustment is created.'));
console.log(`V30.60 Accounting controls QA: ${24-fail}/24 PASS`);process.exitCode=fail?1:0;
