'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const client=read('public/v338-client.js'),server=read('server/v338.js'),main=read('server/server.js'),v326=read('server/v326.js'),index=read('public/index.html'),ko=read('public/i18n-ko.js'),pkg=JSON.parse(read('package.json'));
const {calculateExcavatorSaleSettlementV338:calc}=require('../public/settlement-v338');
let pass=0;function ok(cond,msg){assert.ok(cond,msg);pass++;console.log('PASS',String(pass).padStart(2,'0'),msg)}
ok(pkg.version==='30.38.0','package version is 30.38.0');
ok(index.includes('/settlement-v338.js?v=30.38.0')&&index.includes('/v338-client.js?v=30.38.0'),'V30.38 browser scripts are shipped');
ok(main.includes("require('./v338').install"),'V30.38 server module is installed');
ok(server.includes('counterparty_payment_account_history'),'account edit/history schema is additive');
ok(server.includes("app.put('/api/v338/payee-accounts/:id'"),'receiver accounts can be updated');
ok(server.includes("app.put('/api/v338/payee-accounts/:id/archive'"),'receiver accounts archive instead of delete');
ok(server.includes("app.get('/api/v338/payee-account-history'"),'account change history is queryable');
ok(main.includes('sameReceiverAccount')&&main.includes('historicalReceiver'),'Finance receiver snapshots are protected from later account-master edits');
ok(client.includes("['overview','records','payments','credit','refunds','transfers','documents']"),'Pakistan Resales has seven focused sections');
for(const label of ['Overview','Resale Records','Payments & Settlements','Credit','Refunds','Pakistan → Korea Bank Transfers','Documents'])ok(client.includes(label),`Pakistan Resales includes ${label}`);
ok(client.includes('resaleActive338')&&client.includes('resaleActive338.get(buyerId)'), 'Pakistan Resale selected section survives child workflow refresh');
ok(client.includes('allocateResaleCreditV330')&&client.includes('refundResaleCreditV330')&&client.includes('combinedResaleSettlementV330'),'credit actions remain available in their dedicated section');
ok(server.includes("/api/v338/excavator/buyers/:id/resale-refunds"),'legacy and pooled resale refunds can be displayed together');
ok(client.includes('v338-posting-status-row')&&client.includes('row.appendChild(status)'),'Accounting status controls are moved outside collapsible filter body');
ok(client.includes('v338ToggleFilters')&&client.includes('v338-collapsible-filter-body'),'Finance/Accounting filters are collapsible and responsive');
ok(client.includes('filterState338')&&client.includes('restoreFilter338'),'filter values are preserved across UI refreshes');
ok(client.includes('token_new_receiver_is_default')&&client.includes('checked'),'new-supplier inline receiver account defaults intelligently');
ok(client.includes('tokenRefreshBefore338')&&client.includes("accounts338('excavator_supplier'"),'Buy Machine existing supplier receiver selector actively restores default account');
ok(v326.includes("require('../public/settlement-v338')")&&v326.includes('calculateExcavatorSaleSettlementV338'),'sale backend uses the shipped shared settlement calculator');
ok(client.includes('BOMSettlementV338')&&client.includes('salePlan338'),'sale browser UI uses the same shipped settlement calculator');
let p=calc({salePrice:15000,currentAllocated:0,settlementMode:'replace',paymentSource:'advance_plus_new',availableAdvance:10000,requestedAdvance:10000,paymentAmountOriginal:5000,paymentCurrency:'KRW',buyerExists:true,paymentMethod:'Bank',paymentDate:'2026-09-18',paymentReference:'T1',hasEvidence:true,validatePaymentFields:true,requireMethod:true,requireDate:true,requireReference:true,requireEvidence:true});
ok(p.valid&&p.advanceUsedKrw===10000&&p.newPaymentRequiredKrw===5000&&p.resultingOutstandingKrw===0,'₩15,000 sale + ₩10,000 advance correctly requires ₩5,000 new payment');
p=calc({salePrice:15000,currentAllocated:0,settlementMode:'replace',paymentSource:'advance_plus_new',availableAdvance:10000,requestedAdvance:10000,paymentAmountOriginal:4000,paymentCurrency:'KRW',buyerExists:true,paymentMethod:'Bank',paymentDate:'2026-09-18',paymentReference:'T2',hasEvidence:true,validatePaymentFields:true,requireMethod:true,requireDate:true,requireReference:true,requireEvidence:true});
ok(!p.valid&&p.resultingOutstandingKrw===1000&&p.errors.some(x=>/short/i.test(x)),'short new payment is rejected consistently');
p=calc({salePrice:15000,currentAllocated:15000,settlementMode:'keep',paymentSource:'new_payment',paymentAmountOriginal:0,paymentCurrency:'KRW',buyerExists:true,validatePaymentFields:true});
ok(p.valid&&p.coverageRequiredKrw===0,'unchanged fully-settled sale can keep existing settlement');
p=calc({salePrice:17000,currentAllocated:15000,settlementMode:'keep',paymentSource:'new_payment',paymentAmountOriginal:0,paymentCurrency:'KRW',buyerExists:true,validatePaymentFields:true});
ok(!p.valid&&p.coverageRequiredKrw===2000,'price increase cannot keep an insufficient old settlement');
ok(client.includes('liveValidation')&&client.includes('setCustomValidity'),'Sell Machine required fields/shortfalls update dynamically');
ok(client.includes('newPaymentRequiredKrw')&&client.includes('buyerCreditAddedKrw')&&client.includes('resultingOutstandingKrw'),'Sell Machine shows one canonical dependent-value set');
ok(client.includes('closeModal(true)')&&client.includes('refreshParentSelectors338'),'account child dialog returns to parent and refreshes Paid To selectors');
ok(server.includes('usage_count')||server.includes('usageCount'),'account management reports historical usage without destructive deletion');
ok(['Edit Account','Add Receiver Account','Account History','Pakistan → Korea Bank Transfers','New Payment Required','Show Filters','Hide Filters'].every(x=>ko.includes(`'${x}':`)),'V30.38 user-facing additions have Korean localization');
console.log(`\nV30.38 requirement QA: ${pass}/${pass} PASS`);
