'use strict';
const assert=require('assert'),{DatabaseSync}=require('node:sqlite'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),db=new DatabaseSync(':memory:');db.transaction=fn=>(...args)=>{db.exec('BEGIN');try{const v=fn(...args);db.exec('COMMIT');return v}catch(e){db.exec('ROLLBACK');throw e}};
db.exec(`CREATE TABLE business_units(id INTEGER PRIMARY KEY,status TEXT);INSERT INTO business_units VALUES(1,'Active');
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,journal_no TEXT,source_type TEXT,source_id INTEGER,status TEXT,finance_entry_id INTEGER,reversal_of_id INTEGER,business_unit_id INTEGER,created_by INTEGER);
CREATE TABLE accounting_journal_lines(id INTEGER PRIMARY KEY,journal_entry_id INTEGER,account_id INTEGER,debit_krw REAL,credit_krw REAL);
CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,code TEXT,name TEXT,account_type TEXT,active INTEGER);
CREATE TABLE finance_entries(id INTEGER PRIMARY KEY,verification_status TEXT,status TEXT,cash_effect INTEGER);
CREATE TABLE accounting_financing_v356(id INTEGER PRIMARY KEY,business_unit_id INTEGER,agreement_no TEXT,status TEXT,financing_type TEXT,currency TEXT,opening_principal REAL,start_date TEXT);
CREATE TABLE accounting_financing_funding_v356(id INTEGER PRIMARY KEY,financing_id INTEGER,amount_krw REAL);
CREATE TABLE accounting_financing_repayments_v356(id INTEGER PRIMARY KEY,financing_id INTEGER,principal_krw REAL,finance_entry_id INTEGER);
INSERT INTO accounting_accounts VALUES(1,'1500','Lease asset','Asset',1),(2,'2200','Lease payable','Liability',1),(3,'6600','Depreciation','Expense',1),(4,'1599','Accumulated depreciation','Asset',1);
INSERT INTO accounting_financing_v356 VALUES(1,1,'LEASE-1','Active','Equipment Lease','KRW',1000,'2026-01-01'),(2,1,'LOAN-2','Active','Bank Loan','KRW',800,'2026-01-01');`);
const routes=[];let generated=0,financeCreated=0;const app={get:(u,...handlers)=>routes.push(['GET',u,handlers.at(-1)]),post:(u,...handlers)=>routes.push(['POST',u,handlers.at(-1)])};
const accounting={isPeriodClosed:()=>false,postJournal({sourceType,sourceId,lines,businessUnitId,createdBy}){generated++;assert(Math.abs(lines.reduce((n,l)=>n+(l.debit_krw||0)-(l.credit_krw||0),0))<.005);const jid=db.prepare('INSERT INTO accounting_journal_entries(journal_no,source_type,source_id,status,business_unit_id,created_by) VALUES(?,?,?,?,?,?)').run('J-'+generated,sourceType,sourceId,'Pending Review',businessUnitId,createdBy).lastInsertRowid;for(const l of lines)db.prepare('INSERT INTO accounting_journal_lines(journal_entry_id,account_id,debit_krw,credit_krw) VALUES(?,?,?,?)').run(jid,l.account_id,l.debit_krw||0,l.credit_krw||0);return Number(jid)}};
require('../server/v356-finalization').install({app,db,auth:()=>{},allow:()=>()=>{},currentUnit:()=>1,enforceUnit:()=>true,audit:()=>{},accounting,hasAccess:()=>false});
const route=(method,end)=>{const x=routes.find(x=>x[0]===method&&x[1].endsWith(end));assert(x,method+' '+end);return x[2]};
const invoke=(fn,body={},id=1,role='CEO / Owner')=>{let res={code:200,body:null};fn({params:{id},body,user:{id:9,role}}, {status(n){res.code=n;return this},json(x){res.body=x;return this}});return res};
const init=route('POST','/lease-commencement'),depr=route('POST','/lease-depreciation'),opening=route('POST','/link-opening-journal'),recon=route('GET','/liability-reconciliation');
const start={recognition_date:'2026-01-01',asset_krw:1000,liability_krw:1000,approved_policy:'Approved policy memo',approval_reference:'BOARD-7',asset_account_id:1,liability_account_id:2};
let r=invoke(init,start,1,'Staff');assert.equal(r.code,403);
r=invoke(init,{...start,asset_krw:900});assert.equal(r.code,400);assert.equal(generated,0);
r=invoke(init,start);assert.equal(r.code,201,JSON.stringify(r));assert.equal(generated,1);const jid=r.body.journal_id;
r=invoke(init,start);assert.equal(r.code,409);assert.equal(generated,1);
const dep={period_end:'2026-02-28',amount_krw:100,approved_policy:'Approved policy memo',approval_reference:'BOARD-7',expense_account_id:3,accumulated_depreciation_account_id:4};
r=invoke(depr,dep);assert.equal(r.code,409,'Cannot depreciate unposted commencement');db.prepare("UPDATE accounting_journal_entries SET status='Posted' WHERE id=?").run(jid);
r=invoke(depr,dep);assert.equal(r.code,201,JSON.stringify(r));assert.equal(generated,2);r=invoke(depr,dep);assert.equal(r.code,409);
r=invoke(recon);assert.equal(r.code,200);assert.equal(r.body.operational_outstanding_krw,1000);assert.equal(r.body.source_linked_reconciled,true,JSON.stringify(r.body));
db.prepare('INSERT INTO accounting_journal_entries(id,journal_no,source_type,status,business_unit_id) VALUES(?,?,?,?,?)').run(99,'OPEN-99','Opening Balance','Posted',1);
db.prepare('INSERT INTO accounting_journal_lines(journal_entry_id,account_id,debit_krw,credit_krw) VALUES(?,?,?,?)').run(99,2,0,800);
r=invoke(opening,{journal_entry_id:99,liability_account_id:2,migration_reference:'MIG-2026'},2);assert.equal(r.code,201,JSON.stringify(r));assert.equal(generated,2);
r=invoke(recon,{},2);assert.equal(r.body.source_linked_reconciled,true,JSON.stringify(r.body));
r=invoke(opening,{journal_entry_id:99,liability_account_id:2,migration_reference:'MIG-2026'},2);assert.equal(r.code,409);
assert.equal(financeCreated,0);assert(!fs.readFileSync(path.join(root,'server/v356-finalization.js'),'utf8').includes('INSERT INTO finance_entries'));
for(const file of ['server/v356-finalization.js','server/v356-financing.js','server/v318.js','public/v356-accounting.js','server/server.js'])require('vm').createScript(fs.readFileSync(path.join(root,file),'utf8'),{filename:file});
console.log('PASS V30.56.5 finalization: roles, invalid measurement, duplicate initiation/month, posted initiation gate, balanced proposals, opening journal one-to-one, source reconciliation, no synthetic Finance, source syntax.');
