const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const base=read('public/client.js'),v319=read('public/v319-client.js'),v318=read('public/v318-client.js'),v3241=read('public/v3241-client.js'),v331=read('public/v331-client.js'),server=read('server/server.js'),s318=read('server/v318.js'),s331=read('server/v331.js');
let fails=0; const out=[];
function check(name,ok){out.push(`${ok?'PASS':'FAIL'} ${name}`); if(!ok)fails++;}
check('Add Supplier Save button is wired to saveExcavatorSupplier',base.includes('onsubmit="saveExcavatorSupplier(event,')&&base.includes('Save Supplier'));
check('Supplier Save closes the dialog after success',/async function saveExcavatorSupplier[\s\S]{0,1200}closeModalAfterSave\(\)/.test(base));
check('Supplier Save refreshes supplier list after success',/async function saveExcavatorSupplier[\s\S]{0,1200}await excavatorSuppliers\(\)/.test(base));
check('Finance verification lifecycle action button calls V30.31 handler',v331.includes('b.onclick=()=>window.voidFinanceV331(id)'));
check('Finance lifecycle button is state-driven by action policy',v331.includes("policy331(id)")&&s331.includes("/api/v331/finance/:id/action-policy"));
check('Finance Void/Reversal requires impact review and reason',v331.includes('impactDetails(p')&&v331.includes("reasonAction({title:p.action_label")&&v331.includes("method:'DELETE'"));
check('Finance Void/Reversal has matching backend endpoint',s331.includes("app.delete('/api/finance/:id'"));
check('Correct & Resubmit form is wired to saveFinanceCorrection',v3241.includes('onsubmit="saveFinanceCorrection(event,')&&v3241.includes('Save & Resubmit'));
check('Correct & Resubmit submits source-aware Finance PUT',v3241.includes("multipartApi('/api/finance/'+financeId")&&v3241.includes("method:'PUT'"));
check('Correct & Resubmit has matching V30.31 backend endpoint',s331.includes("app.put('/api/finance/:id'"));
check('Machine cost active row exposes Edit',v319.includes('onclick="excavatorAddCost(${assetId},${x.id})">Edit</button>'));
check('Machine cost active row exposes controlled Void',v319.includes('onclick="deleteExcavatorCostV319(${assetId},${x.id})">Void</button>')&&v331.includes('window.deleteExcavatorCostV319=async function'));
check('Voided machine cost remains visible with status instead of action buttons',v319.includes("voided?'<span class=\"pill bad\">Voided</span>'"));
check('Machine cost Void has matching controlled backend route',server.includes("app.delete('/api/excavator/assets/:id/transactions/:txid'"));
check('Supplier payment form offers Purchase only',v319.includes('<select name="payment_type"><option>Purchase</option></select>'));
check('Supplier payment Save button remains wired',v319.includes('onsubmit="saveExcavatorPayment(event,${id})"')&&v319.includes('Save Payment'));
check('Supplier payment server rejects non-Purchase types',server.includes("Only Purchase supplier payments are supported")||server.includes("payment_type!=='Purchase'")||server.includes("paymentType!=='Purchase'"));
check('Accounting Posting Queue Open button is wired',v318.includes('onclick="postingOpenV318(${x.id})"'));
check('Posting Review Final Post button is wired and gated by readiness',v318.includes('onclick="postingFinalV318(${j.id}')&&v318.includes("${ready?'':`disabled"));
check('Final Post has matching backend route',s318.includes("/api/accounting/posting-control/:id/post"));
check('Posting correction/cancel buttons remain wired',v318.includes('postingCorrectionV318(${j.id})')&&v318.includes('postingCancelV318(${j.id})'));
check('One-navigation cleanup hides duplicate Back/X workflow controls',v331.includes('v331-single-navigation')&&v331.includes('v331-duplicate-nav')&&v331.includes('closeWorkflowPageV324'));
check('Posted lifecycle uses Request Reversal label',s331.includes('Request Reversal')&&v331.includes("p.action_label==='Request Reversal'"));
check('Unavailable lifecycle actions do not render a dead action button',v331.includes('if(p?.can_request)')&&v331.includes('Action unavailable'));
console.log(out.join('\n'));
console.log(`\nV30.31 BUTTON / ACTION STATIC AUDIT ${fails?'FAILED':'PASS'}${fails?`: ${fails} check(s)`:''}`);
process.exit(fails?1:0);
