const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const srv=read('server/v367-pink-operational-completion.js');
const main=read('server/server.js');
const ui=read('public/v367-pink-operational-completion.js');
const runtime=read('public/runtime-v30392.js');
const v313=read('server/v313.js');
const html=read('public/index.html');
const v366=read('server/v366-pink-product-master.js');
const checks=[];
checks.push(['V30.67 server module wired',main.includes('v367-pink-operational-completion')]);
checks.push(['V30.67 client loaded',html.includes('/v367-pink-operational-completion.js?v=30.67.0')]);
checks.push(['Core Pink Salt runtime cache bumped',html.includes('runtime-v30392.js?v=30.67.0')]);
checks.push(['True family table exists',srv.includes('pink_salt_product_families')&&srv.includes("addCol('pink_salt_products','family_id'")]);
checks.push(['Variant code/order are persisted',srv.includes('variant_code')&&srv.includes('variant_sort_order')&&ui.includes('Variant Code')]);
checks.push(['Existing product family text migrates non-destructively',srv.includes('ensureFamilies')&&srv.includes('INSERT OR IGNORE INTO pink_salt_product_families')]);
checks.push(['Product save persists V30.66 catalog plus V30.67 variant model',runtime.includes('/api/v366/pink-salt/products/')&&runtime.includes('/api/v367/pink-salt/products/')]);
checks.push(['Variant-specific product images remain supported',v366.includes('pink_salt_product_images')&&v366.includes('product_id INTEGER NOT NULL')]);
checks.push(['Finished-lot table exists',srv.includes('pink_salt_finished_lots')&&srv.includes('production_batch_id')]);
checks.push(['Lot allocations exist',srv.includes('pink_salt_finished_lot_allocations')&&srv.includes("allocation_method TEXT NOT NULL DEFAULT 'FEFO'")]);
checks.push(['FEFO lot ordering implemented',srv.includes("ORDER BY CASE WHEN l.best_before_date IS NULL OR l.best_before_date='' THEN 1 ELSE 0 END,l.best_before_date,l.production_date,l.id")]);
checks.push(['Completed sales reconcile lot allocations',v313.includes('__bomV367PinkLots')&&v313.includes('reconcileOrderLots')]);
checks.push(['Order trace reaches raw import sources',srv.includes('raw_sources')&&srv.includes('pink_salt_production_inputs')&&srv.includes('pink_salt_imports')]);
checks.push(['Expiry/lot manager UI exists',ui.includes('psLotsV367')&&ui.includes('Expiring Soon')&&ui.includes('Quality Status')]);
checks.push(['Customer classification implemented',srv.includes('/customers/:id/kind')&&ui.includes('customer_kind_v367')]);
checks.push(['Address edit/default implemented',srv.includes('/addresses/:id/default')&&ui.includes('psAddressDefaultV367')&&ui.includes('Edit Address')]);
checks.push(['Fulfillment status visible in Sales list',runtime.includes("<th>${tr('Fulfillment Status')}</th>")]);
checks.push(['Pricing hierarchy is explicit',srv.includes('/pricing-hierarchy/:productId')&&ui.includes('psPricingHierarchyV367')]);
checks.push(['Dashboard attention center implemented',srv.includes('/pink-salt/attention')&&ui.includes('Attention Center')]);
checks.push(['Sidebar is grouped by Pink Salt workflow',runtime.includes("['PURCHASING'")&&runtime.includes("['INVENTORY & PRODUCTION'")&&runtime.includes("['COMMERCE'")]);
checks.push(['Location balance foundation retained',srv.includes('/pink-salt/location-balances')&&srv.includes('pink_salt_storage_locations')]);
checks.push(['Commerce remains channel agnostic',!srv.includes('Coupang')&&!srv.includes('Naver')&&!srv.includes('Amazon')]);
checks.push(['No destructive schema reset',!srv.match(/DROP\s+TABLE|DELETE\s+FROM\s+pink_salt_products/i)]);
checks.push(['Shared Blue Ocean UI primitives reused',ui.includes('section-title')&&ui.includes('card')&&ui.includes('table-wrap')&&ui.includes('actions')]);
let fail=0;
for(const [name,ok] of checks){console.log(`${ok?'PASS':'FAIL'} ${name}`);if(!ok)fail++}
console.log(`\nV30.67 Pink Salt operational completion QA: ${checks.length-fail}/${checks.length} passed`);
process.exit(fail?1:0);
