'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const c=read('public/v3382-client.js'),index=read('public/index.html'),pkg=JSON.parse(read('package.json')),lock=JSON.parse(read('package-lock.json')),main=read('server/server.js'),v300=read('server/v300.js'),v305=read('server/v305.js'),v330=read('server/v330.js'),v3381=read('public/v3381-client.js'),v3242=read('public/v3242-client.js');
let pass=0;function ok(x,m){assert.ok(x,m);pass++;console.log('PASS',String(pass).padStart(2,'0'),m)}
ok(pkg.version==='30.38.2'&&lock.version==='30.38.2'&&lock.packages?.['']?.version==='30.38.2','patch release identity is V30.38.2');
ok(main.includes("version:'30.38.2'")&&main.includes('Blue Ocean Market V30.38.2 running on port'),'health/startup identity is V30.38.2');
ok(index.includes('/v3381-client.js?v=30.38.2')&&index.includes('/v3382-client.js?v=30.38.2')&&index.indexOf('/v3381-client.js?v=30.38.2')<index.indexOf('/v3382-client.js?v=30.38.2'),'V30.38.2 loads after protected V30.38.1 overlay');
ok(c.includes("const VERSION='30.38.2'"),'V30.38.2 browser overlay identifies the point release');
ok(c.includes('v3382-account-picker')&&c.includes('v3382-picker-menu'),'Token Payment replaces fragile native pointer UI with interaction-safe picker');
ok(c.includes('v3382-native-account-select')&&c.includes("sel.dispatchEvent(new Event('change',{bubbles:true}))"),'real select remains form truth and receives normal change events');
ok(c.includes('closePickers382')&&c.includes('aria-expanded'),'custom account lists have stable open/close state');
ok(c.includes("data-v3382-manage-payee")&&c.includes("removeAttribute('data-v332-manage-payee')"),'Buy Machine Manage button is detached from conflicting legacy click route');
ok(c.includes("openCounterpartyAccountsV338")&&c.includes("stopImmediatePropagation"),'Manage button routes directly to final shared counterparty account manager');
ok(c.includes('window.v332RefreshTokenAccounts=async function')&&c.includes('enhanceBuyAccounts382'),'underlying V30.38.1 async account loading is preserved and picker resynchronizes after refresh');
ok(v3381.includes('Promise.allSettled([companyP,supplierP])')&&v3381.includes('prefetchBuy381'),'V30.38.1 parallel/prefetch slow-connection account loading remains protected');
ok(c.includes('Refund settlement')&&c.includes('KRW Equivalent / Advance Deduction')&&c.includes('Remaining After Refund'),'shared refund settlement summary shows before/refund/KRW/remaining values');
ok(c.includes("balanceCurrency==='KRW'?krw:amount"),'KRW advance/credit balances deduct only the KRW equivalent while PKR resale credit remains PKR-native');
ok(c.includes("p.fx.disabled=krwCur")&&c.includes("if(krwCur)p.fx.value='1'"),'KRW refunds lock FX to 1 while foreign refund currencies require FX');
ok(c.includes('f.dataset.accountCurrency=currency')&&c.includes('v320RefreshPaymentAccount'),'refund currency drives Company Pay From account filtering');
ok(c.includes("txt(a.currency||'KRW').toUpperCase()===currency"),'buyer Paid To accounts are filtered to Refund Currency');
ok(main.includes('Paid To account currency must match Refund Currency')&&main.includes('Pay From account currency must match Refund Currency'),'Excavator buyer refund backend enforces both Pay From and Paid To currency match');
ok(v300.includes('Pay From account currency must match Refund Currency'),'Pink Salt customer cash-refund source account enforces Refund Currency');
ok(v305.includes('Pay From account currency must match Refund Currency'),'Pink Salt supplier advance-refund source account enforces Refund Currency');
ok(v330.includes("currency:'PKR'")&&v330.includes('Paid To account currency must match Refund Currency'),'Pakistan resale pooled refunds enforce PKR buyer destination account');
ok(c.includes('armModalAction382')&&c.includes("document.addEventListener('submit'"),'system-wide modal success lifecycle arms from actual modal form submissions');
ok(c.includes("!['GET','HEAD','OPTIONS'].includes(method)")&&c.includes('scheduleModalClose382')&&c.includes('state.pending'),'modal lifecycle closes only after all successful mutating API work settles');
ok(c.includes('catch(e){if(mutating&&state){')&&c.includes('cancelModalClose382()'),'failed API actions cancel auto-close and leave dialog available for correction');
ok(c.includes('window.closeModalAfterSave')&&v3242.includes('restoreParent()'),'successful child close uses nested-dialog-safe parent restoration');
ok(c.includes('sameOriginal')&&c.includes('sameAction'),'auto-close never blindly closes an unrelated modal opened after the action');
ok(c.includes('v3382-processing-chip')&&c.includes("t('Processing…')"),'modal mutations show protected processing state');
ok(c.includes('v3382-cost-list')&&c.includes('max-height:285px')&&c.includes('overflow-y:auto'),'Machine Costs entries use a bounded scroll viewport');
ok(c.includes("card.querySelector(':scope > .row.total')")&&c.includes('card.appendChild(total)'),'Total machine cost remains outside/below the scrollable entries list');
ok(c.includes('v3382-locked-edit')&&c.includes('disabled title=')&&c.includes("🔒 ${esc(t('Edit'))}"),'large yellow cost lock is replaced by compact disabled lock/Edit control');
ok(c.includes('v3382-cost-row .v319-cost-actions')&&c.includes('margin-left:auto')&&c.includes('justify-content:flex-end'),'Machine Cost Edit/Void actions align to the right');
ok(c.includes("replace(/<span class=\"v335-cost-locked\"")&&c.includes('v3382-locked-edit'),'legacy yellow lock pill is actively removed from locked cost rows');
ok(c.includes("'Refund Currency':'환불 통화'")&&c.includes("'Processing…':'처리 중…'"),'new refund/modal states are Korean localized');
ok(!main.includes('DROP TABLE counterparty_payment_account_history')&&!v300.includes('DROP TABLE')&&!v305.includes('DROP TABLE'),'V30.38.2 introduces no destructive refund/account migration');
console.log(`\nV30.38.2 patch QA: ${pass}/${pass} PASS`);
