const fs=require('fs');
const client=fs.readFileSync('public/client.js','utf8');
const server=fs.readFileSync('server/server.js','utf8');
const db=fs.readFileSync('server/db.js','utf8');
const html=fs.readFileSync('public/index.html','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
let fail=0;function check(name,ok){console.log((ok?'PASS ':'FAIL ')+name);if(!ok)fail++}
check('version 27.4.0',pkg.version==='27.4.0'&&server.includes("version:'27.4.0'")&&html.includes('client.js?v=27.4.0'));
check('CRM removed from sidebar',!client.match(/\['crm','CRM'/));
check('KPIs removed from sidebar',!client.match(/\['kpi','KPIs'/));
check('Business Units CEO consolidated only',client.includes("key==='businesses')return me.role==='CEO / Owner'&&!selectedUnitId"));
check('notification close X',client.includes('onclick="closeNotifDialog()">✕'));
check('notification bell toggles close',client.includes("if(document.getElementById('notifDialog')){closeNotifDialog();return}"));
check('notification outside click close',client.includes('if(e.target===wrap)closeNotifDialog()'));
check('notification Escape close',client.includes("if(e.key==='Escape')"));
check('only one toggleNotifs definition',(client.match(/async function toggleNotifs\(/g)||[]).length===1);
check('app history back forward',client.includes('function appBack()')&&client.includes('function appForward()')&&client.includes("window.addEventListener('popstate'"));
check('breadcrumbs',client.includes('function breadcrumbHtml()')&&client.includes('app-crumbs'));
check('view state restore',client.includes('captureViewState')&&client.includes('restoreViewState'));
check('unsaved changes protection',client.includes('You have unsaved changes'));
check('near-real-time polling',client.includes('V27.4 near-real-time visible-data synchronization'));
check('mutation sync still present',client.includes("method!=='GET'&&method!=='HEAD'")&&client.includes('scheduleDataSync'));
check('finance control center',client.includes('Finance Control Center')&&client.includes('Pending Verification')&&client.includes('Corrections / Voids'));
check('finance source evidence view',client.includes('Source & Evidence')&&client.includes('Open Source Record'));
check('finance direct receipt',client.includes('View Receipt')&&client.includes('Missing Evidence'));
check('finance transaction timeline',client.includes('Transaction Timeline')&&server.includes('function financeTimeline'));
check('finance detail API',server.includes("app.get('/api/finance/:id/detail'"));
check('finance rejection reason mandatory',server.includes('A rejection / correction reason is required'));
check('verified records locked',server.includes('Verified finance entries are locked'));
check('finance change request approval',server.includes("app.post('/api/finance/:id/request-change'")&&server.includes("actionKey:'finance.verified_change'"));
check('finance unique source scoped by unit',server.includes('business_unit_id=? AND source_type=? AND source_id=?'));
check('finance source index unit scoped',db.includes('idx_finance_unit_source_v274'));
check('finance original currency fields',db.includes("['finance_entries','original_currency'")&&client.includes('Original Currency'));
check('manual finance currency FX',client.includes('FX Rate to KRW')&&server.includes('originalAmount')&&server.includes('original_currency'));
check('buyer payment finance original currency',server.includes("sourceLabel:'Excavator → Buyer Payment'"));
check('sale finance source update preserved',server.includes("sourceType:'Excavator Sale'")&&server.includes('resetVerification:isUpdate'));
check('Docker production host',server.includes("app.listen(PORT,'0.0.0.0'"));
process.exit(fail?1:0);
