const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
let pass=0,fail=0;
function check(name,cond){if(cond){pass++;console.log('PASS',name)}else{fail++;console.error('FAIL',name)}}
const server=read('server/server.js'),reg=read('server/v361-platform-registry.js'),client=read('public/client.js'),pkg=JSON.parse(read('package.json'));
check('registry foundation retained in current release',Number(String(pkg.version).split('.')[1]||0)>=61);
check('registry module installed',server.includes("require('./v361-platform-registry').install"));
check('module registry table',reg.includes('CREATE TABLE IF NOT EXISTS platform_modules'));
check('entity registry table',reg.includes('CREATE TABLE IF NOT EXISTS platform_entities'));
check('capability registry table',reg.includes('platform_entity_capabilities'));
check('generic related records',reg.includes('platform_related_records'));
check('meeting multi-BU junction',reg.includes('meeting_business_units'));
check('task scope junction',reg.includes('task_business_units'));
check('existing meetings backfilled',reg.includes('SELECT id,business_unit_id FROM meetings'));
check('existing tasks backfilled',reg.includes('SELECT id,business_unit_id FROM tasks'));
check('registry API',reg.includes("app.get('/api/platform/registry'"));
check('related-record API',reg.includes("app.post('/api/platform/related'"));
check('meeting supports Multi-BU',server.includes("'Multi-BU'"));
check('meeting supports Company-wide',server.includes("'Company-wide'"));
check('meeting unit scope persisted',server.includes('syncMeetingUnits'));
check('meeting task relation registered',server.includes("'Source Meeting'"));
check('ordinary tasks register scope',server.includes("INSERT OR IGNORE INTO task_business_units(task_id,business_unit_id)"));
check('meeting UI multi-BU selector',client.includes('meeting_unit_pick'));
check('meeting UI company-wide option',client.includes("['Company-wide']"));
check('meeting save avoids full loadView',client.includes("if(view==='meetings'&&c)await meetings(c)"));
check('old primary business_unit compatibility retained',server.includes('business_unit_id=?,meeting_type=?'));
console.log(`\nV30.61 source QA: ${pass} passed, ${fail} failed`);
if(fail)process.exit(1);
