const fs=require('fs');
const path=require('path');
let pass=0,fail=0;
function ok(name,cond){if(cond){pass++;console.log('PASS',name)}else{fail++;console.error('FAIL',name)}}
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'public/v363-dialog-processing.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
ok('release version is 30.63.0',pkg.version==='30.63.0');
ok('V30.63 script loaded last',html.includes('/v363-dialog-processing.js?v=30.63.0')&&html.indexOf('/v362-collaboration.js')<html.indexOf('/v363-dialog-processing.js')&&html.lastIndexOf('<script src=')===html.indexOf('<script src="/v363-dialog-processing.js'));
ok('root processing portal used',/document\.getElementById\('processingRoot'\)/.test(js));
ok('root overlay is fixed full screen',/\.bom363-global-processing\{position:fixed;inset:0/.test(js));
ok('processing layer exceeds modal layers',/2147483600/.test(js));
ok('serious mutations include POST PUT PATCH DELETE via non-read method classification',/\['GET','HEAD','OPTIONS'\]\.includes\(method\)/.test(js));
ok('request object method supported',/opt\.method\|\|url\?\.method/.test(js));
ok('trivial notification mutations excluded',/api\\\/notifications/.test(js));
ok('legacy modal payment overlay suppressed during root processing',/bom353-payment-overlay/.test(js)&&/body\.bom363-processing/.test(js));
ok('legacy modal processing chip suppressed',/v3382-processing-chip/.test(js));
ok('legacy scoped progress suppressed',/\.bom345-progress/.test(js));
ok('network banner suppressed during serious processing',/#bomNetworkState/.test(js));
ok('application roots are inert during serious processing',/el\.inert=true/.test(js));
ok('Escape blocked during serious processing',/e\.key==='Escape'/.test(js));
ok('modal close is guarded during serious processing',/guardedClose/.test(js));
ok('before unload protection present',/beforeunload/.test(js));
ok('sticky terminal action class provided',/bom363-sticky-actions/.test(js));
ok('modal terminal actions use sticky bottom',/position:sticky!important;bottom:-1px!important/.test(js));
ok('small dialogs retain natural layout',/Only force scrolling when the dialog actually needs it/.test(js));
ok('shared MutationHub used when available',/BOMMutationHub\.register\('v363-sticky-dialog-actions'/.test(js));
ok('no finance/accounting server logic changed by V30.63 layer',!/(ledger|journal_entries|posting_control).*INSERT/i.test(js));
console.log(`\nV30.63 dialog/processing QA: ${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
