'use strict';
const assert=require('assert'),{DatabaseSync}=require('node:sqlite'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),db=new DatabaseSync(':memory:');db.transaction=fn=>(...args)=>{db.exec('BEGIN');try{const v=fn(...args);db.exec('COMMIT');return v}catch(e){db.exec('ROLLBACK');throw e}};
db.exec(`CREATE TABLE business_units(id INTEGER PRIMARY KEY,status TEXT);INSERT INTO business_units VALUES(1,'Active');
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,journal_no TEXT,source_type TEXT,source_id INTEGER,status TEXT,finance_entry_id INTEGER,reversal_of_id INTEGER,business_unit_id INTEGER,created_by INTEGER);
CREATE TABLE accounting_journal_lines(id INTEGER PRIMARY KEY,journal_entry_id INTEGER,account_id INTEGER,debit_krw REAL,credit_krw REAL);
CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,code TEXT,name TEXT,account_type TEXT,active INTEGER);
CREATE TABLE finance_entries(id INTEGER PRIMARY KEY,verification_status TEXT,status TEXT,cash_effect INTEGER);
CREATE TABLE accounting_financing_v356(id INTEGER PRIMARY KEY,business_unit_id INTEGER,agreement_no TEXT,status TEXT,financing_type TEXT,currency TEXT,opening_principal REAL,start_date TEXT);
CREATE TABLE accounting_financing_funding_v356(id INTEGER PRIMARY KEY,financing_id INTEGER,amount_krw REAL);
CREATE TABLE accounting_financing_repayments_v356(id INTEGER PRIMARY KEY,financing_id INTEGER,principal_krw REAL,finance_entry_id INTEGER);
INSERT INTO accounting_accounts VALUES(1,'1500','Lease asset','Asset',1),(2,'2200','Lease payable','Liability',1),(3,'6600','Depreciation','Expense',1),(4,'1599','Accumulated depreciation','Asset',1);
INSERT INTO accounting_financing_v356 VALUES(1,1,'LEASE-1','Active','Equipment Lease','KRW',1000,'2026-01-01'),(2,1,'LOAN-2','Active','Bank Loan','KRW',800,'2026-01-01');`);
const routes=[];let generated=0,financeCreated=0;const app={get:(u,...handlers)=>routes.push(['GET',u,handlers.at(-1)]),post:(u,...handlers)=>routes.push(['POST',u,handlers.at(-1)])};
const accounting={isPeriodClosed:()=>false,postJournal({sourceType,sourceId,lines,businessUnitId,createdBy}){generated++;assert(Math.abs(lines.reduce((n,l)=>n+(l.debit_krw||0)-(l.credit_krw||0),0))<.005);const jid=db.prepare('INSERT INTO accounting_journal_entries(journal_no,source_type,source_id,status,business_unit_id,created_by) VALUES(?,?,?,?,?,?)').run('J-'+generated,sourceType,sourceId,'Pending Review',businessUnitId,createdBy).lastInsertRowid;for(const l of lines)db.prepare('INSERT INTO accounting_journal_lines(journal_entry_id,account_id,debit_krw,credit_krw) VALUES(?,?,?,?)').run(jid,l.account_id,l.debit_krw||0,l.credit_krw||0);return Number(jid)}};
require('../server/v356-finalization').install({app,db,auth:()=>{},allow:()=>()=>{},currentUnit:()=>1,enforceUnit:()=>true,audit:()=>{},accounting,hasAccess:()=>false});
const route=(method,end)=>{const x=routes.find(x=>x[0]===method&&x[1].endsWith(end));assert(x,method+' '+end);return x[2]};
const invoke=(fn,body={},id=1,role='CEO / Owner')=>{let res={code:200,body:null};fn({params:{id},body,user:{id:9,role}}, {status(n){res.code=n;return this},json(x){res.body=x;return this}});return res};
const init=route('POST','/lease-commencement'),depr=route('POST','/lease-depreciation'),close=route('POST','/close-settled-lease'),status=route('GET','/lease-closure-status');
const req={recognition_date:'2026-01-01',asset_krw:1000,liability_krw:1000,approved_policy:'Board-approved lease policy',approval_reference:'BOARD-001',asset_account_id:1,liability_account_id:2};
let r=invoke(init,req);assert.equal(r.code,201,JSON.stringify(r));
const closing={closure_date:'2026-09-25',lender_reference:'LENDER-CLEARANCE-001',approved_policy:'Accountant-approved lease closure',accumulated_depreciation_account_id:4};
r=invoke(close,closing);assert.equal(r.code,409);assert.equal(generated,1);
db.prepare("UPDATE accounting_journal_entries SET status='Posted' WHERE id=1").run();
r=invoke(depr,{period_end:'2026-09-25',amount_krw:1000,approved_policy:'Board-approved lease policy',approval_reference:'BOARD-001',expense_account_id:3,accumulated_depreciation_account_id:4});assert.equal(r.code,201,JSON.stringify(r));
r=invoke(close,closing);assert.equal(r.code,409,'No closure with unposted depreciation');db.prepare("UPDATE accounting_journal_entries SET status='Posted' WHERE id=2").run();
db.exec("ALTER TABLE finance_entries ADD COLUMN verification_status_x TEXT");
db.prepare('INSERT INTO finance_entries(id,verification_status,status,cash_effect) VALUES(?,?,?,?)').run(30,'Verified / Correct','Recorded',-1);
db.prepare('INSERT INTO accounting_financing_repayments_v356(id,financing_id,principal_krw,finance_entry_id) VALUES(?,?,?,?)').run(7,1,1000,30);
r=invoke(close,closing);assert.equal(r.code,409,'No closure without posted repayment classification');
db.prepare('INSERT INTO accounting_journal_entries(id,journal_no,source_type,source_id,status,business_unit_id) VALUES(?,?,?,?,?,?)').run(40,'REP-40','Financing Repayment Reclassification',7,'Posted',1);
r=invoke(status);assert.equal(r.code,200,JSON.stringify(r));assert.equal(r.body.ready_for_accounting_review,true);
r=invoke(close,closing,'1','Staff');assert.equal(r.code,403);
r=invoke(close,closing);assert.equal(r.code,201,JSON.stringify(r));assert.equal(r.body.no_cash_movement,true);assert.equal(r.body.requires_posting_control,true);assert.equal(generated,3);
r=invoke(close,closing);assert.equal(r.code,409);assert.equal(generated,3);
assert.equal(db.prepare('SELECT COUNT(*) n FROM finance_entries').get().n,1);
const last=db.prepare("SELECT id,status FROM accounting_journal_entries WHERE source_type='Financing Lease Closure'").get();assert.equal(last.status,'Pending Review');
assert.deepEqual(db.prepare('SELECT account_id,debit_krw,credit_krw FROM accounting_journal_lines WHERE journal_entry_id=? ORDER BY account_id').all(last.id),[{account_id:1,debit_krw:0,credit_krw:1000},{account_id:4,debit_krw:1000,credit_krw:0}]);
console.log('PASS V30.56.8 lease closure: permissions, unposted guards, exact principal, zero new Finance movement, balanced cash-neutral proposal and duplicate rejection.');
