'use strict';
const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const db=new DatabaseSync(':memory:');
db.exec(`CREATE TABLE excavator_assets(id INTEGER PRIMARY KEY,business_unit_id INTEGER,asset_no TEXT,status TEXT,purchase_price REAL,selling_price REAL);
CREATE TABLE excavator_transactions(id INTEGER PRIMARY KEY,asset_id INTEGER,type TEXT,status TEXT);
CREATE TABLE pink_salt_imports(id INTEGER PRIMARY KEY,business_unit_id INTEGER,import_no TEXT,status TEXT);
CREATE TABLE pink_salt_import_items(id INTEGER PRIMARY KEY,import_id INTEGER,line_amount_krw REAL);
CREATE TABLE pink_salt_import_costs(id INTEGER PRIMARY KEY,import_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE pink_salt_import_payments(id INTEGER PRIMARY KEY,import_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE pink_salt_supplier_advances(id INTEGER PRIMARY KEY,status TEXT);
CREATE TABLE pink_salt_supplier_advance_allocations(id INTEGER PRIMARY KEY,import_id INTEGER,advance_id INTEGER,amount_krw REAL,status TEXT);
CREATE TABLE pink_salt_production_batches(id INTEGER PRIMARY KEY,business_unit_id INTEGER,batch_no TEXT,status TEXT);
CREATE TABLE pink_salt_production_inputs(id INTEGER PRIMARY KEY,production_batch_id INTEGER,input_weight_kg REAL,raw_unit_cost_krw REAL);
CREATE TABLE pink_salt_production_packaging(id INTEGER PRIMARY KEY,production_batch_id INTEGER,quantity_used REAL,unit_cost_krw REAL);
CREATE TABLE pink_salt_production_outputs(id INTEGER PRIMARY KEY,production_batch_id INTEGER,quantity_units REAL,unit_cost_krw REAL);
CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,system_key TEXT);
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,business_unit_id INTEGER,source_type TEXT,source_id INTEGER,status TEXT);
CREATE TABLE accounting_journal_lines(id INTEGER PRIMARY KEY,journal_entry_id INTEGER,account_id INTEGER,business_unit_id INTEGER,entity_type TEXT,entity_id INTEGER,debit_krw REAL,credit_krw REAL);
INSERT INTO excavator_assets VALUES(1,1,'EX-1','Sold',800,1200),(2,2,'EX-PRIVATE','Sold',500,900);
INSERT INTO excavator_transactions VALUES(1,1,'Local Sale','Completed');
INSERT INTO pink_salt_imports VALUES(1,1,'IM-1','Received'),(2,1,'IM-2','Received');
INSERT INTO pink_salt_import_items VALUES(1,1,700),(2,2,400);
INSERT INTO pink_salt_production_batches VALUES(1,1,'B-1','Completed'),(2,1,'B-2','Completed');
INSERT INTO pink_salt_production_inputs VALUES(1,1,10,10),(2,2,5,10);
INSERT INTO pink_salt_production_packaging VALUES(1,1,2,5);
INSERT INTO pink_salt_production_outputs VALUES(1,1,9,10);
INSERT INTO accounting_accounts VALUES(1,'EXCAVATOR_INVENTORY'),(2,'EXCAVATOR_COGS'),(3,'EXCAVATOR_SALES_REVENUE'),(4,'PINK_SALT_IN_TRANSIT'),(5,'PINK_SALT_RAW_INVENTORY'),(6,'PINK_SALT_PACKAGING_INVENTORY'),(7,'PINK_SALT_FINISHED_INVENTORY'),(8,'PINK_SALT_WASTE_EXPENSE');
INSERT INTO accounting_journal_entries VALUES(1,1,'Machine Sale',1,'Posted'),(2,1,'Pink Salt Import Commitment',1,'Posted'),(3,1,'Pink Salt Import Receipt',1,'Posted'),(4,1,'Pink Salt Production',1,'Posted'),(5,1,'Pink Salt Production',2,'Pending Review');
INSERT INTO accounting_journal_lines(journal_entry_id,account_id,business_unit_id,entity_type,entity_id,debit_krw,credit_krw) VALUES
 (1,1,1,'Machine',1,800,800),(1,2,1,'Machine',1,800,0),(1,3,1,'Machine',1,0,1200),
 (2,4,1,'Pink Salt Import',1,700,0),(3,4,1,'Pink Salt Import',1,0,700),(3,5,1,'Pink Salt Import',1,700,0),
 (4,5,1,'Pink Salt Import',1,0,100),(4,6,1,'Pink Salt Production',1,0,10),(4,7,1,'Pink Salt Production',1,90,0),(4,8,1,'Pink Salt Production',1,20,0),
 (5,7,1,'Pink Salt Production',2,50,0);`);
db.exec(`ALTER TABLE pink_salt_import_items ADD COLUMN salt_grade TEXT DEFAULT 'Fine';
ALTER TABLE pink_salt_import_items ADD COLUMN received_weight_kg REAL DEFAULT 0;
ALTER TABLE pink_salt_import_items ADD COLUMN landed_cost_krw REAL DEFAULT 0;
ALTER TABLE pink_salt_production_inputs ADD COLUMN import_item_id INTEGER DEFAULT 1;
CREATE TABLE pink_salt_raw_stock_movements(id INTEGER PRIMARY KEY,business_unit_id INTEGER,import_item_id INTEGER,movement_type TEXT,quantity_kg REAL);
UPDATE pink_salt_import_items SET received_weight_kg=70,landed_cost_krw=700 WHERE id=1;
UPDATE pink_salt_import_items SET landed_cost_krw=400 WHERE id=2;
INSERT INTO pink_salt_import_payments VALUES(1,1,300,'Active');
INSERT INTO pink_salt_supplier_advances VALUES(1,'Active');
INSERT INTO pink_salt_supplier_advance_allocations VALUES(1,1,1,200,'Active');
INSERT INTO pink_salt_raw_stock_movements VALUES(1,1,1,'Import Receipt',70),(2,1,1,'Production Issue',-10);
UPDATE pink_salt_production_inputs SET import_item_id=1;
UPDATE accounting_journal_lines SET entity_id=1 WHERE journal_entry_id=4 AND account_id=5;`);
const routes=new Map(),app={get:(path,...handlers)=>routes.set(path,handlers.at(-1))};
require('../server/v357-inventory-review').install({app,db,auth:()=>{},allow:()=>()=>{},currentUnit:r=>r.selected_business_unit_id,enforceUnit:(r,bu)=>r.user.role==='CEO / Owner'||bu===r.user.business_unit_id});
function read(kind,role='BU Manager',bu=1,extra={}){let status=200,payload;const res={status:n=>(status=n,res),json:x=>payload=x};routes.get('/api/accounting/v357-inventory-review')({query:{kind,...extra},user:{role,business_unit_id:bu},selected_business_unit_id:role==='CEO / Owner'?0:bu},res);return {status,payload}}
let r=read('machine');assert.equal(r.status,200,r.payload.error);assert.equal(r.payload.total,1);assert.equal(r.payload.rows[0].korea_machine_trading_profit_krw,400);assert.equal(r.payload.rows[0].pakistan_resale_profit_share_krw,null);assert.deepEqual(r.payload.rows[0].flags,[]);
r=read('import');assert.equal(r.payload.total,2);assert.deepEqual(r.payload.rows[0].flags,['IMPORT_RECEIPT_NOT_POSTED']);assert.equal(r.payload.rows[1].posted_in_transit_krw,0);assert.equal(r.payload.rows[1].posted_raw_receipt_krw,700);assert.equal(r.payload.rows[1].active_supplier_advance_allocated_krw,200);assert.equal(r.payload.rows[1].operational_purchase_outstanding_krw,200);
r=read('batch');assert.equal(r.payload.rows[0].flags.includes('BATCH_CONVERSION_NOT_POSTED'),true);assert.equal(r.payload.rows[0].flags.includes('BATCH_JOURNAL_PENDING_REVIEW'),true);assert.equal(r.payload.rows[1].posted_raw_issued_krw,100);assert.equal(r.payload.rows[1].posted_loss_krw,20);assert.deepEqual(r.payload.rows[1].flags,['PRODUCTION_LOSS_POLICY_REVIEW']);
r=read('raw_lot');assert.equal(r.status,200,r.payload.error);assert.equal(r.payload.rows[1].operational_balance_kg,60);assert.equal(r.payload.rows[1].posted_raw_issued_krw,100);assert.equal(r.payload.rows[1].flags.includes('RAW_LOT_POSTED_ISSUE_DIFFERS'),true);
db.exec('UPDATE pink_salt_raw_stock_movements SET quantity_kg=-80 WHERE id=2');r=read('raw_lot');assert.equal(r.payload.rows[1].flags.includes('RAW_LOT_NEGATIVE_STOCK'),true);
db.exec("INSERT INTO pink_salt_import_costs VALUES(1,1,50,'Active');UPDATE pink_salt_supplier_advance_allocations SET amount_krw=500 WHERE id=1");r=read('import');assert.equal(r.payload.rows[1].flags.includes('IMPORT_LANDED_COST_DIFFERS_FROM_SOURCE'),true);assert.equal(r.payload.rows[1].flags.includes('IMPORT_PURCHASE_OVER_ALLOCATED'),true);
db.exec(`CREATE TABLE pink_salt_packaging_items(id INTEGER PRIMARY KEY,business_unit_id INTEGER,sku TEXT,active INTEGER);
CREATE TABLE pink_salt_packaging_movements(id INTEGER PRIMARY KEY,business_unit_id INTEGER,packaging_item_id INTEGER,movement_type TEXT,quantity REAL,unit_cost_krw REAL,status TEXT);
CREATE TABLE pink_salt_products(id INTEGER PRIMARY KEY,business_unit_id INTEGER,sku TEXT,active INTEGER,packaging_style TEXT);
CREATE TABLE pink_salt_finished_stock_movements(id INTEGER PRIMARY KEY,business_unit_id INTEGER,product_id INTEGER,movement_type TEXT,quantity_units REAL);
CREATE TABLE pink_salt_gift_box_components(id INTEGER PRIMARY KEY,product_id INTEGER,salt_grade TEXT,pouches_per_box REAL);
CREATE TABLE pink_salt_bom_lines(id INTEGER PRIMARY KEY,product_id INTEGER,packaging_item_id INTEGER,quantity_per_unit REAL);
ALTER TABLE pink_salt_production_packaging ADD COLUMN packaging_item_id INTEGER DEFAULT 1;
ALTER TABLE pink_salt_production_outputs ADD COLUMN product_id INTEGER DEFAULT 1;
INSERT INTO pink_salt_packaging_items VALUES(1,1,'PACK-1',1);
INSERT INTO pink_salt_packaging_movements VALUES(1,1,1,'Purchase Receipt',20,5,'Active'),(2,1,1,'Production Issue',-2,5,'Active');
INSERT INTO pink_salt_products VALUES(1,1,'FIN-1',1,'Retail Pack'),(2,1,'GIFT-1',1,'Gift Box');
INSERT INTO pink_salt_finished_stock_movements VALUES(1,1,1,'Production Output',9);
INSERT INTO pink_salt_production_batches VALUES(3,1,'B-WIP','Draft');
INSERT INTO pink_salt_production_inputs(id,production_batch_id,input_weight_kg,raw_unit_cost_krw,import_item_id) VALUES(3,3,2,10,1);
INSERT INTO accounting_journal_entries VALUES(6,1,'Pink Salt Packaging Purchase',1,'Posted');
INSERT INTO accounting_journal_lines(journal_entry_id,account_id,business_unit_id,entity_type,entity_id,debit_krw,credit_krw) VALUES(6,6,1,'Pink Salt Packaging',1,100,0);`);
r=read('packaging');assert.equal(r.status,200,r.payload.error);assert.equal(r.payload.rows[0].operational_balance_quantity,18);assert.equal(r.payload.rows[0].posted_purchase_krw,100);
r=read('finished');assert.equal(r.status,200,r.payload.error);assert.equal(r.payload.rows.find(x=>x.reference==='FIN-1').operational_balance_units,9);
r=read('wip');assert.equal(r.status,200,r.payload.error);assert.equal(r.payload.rows.length,1);assert.equal(r.payload.rows[0].flags.includes('WIP_OPERATIONAL_COST_NOT_GL_MAPPED'),true);
r=read('gift_box');assert.equal(r.status,200,r.payload.error);assert.equal(r.payload.rows[0].flags.includes('GIFT_BOX_COMPONENTS_MISSING'),true);
assert.equal(read('machine','CEO / Owner',0).payload.total,2);assert.equal(read('bad').status,400);assert.equal(read('machine','BU Manager',0).status,403);
assert.equal(db.prepare('SELECT COUNT(*) n FROM accounting_journal_entries').get().n,6);assert.equal(db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE name='finance_entries'").get().n,0);
console.log('PASS inventory source/posted GL review, BU scope, pending exclusion, separate trading profit and no mutations');
