'use strict';
const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');const db=new DatabaseSync(':memory:');
db.exec(`CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,code TEXT,name TEXT,account_type TEXT,active INTEGER,allow_manual INTEGER,system_key TEXT);
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,status TEXT,business_unit_id INTEGER,transaction_date TEXT,finance_entry_id INTEGER,reversal_of_id INTEGER);
CREATE TABLE accounting_journal_lines(id INTEGER PRIMARY KEY,journal_entry_id INTEGER,account_id INTEGER,business_unit_id INTEGER,debit_krw REAL,credit_krw REAL);
CREATE TABLE accounting_inter_unit_transfers(id INTEGER PRIMARY KEY,transfer_no TEXT,from_business_unit_id INTEGER,to_business_unit_id INTEGER,amount_krw REAL,journal_entry_id INTEGER,transfer_date TEXT);
INSERT INTO accounting_accounts VALUES(1,'1500','Due From','Asset',1,0,'INTER_BU_RECEIVABLE'),(2,'2300','Due To','Liability',1,0,'INTER_BU_PAYABLE');
INSERT INTO accounting_journal_entries VALUES(10,'Posted',NULL,'2026-02-01',NULL,NULL),(11,'Pending Review',NULL,'2026-02-02',NULL,NULL),(12,'Posted',NULL,'2026-02-03',NULL,NULL);
INSERT INTO accounting_journal_lines(journal_entry_id,account_id,business_unit_id,debit_krw,credit_krw) VALUES(10,1,1,500,0),(10,2,2,0,500),(11,1,1,200,0),(11,2,2,0,200),(12,1,1,300,0),(12,2,2,0,250);
INSERT INTO accounting_inter_unit_transfers VALUES(1,'IB-1',1,2,500,10,'2026-02-01'),(2,'IB-2',1,2,200,11,'2026-02-02'),(3,'IB-3',1,2,300,12,'2026-02-03');`);
const routes=new Map(),app={get:(p,...handlers)=>routes.set(p,handlers.at(-1)),post:()=>{}};let selected=0,role='CEO / Owner';
require('../server/v357-realworld').install({app,db,auth:()=>{},allow:()=>()=>{},currentUnit:()=>selected,enforceUnit:()=>true,audit:()=>{},accounting:{},hasAccess:()=>false});
function read(asOf='2026-02-28'){let status=200,payload;const res={status:n=>(status=n,res),json:x=>payload=x};routes.get('/api/accounting/inter-bu-elimination-preview-v357')({query:{as_of:asOf},user:{id:1,role}},res);return {status,payload}};
let r=read();assert.equal(r.status,200,r.payload.error);assert.equal(r.payload.preview.debit_due_to_krw,500);assert.equal(r.payload.preview.credit_due_from_krw,500);assert.equal(r.payload.exceptions.length,2);
assert.equal(read('2026-01-31').payload.preview.debit_due_to_krw,0);
selected=1;assert.equal(read().status,403);selected=0;role='BU Manager';assert.equal(read().status,403);role='CEO / Owner';
db.prepare("INSERT INTO accounting_journal_entries(id,status,business_unit_id,transaction_date,reversal_of_id) VALUES(20,'Posted',NULL,'2026-02-04',10)").run();r=read();assert.equal(r.payload.preview.debit_due_to_krw,0);
assert.equal(db.prepare('SELECT COUNT(*) n FROM accounting_journal_entries').get().n,4);assert.equal(db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE name='finance_entries'").get().n,0);
console.log('PASS posted paired transfer preview excludes pending/mismatched/reversed sources, is CEO scoped and read-only');
