'use strict';
const assert=require('node:assert/strict'),Database=require('better-sqlite3'),db=new Database(':memory:');
db.exec(`CREATE TABLE excavator_assets(id INTEGER PRIMARY KEY,asset_no TEXT,business_unit_id INTEGER,status TEXT,purchase_price REAL,selling_price REAL);
CREATE TABLE pink_salt_imports(id INTEGER PRIMARY KEY,import_no TEXT,business_unit_id INTEGER,supplier_id INTEGER,status TEXT,invoice_currency TEXT,purchase_date TEXT,expected_arrival TEXT);
CREATE TABLE pink_salt_import_items(import_id INTEGER,line_amount_krw REAL,landed_cost_krw REAL);
CREATE TABLE pink_salt_import_costs(import_id INTEGER,krw_amount REAL,status TEXT);
CREATE TABLE pink_salt_import_payments(import_id INTEGER,krw_amount REAL,status TEXT,payment_date TEXT);
CREATE TABLE pink_salt_supplier_advance_allocations(import_id INTEGER,amount_krw REAL,status TEXT,allocation_date TEXT);
CREATE TABLE pink_salt_packaging_movements(id INTEGER PRIMARY KEY,reference TEXT,business_unit_id INTEGER,supplier_id INTEGER,movement_type TEXT,status TEXT,movement_date TEXT,due_date TEXT,quantity REAL,unit_cost_krw REAL);
CREATE TABLE pink_salt_supplier_packaging_allocations(packaging_movement_id INTEGER,amount_krw REAL,status TEXT,allocation_date TEXT);
CREATE TABLE pink_salt_production_batches(id INTEGER PRIMARY KEY,batch_no TEXT,business_unit_id INTEGER,production_date TEXT,status TEXT);
CREATE TABLE pink_salt_production_inputs(production_batch_id INTEGER,input_weight_kg REAL,raw_unit_cost_krw REAL);
CREATE TABLE pink_salt_production_packaging(production_batch_id INTEGER,quantity_used REAL,unit_cost_krw REAL);
CREATE TABLE pink_salt_production_outputs(production_batch_id INTEGER,quantity_units REAL,unit_cost_krw REAL);
CREATE TABLE pink_salt_products(id INTEGER PRIMARY KEY,sku TEXT,name TEXT,business_unit_id INTEGER,active INTEGER);
CREATE TABLE pink_salt_orders(id INTEGER PRIMARY KEY,status TEXT,order_no TEXT,business_unit_id INTEGER,customer_id INTEGER,customer_name TEXT,order_date TEXT,due_date TEXT,total_krw REAL,prepaid_applied_krw REAL);CREATE TABLE pink_salt_customer_payments(id INTEGER PRIMARY KEY,order_id INTEGER,status TEXT,payment_role TEXT,payment_date TEXT,krw_amount REAL);CREATE TABLE pink_salt_customer_receipt_allocations(id INTEGER PRIMARY KEY,order_id INTEGER,receipt_id INTEGER,status TEXT,amount_krw REAL);CREATE TABLE pink_salt_customer_receipts(id INTEGER PRIMARY KEY,status TEXT,payment_date TEXT);CREATE TABLE pink_salt_customer_refunds(order_id INTEGER,status TEXT,refund_date TEXT,krw_amount REAL);
CREATE TABLE pink_salt_order_items(product_id INTEGER,order_id INTEGER,line_total_krw REAL,line_cost_krw REAL);
CREATE TABLE pink_salt_finished_stock_movements(product_id INTEGER,quantity_units REAL);
CREATE TABLE accounting_accounts(id INTEGER PRIMARY KEY,system_key TEXT,code TEXT,name TEXT,account_type TEXT);
CREATE TABLE finance_entries(id INTEGER PRIMARY KEY,source_type TEXT,source_id INTEGER);
CREATE TABLE accounting_journal_entries(id INTEGER PRIMARY KEY,transaction_date TEXT,status TEXT,source_type TEXT,source_id INTEGER,finance_entry_id INTEGER);
CREATE TABLE accounting_journal_lines(journal_entry_id INTEGER,account_id INTEGER,business_unit_id INTEGER,entity_type TEXT,entity_id INTEGER,debit_krw REAL,credit_krw REAL);
INSERT INTO excavator_assets VALUES(1,'M-1',1,'Sold',60,100),(2,'M-2',2,'Sold',600,1000);
INSERT INTO pink_salt_imports VALUES(1,'I-1',1,1,'Received','USD','2026-08-01','2026-08-20');
INSERT INTO pink_salt_import_items VALUES(1,70,80);
INSERT INTO pink_salt_import_costs VALUES(1,10,'Active');
INSERT INTO pink_salt_import_payments VALUES(1,20,'Active','2026-09-01');
INSERT INTO pink_salt_supplier_advance_allocations VALUES(1,10,'Active','2026-09-02');
INSERT INTO pink_salt_packaging_movements VALUES(1,'PACK-1',1,1,'Purchase Receipt','Active','2026-08-01','2026-08-20',5,5);
INSERT INTO pink_salt_supplier_packaging_allocations VALUES(1,5,'Active','2026-09-03');
INSERT INTO pink_salt_production_batches VALUES(1,'B-1',1,'2026-09-10','Completed');
INSERT INTO pink_salt_production_inputs VALUES(1,5,4);
INSERT INTO pink_salt_production_packaging VALUES(1,2,5);
INSERT INTO pink_salt_production_outputs VALUES(1,3,10);
INSERT INTO pink_salt_products VALUES(1,'S-1','Pouch',1,1);
INSERT INTO pink_salt_orders VALUES(1,'Completed','O-1',1,1,'Customer 1','2026-08-01','2026-08-20',100,0);INSERT INTO pink_salt_customer_receipts VALUES(1,'Active','2026-09-01');INSERT INTO pink_salt_customer_receipt_allocations VALUES(1,1,1,'Active',40);
INSERT INTO pink_salt_order_items VALUES(1,1,50,30);
INSERT INTO pink_salt_finished_stock_movements VALUES(1,3);
INSERT INTO accounting_accounts VALUES(1,'EXCAVATOR_SALES_REVENUE','4000','Sale','Revenue'),(2,'EXCAVATOR_COGS','5000','Cost','Expense'),(3,'PINK_SALT_FINISHED_INVENTORY','1290','Finished','Asset'),(4,'ACCOUNTS_RECEIVABLE','1100','AR','Asset');
INSERT INTO finance_entries VALUES(1,'Pink Salt Sale',1);
INSERT INTO accounting_journal_entries VALUES(1,'2026-09-12','Posted','Sale',1,NULL),(2,'2026-09-13','Pending Review','Sale',1,NULL),(3,'2026-09-10','Posted','Pink Salt Production',1,NULL),(4,'2026-08-01','Posted','Finance Entry',1,1),(5,'2026-09-01','Posted','Pink Salt Customer Receipt Allocation',1,NULL);
INSERT INTO accounting_journal_lines VALUES(1,1,1,'Machine',1,0,100),(1,2,1,'Machine',1,60,0),(1,4,1,'Excavator Buyer',3,100,0),(4,4,1,'Pink Salt Customer',1,100,0),(5,4,1,'Pink Salt Order',1,0,40),(2,1,1,'Machine',1,0,1000),(3,3,1,'Batch',1,30,0);`);
const routes=new Map(),app={get:(p,...args)=>routes.set(p,args.at(-1))},auth=()=>{},allow=()=>auth;
require('../server/v358-management-detail').install({app,db,auth,allow,currentUnit:r=>r.selected_business_unit_id,enforceUnit:(r,bu)=>r.user.role==='CEO / Owner'||r.user.business_unit_id===bu});
function get(kind,bu=1,role='BU Manager',asOf='2026-09-30'){let status=200,data;const res={status:x=>(status=x,res),json:x=>(data=x,res)};routes.get('/api/accounting/v358/management-detail')({query:{kind,as_of:asOf},user:{role,business_unit_id:bu},selected_business_unit_id:bu},res);return {status,data}}
let r=get('machine');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.total,1);assert.equal(r.data.rows[0].posted_korea_profit_krw,40);assert.equal(r.data.rows[0].posted_revenue_krw,100);
r=get('import');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.rows[0].source_landed_krw,80);assert.equal(r.data.rows[0].flags.length,0);
r=get('batch');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.rows[0].posted_finished_krw,30);assert.equal(r.data.rows[0].source_raw_krw,20);
r=get('sku');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.rows[0].posted_sku_profit_krw,null);assert.equal(r.data.rows[0].source_gross_margin_krw,20);
r=get('aging');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.rows[0].net_exposure_krw,100);
r=get('expense');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.rows[0].posted_expense_krw,60);
r=get('invoice_aging');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.rows[0].source_outstanding_krw,60);assert.equal(r.data.rows[0].posted_receivable_krw,60);assert.equal(r.data.rows[0].aging_bucket,'31-60');
r=get('supplier_invoice_aging');assert.equal(r.status,200,r.data?.error);assert.equal(r.data.total,2);assert.equal(r.data.rows[0].source_outstanding_krw,40);assert.equal(r.data.rows[1].source_outstanding_krw,20);assert.equal(r.data.rows[0].posted_invoice_payable_krw,null);assert.equal(get('supplier_invoice_aging',2).data.total,0);
r=get('supplier_invoice_aging',1,'BU Manager','2026-08-25');assert.equal(r.data.rows[0].source_outstanding_krw,70);assert.equal(r.data.rows[1].source_outstanding_krw,25);
db.exec("INSERT INTO pink_salt_customer_payments VALUES(1,1,'Active','Sale Payment','2026-09-02',10);INSERT INTO finance_entries VALUES(2,'Pink Salt Customer Payment',1);INSERT INTO accounting_journal_entries VALUES(6,'2026-09-02','Posted','Finance Entry',2,2);INSERT INTO accounting_journal_lines VALUES(6,4,1,'Pink Salt Customer',1,0,10)");
r=get('invoice_aging');assert.equal(r.data.rows[0].source_outstanding_krw,50);assert.equal(r.data.rows[0].posted_receivable_krw,50);assert.equal(r.data.rows[0].difference_krw,0);
db.exec("INSERT INTO accounting_journal_entries VALUES(7,'2026-09-02','Posted','Manual Journal',NULL,NULL);INSERT INTO accounting_journal_lines VALUES(7,4,1,'Pink Salt Customer',1,5,0)");
assert.equal(get('invoice_aging').data.rows[0].posted_receivable_krw,50,'Unlinked customer-level adjustments must not be assigned to an invoice');
assert.equal(get('machine',2).data.total,1);assert.equal(get('machine',1,'CEO / Owner').data.total,1);db.close();console.log('PASS V30.58 paged source/GL machine, import, batch, SKU, expense and exposure reports; pending exclusion and BU scope');
