'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..');let pass=0,fail=0;
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const check=(name,ok,detail='')=>{if(ok){pass++;console.log('PASS',name)}else{fail++;console.error('FAIL',name,detail)}};
const pkg=JSON.parse(read('package.json')),lock=JSON.parse(read('package-lock.json')),html=read('public/index.html'),base=read('public/client.js'),runtime=read('public/runtime-v30392.js'),v337=read('public/v337-client.js'),v3391=read('public/v3391-client.js'),server=read('server/server.js'),prog=read('server/v3391-progressive.js'),req=read('REQUIREMENTS_MASTER.md');
check('V30.39.1 progressive foundation retained in release 30.39.2',pkg.version==='30.39.2'&&lock.version==='30.39.2'&&lock.packages?.['']?.version==='30.39.2'&&server.includes("version:'30.39.2'")&&server.includes('Blue Ocean Market V30.39.2 running on port'));
check('qa:v3391 registered',pkg.scripts['qa:v3391']==='node qa/qa_v3391_progressive.js');
check('live browser remains three scripts',(html.match(/<script\s+src=/g)||[]).length===3);
check('V30.39.1 runtime behavior retained inside V30.39.2 runtime',html.includes('/runtime-v30392.js?v=30.39.2')&&runtime.includes('===== v3391-client.js =====')&&runtime.indexOf('===== v339-client.js =====')<runtime.indexOf('===== v3391-client.js ====='));
for(const f of ['public/i18n-ko.js','public/client.js','public/runtime-v30392.js']){const gz=f+'.gz';check(`${gz} exists`,fs.existsSync(path.join(root,gz)));if(fs.existsSync(path.join(root,gz)))check(`${gz} smaller`,fs.statSync(path.join(root,gz)).size<fs.statSync(path.join(root,f)).size)}
check('generic view shell paints immediately',base.includes("window.BOMProgressive?.viewShell?.(view)"));
check('boot me/context/access parallelized',base.includes("Promise.all([api('/api/me'),api('/api/context'),api('/api/access/me')])"));
check('business units and pnl parallelized',base.includes("Promise.all([api('/api/business-units'),api('/api/pnl')])"));
check('progressive skeleton states',v3391.includes('bom-skeleton')&&v3391.includes('sectionHtml')&&v3391.includes('errorHtml')&&v3391.includes('prefers-reduced-motion'));
check('shared parallel/lazy/cache primitives',v3391.includes('async function runParallel')&&v3391.includes('function visibleLater')&&v3391.includes('async function cachedApi')&&v3391.includes('function invalidate'));
check('successful mutations invalidate progressive caches',v3391.includes('const progressiveFetch=window.fetch.bind(window)')&&v3391.includes("!['GET','HEAD','OPTIONS'].includes(method)")&&v3391.includes("invalidate('')"));
check('machine page is server paged',v3391.includes("paged:'1'")&&v3391.includes("'/api/excavator/assets?'")&&v3391.includes('pageSize:String(machineState.size)'));
check('buyer page is server paged',v3391.includes("'/api/excavator/buyers?'")&&v3391.includes('pageSize:String(buyerList.size)'));
check('supplier page is server paged',v3391.includes("'/api/excavator/suppliers?'")&&v3391.includes('pageSize:String(supplierList.size)'));
check('server V30.39.1 performance module installed before legacy routes',server.includes("require('./v3391-progressive').install")&&server.indexOf("require('./v3391-progressive').install")<server.indexOf("app.get('/api/excavator/overview'"));
check('summary-only Excavator overview supported',prog.includes("include_assets||'1')!=='0'")&&v3391.includes("/api/excavator/overview?include_assets=0"));
check('overview aggregate runs in SQL',prog.includes('COALESCE(SUM(total_cost),0) totalCost')&&prog.includes('FROM snapshots`).get(b)'));
check('machine paging uses SQL LIMIT/OFFSET and window total',prog.includes('COUNT(*) OVER() __total')&&prog.includes('LIMIT ? OFFSET ?'));
const db=read('server/db.js');
check('V30.39.1 query-path indexes included',db.includes('idx_exc_tx_v3391_asset_type_status')&&db.includes('idx_exc_pay_v3391_asset_type_status')&&db.includes('idx_exc_supplier_machines_v3391_supplier_status')&&db.includes('idx_exc_buyer_payments_v3391_buyer_status'));
check('three legacy-compatible paged intercepts',(prog.match(/String\(req\.query\.paged\|\|''\)!=='1'/g)||[]).length===3);
const buyerProfileBlock=server.slice(server.indexOf("app.get('/api/excavator/buyers/:id'"),server.indexOf("app.post('/api/excavator/buyers/:id/payments'"));
check('buyer profile requirements use persisted match counts',buyerProfileBlock.includes("FROM excavator_requirement_matches m WHERE m.requirement_type='Buyer'")&&!/buyerRequirementMatches\(r,b\)\.length/.test(buyerProfileBlock));
check('supplier requirements use persisted match counts',server.includes("FROM excavator_requirement_matches m WHERE m.requirement_type='Supplier'")&&!/supplierRequirementMatches\(r,s\)\.length/.test(server));
check('buyer receiver accounts removed from initial critical path',v337.includes("Promise.resolve(api('/api/excavator/buyers/'+id))")&&v337.includes("if(active==='accounts')ensureBuyerAccounts337(id)"));
check('supplier secondary sections lazy by key',v337.includes("supplierNeeded337(active)")&&v337.includes("key==='requirements'")&&v337.includes("key==='accounts'"));
check('supplier profile core reads can run concurrently',v337.includes("for(const k of required)ensureSupplier337(id,k)"));
check('section-level retry exists',v337.includes('v337RetrySupplierSection')&&v337.includes('v337RetryBuyerSection'));
check('permanent progressive carry-forward rule',req.includes('Progressive loading, parallel reads & section resilience — V30.39.1+ permanent rule')&&req.includes('Independent read requests start concurrently')&&req.includes('The user should not need to repeat these rules'));
check('permanent smart context-aware impact rule',req.includes('Smart context-aware change & impact-control standard')&&req.includes('Never implement a requirement blindly')&&req.includes('smallest correct scope')&&req.includes('Preserve unrelated behavior and context')&&req.includes('Data/query changes require result-equivalence checks')&&req.includes('AI-assisted development follows the same rule'));
const syntax=['server/server.js','server/v3391-progressive.js','public/client.js','public/v337-client.js','public/v3391-client.js','public/runtime-v30392.js','qa/qa_v3391_progressive.js'];
for(const f of syntax){const r=cp.spawnSync(process.execPath,['--check',path.join(root,f)],{encoding:'utf8'});check('syntax '+f,r.status===0,r.stderr)}
console.log(`\nV30.39.1 retained-foundation QA in V30.39.2: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
