'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),zlib=require('node:zlib'),cp=require('node:child_process');const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');const server=read('server/v357-realworld.js'),layout=read('public/v357-accounting-workspace.js'),overview=read('public/v356-accounting.js'),html=read('public/index.html');let count=0;
function test(n,f){f();count++;console.log('PASS '+n)}
test('versions aligned',()=>{const version=require('../package.json').version;assert.equal(require('../package-lock.json').version,version);assert(read('server/server.js').includes("version:'"+version+"'"));assert(html.includes('?v='+version))});
test('existing six-group navigation and dedicated real-world pages',()=>{for(const s of ['Overview','Accounts & Ledgers','Money & Balances','Financial Reports','Accounting Control','Accounting Setup'])assert(layout.includes("['"+s+"'"));assert(layout.includes("['Fixed Assets','fixed']"));assert(layout.includes("['Accruals & Prepayments','expenses']"));assert(html.includes('/v357-fixed-assets.js'));assert(html.includes('/v357-expenses.js'))});
test('posted-only actual data for graphs and source-based cash trend',()=>{assert(server.includes("j.status IN ('Posted','Reversed')"));assert(server.includes("a.subtype='Cash & Bank'"));assert(overview.includes("api('/api/accounting/posted-trends-v357')"));assert(overview.includes('v357-trend-chart'));assert(overview.includes('v357-trend-svg'));assert(!overview.includes('Illustrative figures'))});
test('no new Finance entries and no direct posting',()=>{assert(!server.includes('INSERT INTO finance_entries'));assert(!server.includes("postingStatus:'Posted'"));assert(server.includes("'Pending Review'"));assert(server.includes("hasAccess?.(req.user.id,'sensitive.accounting_adjustments'"))});
test('asset controls and duplicate guards',()=>{assert(server.includes('source_journal_id INTEGER NOT NULL UNIQUE'));assert(server.includes('UNIQUE(asset_id,event_type,period)'));assert(server.includes('existing posted, unreversed cash-neutral same-unit'));assert(server.includes('expense_account_id'));assert(server.includes('isPeriodClosed'))});
test('expense controls and source uniqueness',()=>{assert(server.includes('idx_prepaid_unique_source_v357'));assert(server.includes('UNIQUE(business_unit_id,kind,reference)'));assert(server.includes('pending_amortization_krw'));assert(server.includes('selected original expense line')===false);assert(server.includes('Selected original expense line'))});
for(const f of ['server/v357-realworld.js','server/server.js','public/v356-accounting.js','public/v357-accounting-workspace.js','public/v357-fixed-assets.js','public/v357-expenses.js'])test('syntax '+f,()=>{const r=cp.spawnSync(process.execPath,['--check',path.join(root,f)],{encoding:'utf8'});assert.equal(r.status,0,r.stderr)});
for(const f of ['v356-accounting.js','v357-accounting-workspace.js','v357-fixed-assets.js','v357-expenses.js'])test('compressed asset matches '+f,()=>assert.equal(zlib.gunzipSync(fs.readFileSync(path.join(root,'public',f+'.gz'))).toString(),read('public/'+f)));
console.log('V30.57.2 consolidated source gate PASS: '+count+' checks. Live Render QA not performed.');
