'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'blue-ocean-v341-access-')),data=path.join(temp,'data'),uploads=path.join(temp,'uploads');fs.mkdirSync(data);fs.mkdirSync(uploads);
const port=35300+Math.floor(Math.random()*500),password='BO-'+crypto.randomBytes(12).toString('base64url')+'!9a',secret=crypto.randomBytes(48).toString('hex');
const env={...process.env,PORT:String(port),JWT_SECRET:secret,ADMIN_EMAIL:'admin@blueocean.local',ADMIN_PASSWORD:password,LOCAL_TEST_MODE:'true',LOCAL_TEST_ADMIN_EMAIL:'admin@blueocean.local',LOCAL_TEST_ADMIN_PASSWORD:password,NODE_ENV:'development',DATA_DIR:data,UPLOAD_DIR:uploads,SEED_DEMO_USERS:'false',SEED_DEMO_DATA:'false'};
const child=cp.spawn(process.execPath,['server/server.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let output='',done=false;child.stdout.on('data',d=>{output+=d;process.stdout.write(d)});child.stderr.on('data',d=>{output+=d;process.stderr.write(d)});const sleep=ms=>new Promise(r=>setTimeout(r,ms));const fail=(m,o)=>{throw new Error(m+(o?': '+JSON.stringify(o):''))};
(async()=>{try{
  for(let i=0;i<180;i++){if(output.includes('running on port'))break;if(child.exitCode!==null)fail('Server exited before startup');await sleep(100)}
  const base=`http://127.0.0.1:${port}`;let r=await fetch(base+'/api/health'),health=await r.json();if(!r.ok||health.version!=='30.41.0')fail('V30.41 health failed',health);console.log('PASS V30.41 runtime health');
  r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@blueocean.local',password})});const login=await r.json();if(!r.ok||!login.token)fail('CEO login failed',login);const auth={Authorization:'Bearer '+login.token},get=async p=>{const x=await fetch(base+p,{headers:auth}),j=await x.json();if(!x.ok)fail('GET '+p,j);return j},json=async(method,p,body)=>{const x=await fetch(base+p,{method,headers:{...auth,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let j={};try{j=await x.json()}catch(_){};return {x,j}};
  const ov=await get('/api/access/admin-v341/overview');if(!ov.can_manage_library)fail('CEO cannot manage Access Control Center',ov);console.log('PASS Access Control Center overview');
  const units=await get('/api/business-units'),profiles=(await get('/api/access/profiles')).filter(x=>x.role_name!=='CEO / Owner');if(!units.length||profiles.length<2)fail('Need BUs/profiles',{units:units.length,profiles:profiles.length});const bu=units[0];
  const catalog=await get('/api/access/catalog');if(!catalog.modules.includes('dashboard'))fail('Permission catalog missing dashboard');
  const suffix=Date.now()+'-'+Math.floor(Math.random()*9999),groupName='V341 QA Group '+suffix;
  let z=await json('POST','/api/access/permission-groups-v341',{group_name:groupName,description:'Runtime QA multi-permission group',permissions:{'module.dashboard.view':true,'module.documents.view':true}});if(!z.x.ok||!z.j.group_key)fail('Permission Group create failed',z.j);const groupKey=z.j.group_key;let groups=await get('/api/access/permission-groups-v341'),g=groups.find(x=>x.group_key===groupKey);if(!g||!g.permissions?.['module.dashboard.view']||!g.permissions?.['module.documents.view'])fail('Multi-permission group not retained',g);console.log('PASS multi-permission Permission Group');
  z=await json('PUT',`/api/access/permission-groups-v341/${encodeURIComponent(groupKey)}`,{group_name:groupName,description:'Updated runtime QA group',permissions:{'module.dashboard.view':true,'module.documents.view':true,'module.notifications.view':true}});if(!z.x.ok)fail('Permission Group edit failed',z.j);console.log('PASS Permission Group edit');
  const policyName='V341 QA Policy '+suffix;z=await json('POST','/api/access/policies-v341',{policy_name:policyName,description:'Runtime QA multi-rule policy',business_unit_id:bu.id,rules:[{type:'require_approval_level',module:'dashboard',action:'view',min_level:0,message:'Need configured approval authority.'},{type:'require_permission_group',module:'documents',action:'view',group_key:groupKey,message:'Need QA group.'}]});if(!z.x.ok||!z.j.policy_key)fail('Access Policy create failed',z.j);const policyKey=z.j.policy_key;let policies=await get('/api/access/policies-v341'),p=policies.find(x=>x.policy_key===policyKey);if(!p||p.rules?.length!==2||Number(p.business_unit_id)!==Number(bu.id))fail('Multi-rule policy not retained',p);console.log('PASS multi-rule BU-scoped Access Policy');
  const levels=await get('/api/access/approval-levels-v341');if(levels.length<6||!levels.some(x=>Number(x.level)===5&&Number(x.single_user_allowed)===0))fail('Approval levels incomplete',levels);console.log('PASS L0-L5 Approval Levels');
  const previewBody={business_unit_ids:[bu.id],primary_business_unit_id:bu.id,business_unit_id:bu.id,profiles:[{role_key:profiles[0].role_key,business_unit_id:bu.id,is_primary:true},{role_key:profiles[1].role_key,business_unit_id:bu.id,is_primary:false}],groups:[{group_key:groupKey,business_unit_id:bu.id}]};z=await json('POST','/api/access/preview-v341',previewBody);if(!z.x.ok||!z.j.permissions||!z.j.permission_sources||!z.j.permissions['module.dashboard.view'])fail('Effective Access preview failed',z.j);console.log('PASS Effective Access preview with sources');
  const email=`v341-${suffix}@example.test`,userPassword='Access-QA-'+crypto.randomBytes(10).toString('hex')+'!9a';z=await json('POST','/api/access/users-v341',{name:'V341 Runtime User',email,job_title:'QA Operations Coordinator',password:userPassword,business_unit_ids:[bu.id],primary_business_unit_id:bu.id,profiles:previewBody.profiles,groups:previewBody.groups,approval_level:2,payment_limit:2500000,expense_limit:2000000,approval_limit:2500000});if(!z.x.ok||!z.j.id)fail('Assignment-first user create failed',z.j);const uid=z.j.id;console.log('PASS assignment-first user create');
  const users=await get('/api/users'),u=users.find(x=>Number(x.id)===Number(uid));if(!u||u.job_title!=='QA Operations Coordinator')fail('Job Title not separated/persisted',u);console.log('PASS Job Title separate from system Access Profile');
  const bundle=await get(`/api/access/users/${uid}?business_unit_id=${bu.id}`);if((bundle.profiles||[]).length<2||!(bundle.groups||[]).some(x=>x.group_key===groupKey))fail('Created user profile/group assignments incomplete',bundle);const authRows=bundle.approval_authority||[];if(!authRows.some(x=>Number(x.business_unit_id)===Number(bu.id)&&Number(x.approval_level)===2))fail('Approval Authority missing',authRows);console.log('PASS multiple profiles + group + separate Approval Authority persisted');
  groups=await get('/api/access/permission-groups-v341');g=groups.find(x=>x.group_key===groupKey);if(Number(g?.assigned_users||0)<1)fail('Affected-user count not updated',g);z=await json('POST',`/api/access/permission-groups-v341/${encodeURIComponent(groupKey)}/archive`);if(z.x.status!==409)fail('Assigned Permission Group archive was not protected',{status:z.x.status,body:z.j});console.log('PASS assigned Permission Group archive protection');
  const audit=await get('/api/access/audit-v341?limit=100');if(!audit.some(x=>x.entity==='access_permission_group')||!audit.some(x=>x.entity==='access_policy'))fail('Access Audit missing structural changes',audit.slice(0,10));console.log('PASS Access Audit captures structure changes');
  done=true;console.log('V30.41 ACCESS RUNTIME PASS');process.exitCode=0;
}catch(e){console.error('V30.41 ACCESS RUNTIME FAIL',e);process.exitCode=1}finally{child.kill('SIGTERM');await sleep(150);try{fs.rmSync(temp,{recursive:true,force:true})}catch(_){}}})();
process.on('exit',()=>{if(!done&&child.exitCode===null)try{child.kill('SIGKILL')}catch(_){}});
