'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),cp=require('node:child_process'),assert=require('node:assert/strict'),Database=require('better-sqlite3');
const current=path.resolve(__dirname,'..'),protectedSource=process.env.V357_PROTECTED_SOURCE;
if(!protectedSource||!fs.existsSync(path.join(protectedSource,'server/server.js')))throw Error('Set V357_PROTECTED_SOURCE to the extracted, unmodified protected V30.57.6 source.');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'bom-v357-copy-')),original=path.join(temp,'original'),copy=path.join(temp,'copy');for(const x of [original,copy]){fs.mkdirSync(path.join(x,'data'),{recursive:true});fs.mkdirSync(path.join(x,'uploads'),{recursive:true})}
const secret=crypto.randomBytes(48).toString('hex'),password='BO-'+crypto.randomBytes(12).toString('base64url')+'!9a';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function start(source,directory){const port=33000+Math.floor(Math.random()*5000),env={...process.env,PORT:String(port),JWT_SECRET:secret,ADMIN_EMAIL:'admin@blueocean.local',ADMIN_PASSWORD:password,LOCAL_TEST_MODE:'true',LOCAL_TEST_ADMIN_EMAIL:'admin@blueocean.local',LOCAL_TEST_ADMIN_PASSWORD:password,NODE_ENV:'development',DATA_DIR:path.join(directory,'data'),UPLOAD_DIR:path.join(directory,'uploads'),SEED_DEMO_USERS:'false',SEED_DEMO_DATA:'false'};delete env.V357_PROTECTED_SOURCE;const child=cp.spawn(process.execPath,['server/server.js'],{cwd:source,env,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',x=>output+=x);child.stderr.on('data',x=>output+=x);for(let i=0;i<200;i++){if(output.includes('running on port'))return {child,port};if(child.exitCode!==null)throw Error('Startup failed: '+output.slice(-1200));await sleep(100)}child.kill();throw Error('Startup timeout: '+output.slice(-1200))}
async function stop(s){s.child.kill('SIGTERM');for(let i=0;i<100&&s.child.exitCode===null;i++)await sleep(50);if(s.child.exitCode===null)throw Error('Server did not stop cleanly')}
const digest=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function snapshot(file){const db=new Database(file,{readonly:true,fileMustExist:true});const out={accounts:db.prepare('SELECT id,code,name,account_type,system_key FROM accounting_accounts ORDER BY id').all(),journals:db.prepare('SELECT id,journal_no,business_unit_id,transaction_date,source_type,status FROM accounting_journal_entries ORDER BY id').all(),lines:db.prepare('SELECT journal_entry_id,account_id,business_unit_id,debit_krw,credit_krw FROM accounting_journal_lines ORDER BY id').all(),users:db.prepare('SELECT id,email,role FROM users ORDER BY id').all(),suppliers:db.prepare('SELECT id,business_unit_id,name FROM pink_salt_suppliers ORDER BY id').all(),imports:db.prepare('SELECT id,business_unit_id,import_no,supplier_id,status FROM pink_salt_imports ORDER BY id').all(),items:db.prepare('SELECT id,import_id,line_amount_krw FROM pink_salt_import_items ORDER BY id').all()};db.close();return out}
(async()=>{let server;try{server=await start(protectedSource,original);await stop(server);server=null;const originalDb=path.join(original,'data','blue-ocean.sqlite'),db=new Database(originalDb);const bu=db.prepare("SELECT id FROM business_units WHERE name LIKE '%Pink%' LIMIT 1").get().id,accounts=db.prepare("SELECT id,system_key FROM accounting_accounts WHERE system_key IN ('GENERAL_EXPENSE','CASH_ON_HAND')").all(),keys=Object.fromEntries(accounts.map(x=>[x.system_key,x.id]));assert(keys.GENERAL_EXPENSE&&keys.CASH_ON_HAND);db.prepare("INSERT INTO accounting_journal_entries(journal_no,business_unit_id,transaction_date,source_type,source_id,description,status) VALUES('COPY-MIGRATION-1',?,'2026-09-15','Manual',1,'Protected posted fixture','Posted')").run(bu);const id=db.prepare("SELECT id FROM accounting_journal_entries WHERE journal_no='COPY-MIGRATION-1'").get().id,line=db.prepare('INSERT INTO accounting_journal_lines(journal_entry_id,account_id,business_unit_id,debit_krw,credit_krw) VALUES(?,?,?,?,?)');line.run(id,keys.GENERAL_EXPENSE,bu,100,0);line.run(id,keys.CASH_ON_HAND,bu,0,100);
const supplierId=Number(db.prepare('INSERT INTO pink_salt_suppliers(business_unit_id,name) VALUES(?,?)').run(bu,'Protected copy supplier').lastInsertRowid);
const importId=Number(db.prepare("INSERT INTO pink_salt_imports(business_unit_id,import_no,supplier_id,status,purchase_date,expected_arrival) VALUES(?,? ,?,'Ordered','2026-09-12','2026-09-20')").run(bu,'PROTECTED-IMPORT-1',supplierId).lastInsertRowid);
db.prepare("INSERT INTO pink_salt_import_items(import_id,salt_grade,bag_size_kg,bag_count,total_weight_kg,unit_price_original,line_amount_original,fx_rate_to_krw,line_amount_krw) VALUES(?,'Fine',1,1,1,70,70,1,70)").run(importId);
const transit=db.prepare("SELECT id FROM accounting_accounts WHERE system_key='PINK_SALT_IN_TRANSIT'").get()?.id,payable=db.prepare("SELECT id FROM accounting_accounts WHERE system_key='ACCOUNTS_PAYABLE'").get()?.id;assert(transit&&payable);
const commitment=Number(db.prepare("INSERT INTO accounting_journal_entries(journal_no,business_unit_id,transaction_date,source_type,source_id,description,status) VALUES('COPY-IMPORT-1',?,'2026-09-12','Pink Salt Import Commitment',?,'Protected supplier obligation','Posted')").run(bu,importId).lastInsertRowid);
db.prepare("INSERT INTO accounting_journal_lines(journal_entry_id,account_id,business_unit_id,entity_type,entity_id,debit_krw,credit_krw) VALUES(?,?,?,?,?,?,?)").run(commitment,transit,bu,'Pink Salt Import',importId,70,0);
db.prepare("INSERT INTO accounting_journal_lines(journal_entry_id,account_id,business_unit_id,entity_type,entity_id,debit_krw,credit_krw) VALUES(?,?,?,?,?,?,?)").run(commitment,payable,bu,'Pink Salt Supplier',supplierId,0,70);db.close();const upload=path.join(original,'uploads','existing-evidence.pdf');fs.writeFileSync(upload,'%PDF-1.4\n%synthetic retained evidence\n');const before=snapshot(originalDb),hash=digest(upload);fs.copyFileSync(originalDb,path.join(copy,'data','blue-ocean.sqlite'));fs.copyFileSync(upload,path.join(copy,'uploads','existing-evidence.pdf'));server=await start(current,copy);const health=await fetch(`http://127.0.0.1:${server.port}/api/health`).then(x=>x.json());assert.equal(health.version,'30.58.0');
const base=`http://127.0.0.1:${server.port}`,login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@blueocean.local',password})}),auth=await login.json();assert(login.ok&&auth.token);
const headers={Authorization:'Bearer '+auth.token,'x-business-unit-id':String(bu)};
for(const [url,verify] of [
 ['/api/accounting/v358/source-reconciliation?kind=supplier_payable',x=>x.total===1&&x.rows[0].source_balance_krw===70&&x.rows[0].posted_balance_krw===70&&x.rows[0].status==='Aligned'],
 ['/api/accounting/v358/management-detail?kind=supplier_invoice_aging&as_of=2026-09-30',x=>x.total===1&&x.rows[0].source_outstanding_krw===70&&x.rows[0].aging_bucket==='1-30']]){
 const response=await fetch(base+url,{headers}),result=await response.json();assert(response.ok&&verify(result),`${url}: ${JSON.stringify(result)}`);
}
await stop(server);server=null;const after=snapshot(path.join(copy,'data','blue-ocean.sqlite'));assert.deepEqual(after,before);assert.equal(digest(path.join(copy,'uploads','existing-evidence.pdf')),hash);assert.equal(snapshot(originalDb).journals.length,before.journals.length);
cp.execFileSync(process.execPath,['qa/staging_v358_existing_data.js','--db',originalDb,'--uploads',path.join(original,'uploads'),'--report',path.join(temp,'staging-verifier.json')],{cwd:current,stdio:'pipe',timeout:60000});assert.equal(JSON.parse(fs.readFileSync(path.join(temp,'staging-verifier.json'))).status,'PASS');
console.log('PASS protected-source synthetic existing-data copy: account IDs/codes/meanings, users, posted journals and lines, retained supplier/import source and upload hash, reconciled source/AP and invoice aging, migration/restart, original unchanged');console.log('LIMIT: synthetic retained records only; Render SQLite and representative real uploads were not supplied.');}catch(e){console.error('COPY MIGRATION FAIL',e,e.stderr?.toString());process.exitCode=1}finally{if(server)server.child.kill('SIGTERM');fs.rmSync(temp,{recursive:true,force:true})}})();
