const fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'blue-ocean-v340-access-')),data=path.join(temp,'data'),uploads=path.join(temp,'uploads');fs.mkdirSync(data);fs.mkdirSync(uploads);
const port=34500+Math.floor(Math.random()*800),password='BO-'+crypto.randomBytes(12).toString('base64url')+'!9a',secret=crypto.randomBytes(48).toString('hex');
const env={...process.env,PORT:String(port),JWT_SECRET:secret,ADMIN_EMAIL:'admin@blueocean.local',ADMIN_PASSWORD:password,LOCAL_TEST_MODE:'true',LOCAL_TEST_ADMIN_EMAIL:'admin@blueocean.local',LOCAL_TEST_ADMIN_PASSWORD:password,NODE_ENV:'development',DATA_DIR:data,UPLOAD_DIR:uploads,SEED_DEMO_USERS:'false',SEED_DEMO_DATA:'false'};
const child=cp.spawn(process.execPath,['server/server.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let output='',done=false;child.stdout.on('data',d=>{output+=d;process.stdout.write(d)});child.stderr.on('data',d=>{output+=d;process.stderr.write(d)});const sleep=ms=>new Promise(r=>setTimeout(r,ms));const fail=(m,o)=>{throw new Error(m+(o?': '+JSON.stringify(o):''))};
(async()=>{try{
  for(let i=0;i<150;i++){if(output.includes('running on port'))break;if(child.exitCode!==null)fail('Server exited before startup');await sleep(100)}
  const base=`http://127.0.0.1:${port}`;let r=await fetch(base+'/api/health'),health=await r.json();if(!r.ok||health.version!=='30.40.0')fail('V30.40 health failed',health);console.log('PASS V30.40 runtime health');
  r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@blueocean.local',password})});const login=await r.json();if(!r.ok||!login.token)fail('CEO login failed',login);const auth={Authorization:'Bearer '+login.token},get=async p=>{const x=await fetch(base+p,{headers:auth}),j=await x.json();if(!x.ok)fail('GET '+p,j);return j},json=async(method,p,body)=>{const x=await fetch(base+p,{method,headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify(body||{})});let j={};try{j=await x.json()}catch(_){};return {x,j}};
  const units=await get('/api/business-units');if(units.length<1)fail('No business units');const u1=units[0],u2=units[1]||units[0];const profiles=(await get('/api/access/profiles')).filter(x=>x.role_name!=='CEO / Owner');if(profiles.length<3)fail('Need profile catalog',profiles);const groups=await get('/api/access/permission-groups');if(!groups.length)fail('Need permission groups');console.log('PASS profile/group catalogs');
  const create=async(label)=>{const email=`v340-${label}-${Date.now()}-${Math.floor(Math.random()*9999)}@example.test`,z=await json('POST','/api/users',{name:'V340 '+label,email,password:'Access-QA-'+crypto.randomBytes(8).toString('hex')+'!9a',role:profiles[0].role_name,business_unit_ids:[u1.id,...(u2.id!==u1.id?[u2.id]:[])],primary_business_unit_id:u1.id});if(!z.x.ok||!z.j.id)fail('Create '+label+' failed',z.j);return z.j.id};
  const a=await create('Source'),b=await create('Target');console.log('PASS users created with initial access profile');
  let z=await json('PUT',`/api/access/users/${a}/profiles`,{assignments:[{role_key:profiles[0].role_key,business_unit_id:u1.id,is_primary:true},{role_key:profiles[1].role_key,business_unit_id:u1.id,is_primary:false}]});if(!z.x.ok)fail('Multi-profile assignment failed',z.j);let bundle=await get(`/api/access/users/${a}?business_unit_id=${u1.id}`);if((bundle.profiles||[]).filter(x=>Number(x.business_unit_id)===Number(u1.id)).length<2)fail('Multiple profiles not retained',bundle.profiles);console.log('PASS multiple Access Profiles per user');
  z=await json('PUT',`/api/access/users/${a}/groups`,{assignments:[{group_key:groups[0].group_key,business_unit_id:u1.id}]});if(!z.x.ok)fail('Permission group assignment failed',z.j);bundle=await get(`/api/access/users/${a}?business_unit_id=${u1.id}`);if(!(bundle.groups||[]).some(x=>x.group_key===groups[0].group_key))fail('Permission group not retained',bundle.groups);console.log('PASS scoped Permission Group assignment');
  for(const amount of [1000000,2000000]){z=await json('PUT',`/api/access/users/${a}/approval-authority`,{business_unit_id:null,approval_level:2,payment_limit:amount,expense_limit:amount,approval_limit:amount});if(!z.x.ok)fail('Approval authority save failed',z.j)}bundle=await get(`/api/access/users/${a}`);const globals=(bundle.approval_authority||[]).filter(x=>x.business_unit_id==null);if(globals.length!==1||Number(globals[0].payment_limit)!==2000000)fail('Global approval authority duplicated/not updated',globals);console.log('PASS null-safe global Approval Authority update');
  z=await json('POST','/api/access/users/bulk-profiles',{user_ids:[b],role_key:profiles[2].role_key,business_unit_id:u1.id});if(!z.x.ok)fail('Bulk profile assignment failed',z.j);let bBundle=await get(`/api/access/users/${b}?business_unit_id=${u1.id}`);if(!(bBundle.profiles||[]).some(x=>x.role_key===profiles[2].role_key))fail('Bulk profile missing',bBundle.profiles);console.log('PASS bulk Access Profile assignment');
  z=await json('POST',`/api/access/users/${b}/copy-v340`,{source_user_id:a,copy_business_units:false});if(!z.x.ok)fail('Clone access failed',z.j);bBundle=await get(`/api/access/users/${b}?business_unit_id=${u1.id}`);if((bBundle.profiles||[]).length<2||!(bBundle.groups||[]).some(x=>x.group_key===groups[0].group_key))fail('Cloned access incomplete',bBundle);console.log('PASS clone copies compatible profiles/groups without changing BU scope');
  const effective=await get(`/api/access/users/${b}/effective?business_unit_id=${u1.id}`);if(!effective.permissions||!effective.permission_sources||!(effective.profiles||[]).length)fail('Effective Access source view incomplete',effective);console.log('PASS Effective Access exposes profile/group sources');
  done=true;console.log('V30.40 ACCESS RUNTIME PASS');process.exitCode=0;
}catch(e){console.error('V30.40 ACCESS RUNTIME FAIL',e);process.exitCode=1}finally{child.kill('SIGTERM');await sleep(150);try{fs.rmSync(temp,{recursive:true,force:true})}catch(_){}}})();
process.on('exit',()=>{if(!done&&child.exitCode===null)try{child.kill('SIGKILL')}catch(_){}});
