const fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'blue-ocean-v320-'));
const data=path.join(temp,'data'),uploads=path.join(temp,'uploads');fs.mkdirSync(data);fs.mkdirSync(uploads);
const port=32000+Math.floor(Math.random()*1000);
const smokePassword='BO-'+crypto.randomBytes(12).toString('base64url')+'!9a';
const smokeSecret=crypto.randomBytes(48).toString('hex');
const env={...process.env,PORT:String(port),JWT_SECRET:smokeSecret,ADMIN_EMAIL:'admin@blueocean.local',ADMIN_PASSWORD:smokePassword,LOCAL_TEST_MODE:'true',LOCAL_TEST_ADMIN_EMAIL:'admin@blueocean.local',LOCAL_TEST_ADMIN_PASSWORD:smokePassword,NODE_ENV:'development',DATA_DIR:data,UPLOAD_DIR:uploads,SEED_DEMO_USERS:'false',SEED_DEMO_DATA:'false'};
const child=cp.spawn(process.execPath,['server/server.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});
let output='',done=false;
child.stdout.on('data',d=>{output+=d.toString();process.stdout.write(d)});child.stderr.on('data',d=>{output+=d.toString();process.stderr.write(d)});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const fail=(msg,obj)=>{throw new Error(msg+(obj?': '+JSON.stringify(obj):''))};
(async()=>{try{
  for(let i=0;i<120;i++){if(output.includes('running on port'))break;if(child.exitCode!==null)fail('Server exited before startup');await sleep(100)}
  const base=`http://127.0.0.1:${port}`;
  const health=await fetch(base+'/api/health').then(r=>r.json());if(!health.ok||health.version!=='30.20.0')fail('Health/version check failed',health);console.log('PASS runtime health V30.20.0');
  const login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@blueocean.local',password:smokePassword})});const body=await login.json();if(!login.ok||!body.token||body.user?.role!=='CEO / Owner')fail('Local CEO login smoke failed',body);console.log('PASS runtime local CEO login');
  const auth={'Authorization':'Bearer '+body.token};
  const unitsRes=await fetch(base+'/api/business-units',{headers:auth}),units=await unitsRes.json(),pink=units.find(x=>String(x.name).toLowerCase().includes('pink')&&String(x.name).toLowerCase().includes('salt'));if(!unitsRes.ok||!pink)fail('Pink Salt business unit unavailable',units);const h={...auth,'x-business-unit-id':String(pink.id)};
  const get=async p=>{const r=await fetch(base+p,{headers:h});let j={};try{j=await r.json()}catch(_){}if(!r.ok)fail('GET '+p+' failed',j);return j};
  const json=async(method,p,payload)=>{const r=await fetch(base+p,{method,headers:{...h,'Content-Type':'application/json'},body:JSON.stringify(payload||{})});let j={};try{j=await r.json()}catch(_){}return {r,j}};
  const multipart=async(method,p,fd)=>{const r=await fetch(base+p,{method,headers:h,body:fd});let j={};try{j=await r.json()}catch(_){}return {r,j}};

  // V30.19 System Settings / Administration smoke.
  const catalog=await get('/api/system-settings-v319/catalog');if(catalog.version!=='30.19.0'||!(catalog.sections||[]).some(x=>x.key==='ai_assistant')||!(catalog.sections||[]).some(x=>x.key==='bank_accounts'))fail('V30.19 System Settings catalog failed',catalog);console.log('PASS V30.19 System Settings catalog');
  const overview=await get('/api/system-settings-v319/overview');if(overview.version!=='30.19.0'||!overview.database)fail('V30.19 System Overview failed',overview);console.log('PASS V30.19 System Overview');
  const attachmentPolicy=await get('/api/v320/attachment-policy?business_unit_id='+pink.id);if(attachmentPolicy.preview_before_store!==false||attachmentPolicy.optimize_images!==false||!attachmentPolicy.max_file_size_mb||!attachmentPolicy.max_attachments_per_upload)fail('V30.20 direct attachment policy failed',attachmentPolicy);console.log('PASS V30.20 direct attachment policy');
  const lang=await json('PUT','/api/me/language',{preferred_language:'ko'});if(!lang.r.ok||lang.j.preferred_language!=='ko')fail('Language persistence endpoint failed',lang.j);console.log('PASS persisted language preference endpoint');

  // Critical V30.18 preserved flow under V30.20: Manual proposal -> Posting Control -> Official Ledger.
  const accounts=await get('/api/accounting/accounts');const expense=accounts.find(a=>a.active&&a.allow_manual&&a.system_key==='GENERAL_EXPENSE')||accounts.find(a=>a.active&&a.allow_manual&&a.account_type==='Expense'),cash=accounts.find(a=>a.active&&a.allow_manual&&a.system_key==='CASH_ON_HAND')||accounts.find(a=>a.active&&a.allow_manual&&a.account_type==='Asset');if(!expense||!cash||expense.id===cash.id)fail('Manual-postable accounting accounts unavailable');
  const bankCreate=await json('POST','/api/v320/financial-accounts',{business_unit_id:pink.id,name:'V30.19 Runtime Bank',payment_type:'Bank',currency:'KRW',ledger_account_id:cash.id,bank_name:'Runtime Test Bank',account_holder:'Blue Ocean Market',account_number:'1234567890',account_type:'Current',default_payment:true,default_receipt:true,reason:'Runtime smoke configured payment account'});if(!bankCreate.r.ok||!bankCreate.j.id)fail('Configured Company Bank Account creation failed',bankCreate.j);const bankList=await get('/api/v320/financial-accounts?business_unit_id='+pink.id);if(!bankList.some(x=>Number(x.id)===Number(bankCreate.j.id)&&x.ledger_code))fail('Configured bank account not returned with GL mapping',bankList);console.log('PASS Company Financial Account / GL mapping');
  const cashOpts=await get('/api/v320/financial-accounts/options?business_unit_id='+pink.id+'&method=Cash');if(!(cashOpts.accounts||[]).length||!(cashOpts.accounts||[]).every(x=>x.financial_account_type==='Cash'))fail('Cash smart-account filter failed',cashOpts);const cardOpts=await get('/api/v320/financial-accounts/options?business_unit_id='+pink.id+'&method=Card');if(!(cardOpts.accounts||[]).length||!(cardOpts.accounts||[]).every(x=>x.financial_account_type==='Card'))fail('Card smart-account filter failed',cardOpts);console.log('PASS smart Cash/Card financial-account filtering');
  const before=await get('/api/accounting/trial-balance');const rowOf=(tb,id)=>(tb.rows||[]).find(x=>Number(x.id)===Number(id))||{debit:0,credit:0,balance:0};const beforeExpense=rowOf(before,expense.id),beforeCash=rowOf(before,cash.id),amount=12345;
  const makeManual=async(description,value)=>{const fd=new FormData();fd.set('business_unit_id',String(pink.id));fd.set('transaction_date','2026-09-08');fd.set('description',description);fd.set('reason',description);fd.set('lines_json',JSON.stringify([{account_id:expense.id,debit_krw:value,credit_krw:0,memo:'Runtime smoke debit'},{account_id:cash.id,debit_krw:0,credit_krw:value,memo:'Runtime smoke credit'}]));fd.set('evidence',new Blob(['%PDF-1.4 V30.20 runtime accounting evidence'],{type:'application/pdf'}),'v320-runtime-evidence.pdf');return multipart('POST','/api/accounting/journal',fd)};
  const proposal=await makeManual('V30.20 runtime posting-control proposal',amount);if(!proposal.r.ok||!proposal.j.id||proposal.j.status!=='Pending Review')fail('Manual journal did not enter Pending Review',proposal.j);console.log('PASS manual journal enters Pending Review');
  const detail=await get('/api/accounting/posting-control/'+proposal.j.id);if(detail.journal?.status!=='Pending Review'||!detail.journal?.balanced||!(detail.evidence||[]).length)fail('Posting Control detail/evidence/balance failed',detail);console.log('PASS Posting Control detail is balanced and evidence-backed');
  const pendingTb=await get('/api/accounting/trial-balance');const pendingExpense=rowOf(pendingTb,expense.id),pendingCash=rowOf(pendingTb,cash.id);if(Math.abs(Number(pendingExpense.debit)-Number(beforeExpense.debit))>0.005||Math.abs(Number(pendingCash.credit)-Number(beforeCash.credit))>0.005)fail('Pending proposal leaked into official Trial Balance');console.log('PASS Pending Review excluded from official ledger');
  const posted=await json('POST','/api/accounting/posting-control/'+proposal.j.id+'/post',{note:'Runtime smoke reviewed source, evidence, BU and balanced lines'});if(!posted.r.ok||posted.j.status!=='Posted')fail('Final Posting Control post failed',posted.j);console.log('PASS authorized final post succeeds');
  const after=await get('/api/accounting/trial-balance');const afterExpense=rowOf(after,expense.id),afterCash=rowOf(after,cash.id);if(Math.abs((Number(afterExpense.debit)-Number(beforeExpense.debit))-amount)>0.01||Math.abs((Number(afterCash.credit)-Number(beforeCash.credit))-amount)>0.01)fail('Posted journal did not reach official Trial Balance',{beforeExpense,afterExpense,beforeCash,afterCash});console.log('PASS Posted journal reaches official Trial Balance exactly once');

  // Correction and cancellation of an unposted manual proposal must not affect GL.
  const correctionProposal=await makeManual('V30.20 runtime correction proposal',2222);if(!correctionProposal.r.ok)fail('Second manual proposal failed',correctionProposal.j);const correction=await json('POST','/api/accounting/posting-control/'+correctionProposal.j.id+'/request-correction',{reason:'Runtime smoke correction required'});if(!correction.r.ok||correction.j.status!=='Correction Required')fail('Correction Required workflow failed',correction.j);const correctedTb=await get('/api/accounting/trial-balance');if(Math.abs(Number(rowOf(correctedTb,expense.id).debit)-Number(afterExpense.debit))>0.005)fail('Correction Required proposal leaked into official GL');const cancelled=await json('POST','/api/accounting/posting-control/'+correctionProposal.j.id+'/cancel-proposal',{reason:'Runtime smoke cancel unposted manual proposal'});if(!cancelled.r.ok||cancelled.j.status!=='Cancelled')fail('Manual proposal cancellation failed',cancelled.j);console.log('PASS correction/cancel workflow stays outside official ledger');
  const postingSummary=await get('/api/accounting/posting-control/summary');if(!Object.prototype.hasOwnProperty.call(postingSummary,'pending'))fail('Posting Control summary unavailable',postingSummary);console.log('PASS Posting Control summary API');

  // V2 reconciliation/period-close gate: future no-activity period requires sign-off, then closes, then reopens with reset sign-offs.
  const closePeriod='2099-01';let readiness=await get('/api/accounting/periods/close-readiness?period_key='+closePeriod+'&business_unit_id='+pink.id);if(readiness.ready||!(readiness.checklist||[]).length||!(readiness.blockers||[]).some(x=>String(x).includes('checklist')))fail('Close readiness did not require V2 reconciliation sign-off',readiness);console.log('PASS period close initially blocked by reconciliation checklist');
  for(const item of readiness.checklist){const fd=new FormData();fd.set('period_key',closePeriod);fd.set('business_unit_id',String(pink.id));fd.set('area_key',item.area_key);fd.set('status','Not Applicable');fd.set('notes','Runtime smoke: no activity in future test period');const r=await multipart('POST','/api/accounting/periods/reconciliation-status',fd);if(!r.r.ok)fail('Reconciliation sign-off failed for '+item.area_key,r.j)}
  readiness=await get('/api/accounting/periods/close-readiness?period_key='+closePeriod+'&business_unit_id='+pink.id);if(!readiness.ready)fail('No-activity period did not become close-ready after full sign-off',readiness);console.log('PASS V2 close-readiness controls become ready after sign-off');
  const close=await json('POST','/api/accounting/periods/close',{period_key:closePeriod,business_unit_id:pink.id,notes:'Runtime smoke close after complete reconciliation review'});if(!close.r.ok)fail('Period close failed after readiness',close.j);console.log('PASS reconciled period closes');
  const reopen=await json('POST','/api/accounting/periods/reopen',{period_key:closePeriod,business_unit_id:pink.id,reason:'Runtime smoke authorized reopen'});if(!reopen.r.ok)fail('Period reopen failed',reopen.j);const reopened=await get('/api/accounting/periods/close-readiness?period_key='+closePeriod+'&business_unit_id='+pink.id);if(!(reopened.checklist||[]).every(x=>x.status==='Open'))fail('Reopen did not reset reconciliation sign-offs',reopened.checklist);console.log('PASS authorized reopen resets reconciliation sign-offs');

  done=true;process.exitCode=0;
}catch(e){console.error('RUNTIME SMOKE FAIL',e);process.exitCode=1}finally{child.kill('SIGTERM');await sleep(150);try{fs.rmSync(temp,{recursive:true,force:true})}catch(_){}}})();
process.on('exit',()=>{if(!done&&child.exitCode===null)try{child.kill('SIGKILL')}catch(_){}});
