'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const Database=require('better-sqlite3');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'blue-ocean-v342-')),data=path.join(temp,'data'),uploads=path.join(temp,'uploads');fs.mkdirSync(data);fs.mkdirSync(uploads);
const port=35800+Math.floor(Math.random()*400),password='BO-'+crypto.randomBytes(12).toString('base64url')+'!9a',secret=crypto.randomBytes(48).toString('hex');
const env={...process.env,PORT:String(port),JWT_SECRET:secret,ADMIN_EMAIL:'admin@blueocean.local',ADMIN_PASSWORD:password,LOCAL_TEST_MODE:'true',LOCAL_TEST_ADMIN_EMAIL:'admin@blueocean.local',LOCAL_TEST_ADMIN_PASSWORD:password,NODE_ENV:'development',DATA_DIR:data,UPLOAD_DIR:uploads,SEED_DEMO_USERS:'false',SEED_DEMO_DATA:'false'};
const child=cp.spawn(process.execPath,['server/server.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let output='',done=false;child.stdout.on('data',d=>{output+=d;process.stdout.write(d)});child.stderr.on('data',d=>{output+=d;process.stderr.write(d)});const sleep=ms=>new Promise(r=>setTimeout(r,ms));const fail=(m,o)=>{throw new Error(m+(o?': '+JSON.stringify(o):''))};
(async()=>{try{
  for(let i=0;i<220;i++){if(output.includes('running on port'))break;if(child.exitCode!==null)fail('Server exited before startup');await sleep(100)}
  const base=`http://127.0.0.1:${port}`;let r=await fetch(base+'/api/health'),health=await r.json();if(!r.ok||health.version!=='30.42.0')fail('V30.42 health failed',health);console.log('PASS V30.42 runtime health');
  r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@blueocean.local',password})});const login=await r.json();if(!r.ok||!login.token)fail('CEO login failed',login);const auth={Authorization:'Bearer '+login.token};
  const get=async p=>{const x=await fetch(base+p,{headers:auth}),j=await x.json();if(!x.ok)fail('GET '+p,j);return j};
  const put=async(p,body)=>{const x=await fetch(base+p,{method:'PUT',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify(body)});let j={};try{j=await x.json()}catch(_){};return {x,j}};
  const me=await get('/api/access/me');if(!me.full_system_access||!Object.keys(me.permissions||{}).length)fail('CEO Full System Access missing',me);const units=await get('/api/business-units');if((me.assigned_units||[]).length!==units.length)fail('CEO does not effectively see every BU',{effective:(me.assigned_units||[]).length,units:units.length});console.log('PASS CEO Full System Access + all active Business Units');
  const catalog=await get('/api/access/catalog');if(!Array.isArray(catalog.permissions)||catalog.permissions.length<50)fail('Permission catalog not populated',catalog);if(!catalog.permissions.every(x=>x.permission_key))fail('Permission catalog contains invalid row');console.log('PASS central permission catalog');
  const db=new Database(path.join(data,'blue-ocean.sqlite'));const taskCols=new Set(db.prepare('PRAGMA table_info(tasks)').all().map(x=>x.name));for(const c of ['system_managed','workflow_key','workflow_state','action_key','action_view','action_id','action_enabled','workflow_chain_key'])if(!taskCols.has(c))fail('Missing task workflow column '+c);console.log('PASS actionable task schema');
  const ceo=db.prepare("SELECT id FROM users WHERE role='CEO / Owner' ORDER BY id LIMIT 1").get(),bu=db.prepare("SELECT id FROM business_units WHERE status!='Archived' ORDER BY id LIMIT 1").get();
  const ins=db.prepare(`INSERT INTO tasks(title,owner_id,business_unit_id,priority,status,expected_result,created_by,description,progress_percent,related_module,related_entity_type,related_entity_id,review_required,review_status,assigned_by,system_managed,workflow_key,workflow_state,action_key,action_label,action_view,action_id,action_enabled,source_event,workflow_chain_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
  const tr=ins.run('V30.42 workflow QA',ceo.id,bu.id,'Normal','In Progress','Complete linked workflow',ceo.id,'System-created QA task',0,'Finance','finance_correction',999999,1,'Pending',ceo.id,1,'finance.correction','Action Required','finance.correct_resubmit','Correct & Resubmit','financeCorrectionAction',999999,1,'QA','finance.correction:999999');db.close();
  const detail=await get('/api/tasks/'+tr.lastInsertRowid+'/detail');if(!detail.workflow?.system_managed||detail.workflow?.action?.key!=='finance.correct_resubmit'||detail.workflow?.can_manual_complete!==false)fail('Task workflow payload invalid',detail.workflow);console.log('PASS task-specific action payload');
  const manual=await put('/api/tasks/'+tr.lastInsertRowid,{status:'Completed',progress_percent:100});if(manual.x.status!==409)fail('System task allowed manual completion',{status:manual.x.status,body:manual.j});console.log('PASS system task cannot be manually completed');
  done=true;console.log('V30.42 WORKFLOW RUNTIME PASS');process.exitCode=0;
}catch(e){console.error('V30.42 WORKFLOW RUNTIME FAIL',e);process.exitCode=1}finally{child.kill('SIGTERM');await sleep(150);try{fs.rmSync(temp,{recursive:true,force:true})}catch(_){}}})();
process.on('exit',()=>{if(!done&&child.exitCode===null)try{child.kill('SIGKILL')}catch(_){}});
