'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),cp=require('node:child_process'),assert=require('node:assert/strict'),Database=require('better-sqlite3');
const current=path.resolve(__dirname,'..'),protectedSource=process.env.V357_PROTECTED_SOURCE;
if(!protectedSource||!fs.existsSync(path.join(protectedSource,'server/server.js')))throw Error('Set V357_PROTECTED_SOURCE to the extracted, unmodified protected V30.57.6 source.');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'bom-v357-copy-')),original=path.join(temp,'original'),copy=path.join(temp,'copy');for(const x of [original,copy]){fs.mkdirSync(path.join(x,'data'),{recursive:true});fs.mkdirSync(path.join(x,'uploads'),{recursive:true})}
const secret=crypto.randomBytes(48).toString('hex'),password='BO-'+crypto.randomBytes(12).toString('base64url')+'!9a';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function start(source,directory){const port=33000+Math.floor(Math.random()*5000),env={...process.env,PORT:String(port),JWT_SECRET:secret,ADMIN_EMAIL:'admin@blueocean.local',ADMIN_PASSWORD:password,LOCAL_TEST_MODE:'true',LOCAL_TEST_ADMIN_EMAIL:'admin@blueocean.local',LOCAL_TEST_ADMIN_PASSWORD:password,NODE_ENV:'development',DATA_DIR:path.join(directory,'data'),UPLOAD_DIR:path.join(directory,'uploads'),SEED_DEMO_USERS:'false',SEED_DEMO_DATA:'false'};delete env.V357_PROTECTED_SOURCE;const child=cp.spawn(process.execPath,['server/server.js'],{cwd:source,env,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',x=>output+=x);child.stderr.on('data',x=>output+=x);for(let i=0;i<200;i++){if(output.includes('running on port'))return {child,port};if(child.exitCode!==null)throw Error('Startup failed: '+output.slice(-1200));await sleep(100)}child.kill();throw Error('Startup timeout: '+output.slice(-1200))}
async function stop(s){s.child.kill('SIGTERM');for(let i=0;i<100&&s.child.exitCode===null;i++)await sleep(50);if(s.child.exitCode===null)throw Error('Server did not stop cleanly')}
const digest=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function snapshot(file){const db=new Database(file,{readonly:true,fileMustExist:true});const out={accounts:db.prepare('SELECT id,code,name,account_type,system_key FROM accounting_accounts ORDER BY id').all(),journals:db.prepare('SELECT id,journal_no,business_unit_id,transaction_date,source_type,status FROM accounting_journal_entries ORDER BY id').all(),lines:db.prepare('SELECT journal_entry_id,account_id,business_unit_id,debit_krw,credit_krw FROM accounting_journal_lines ORDER BY id').all(),users:db.prepare('SELECT id,email,role FROM users ORDER BY id').all()};db.close();return out}
(async()=>{let server;try{server=await start(protectedSource,original);await stop(server);server=null;const originalDb=path.join(original,'data','blue-ocean.sqlite'),db=new Database(originalDb);const bu=db.prepare("SELECT id FROM business_units WHERE name LIKE '%Pink%' LIMIT 1").get().id,accounts=db.prepare("SELECT id,system_key FROM accounting_accounts WHERE system_key IN ('GENERAL_EXPENSE','CASH_ON_HAND')").all(),keys=Object.fromEntries(accounts.map(x=>[x.system_key,x.id]));assert(keys.GENERAL_EXPENSE&&keys.CASH_ON_HAND);db.prepare("INSERT INTO accounting_journal_entries(journal_no,business_unit_id,transaction_date,source_type,source_id,description,status) VALUES('COPY-MIGRATION-1',?,'2026-09-15','Manual',1,'Protected posted fixture','Posted')").run(bu);const id=db.prepare("SELECT id FROM accounting_journal_entries WHERE journal_no='COPY-MIGRATION-1'").get().id,line=db.prepare('INSERT INTO accounting_journal_lines(journal_entry_id,account_id,business_unit_id,debit_krw,credit_krw) VALUES(?,?,?,?,?)');line.run(id,keys.GENERAL_EXPENSE,bu,100,0);line.run(id,keys.CASH_ON_HAND,bu,0,100);db.close();const upload=path.join(original,'uploads','existing-evidence.pdf');fs.writeFileSync(upload,'%PDF-1.4\n%synthetic retained evidence\n');const before=snapshot(originalDb),hash=digest(upload);fs.copyFileSync(originalDb,path.join(copy,'data','blue-ocean.sqlite'));fs.copyFileSync(upload,path.join(copy,'uploads','existing-evidence.pdf'));server=await start(current,copy);const health=await fetch(`http://127.0.0.1:${server.port}/api/health`).then(x=>x.json());assert.equal(health.version,'30.57.7');await stop(server);server=null;const after=snapshot(path.join(copy,'data','blue-ocean.sqlite'));assert.deepEqual(after,before);assert.equal(digest(path.join(copy,'uploads','existing-evidence.pdf')),hash);assert.equal(snapshot(originalDb).journals.length,before.journals.length);console.log('PASS protected-source synthetic existing-data copy: account IDs/codes/meanings, users, posted journal and lines, upload hash, migration/restart, original unchanged');console.log('LIMIT: synthetic source data only; Render SQLite and representative real uploads were not supplied.');}catch(e){console.error('COPY MIGRATION FAIL',e);process.exitCode=1}finally{if(server)server.child.kill('SIGTERM');fs.rmSync(temp,{recursive:true,force:true})}})();
