'use strict';
// Read-only source inspection, consistent SQLite backup, isolated V30.58 startup, retained-row comparison.
// Usage: node qa/staging_v358_existing_data.js --db /path/to/blue-ocean.sqlite --uploads /path/to/uploads --report /safe/path/report.json
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),cp=require('node:child_process');
const Database=require('better-sqlite3'),jwt=require('jsonwebtoken');
const root=path.resolve(__dirname,'..'),args=process.argv.slice(2),option=n=>{const i=args.indexOf(n);return i<0?null:args[i+1]};
const dbPath=option('--db'),uploads=option('--uploads'),reportPath=option('--report');
if(!dbPath||!uploads||!reportPath||!fs.statSync(dbPath,{throwIfNoEntry:false})?.isFile()||!fs.statSync(uploads,{throwIfNoEntry:false})?.isDirectory()){
 console.error('Supply an existing SQLite file, matching uploads directory and a report path: --db FILE --uploads DIR --report FILE');process.exit(2);
}
const reportAbsolute=path.resolve(reportPath),dataDirectory=path.dirname(path.resolve(dbPath)),uploadDirectory=path.resolve(uploads);
if(reportAbsolute===path.resolve(dbPath)||reportAbsolute.startsWith(dataDirectory+path.sep)||reportAbsolute===uploadDirectory||reportAbsolute.startsWith(uploadDirectory+path.sep)){
 console.error('The report must be outside the source database and uploads directories.');process.exit(2);
}
const protectedTables=['accounting_accounts','accounting_journal_entries','accounting_journal_lines','accounting_payment_accounts','accounting_bank_statement_lines','finance_entries','business_units','users','excavator_assets','excavator_suppliers','excavator_buyers','excavator_buyer_payments','excavator_buyer_payment_allocations','excavator_buyer_refunds','pink_salt_suppliers','pink_salt_imports','pink_salt_import_items','pink_salt_import_payments','pink_salt_supplier_advances','pink_salt_supplier_advance_allocations','pink_salt_supplier_packaging_allocations','pink_salt_packaging_movements','pink_salt_orders','pink_salt_customer_payments','pink_salt_customer_receipts','pink_salt_customer_receipt_allocations','pink_salt_customer_refunds','payroll_runs','payroll_payments','fixed_assets','loan_agreements','lease_agreements'];
const quote=x=>'"'+String(x).replaceAll('"','""')+'"',hash=()=>crypto.createHash('sha256'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function capture(file,prior){const db=new Database(file,{readonly:true,fileMustExist:true});try{
 const integrity=db.pragma('integrity_check',{simple:true});if(integrity!=='ok')throw Error('SQLite integrity check failed');
 const tables={};for(const name of protectedTables){const exists=db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name);if(!exists){if(prior?.[name])throw Error('Protected table removed: '+name);continue}
  const columns=prior?.[name]?.columns||db.pragma(`table_info(${quote(name)})`).map(x=>x.name),key=columns.includes('id')?'id':'rowid',ident=key==='rowid'?'rowid':quote(key),rows=new Map();
  const sql=`SELECT ${ident} _snapshot_id,${columns.map(quote).join(',')} FROM ${quote(name)} ORDER BY ${ident}`;
  for(const row of db.prepare(sql).iterate()){const id=String(row._snapshot_id);delete row._snapshot_id;rows.set(id,{digest:hash().update(JSON.stringify(row)).digest('hex'),values:row})}
  tables[name]={columns,rows};
 }
 const balances=db.prepare("SELECT l.account_id,l.business_unit_id,ROUND(SUM(l.debit_krw-l.credit_krw),2) balance FROM accounting_journal_lines l JOIN accounting_journal_entries j ON j.id=l.journal_entry_id WHERE j.status IN ('Posted','Reversed') GROUP BY l.account_id,l.business_unit_id ORDER BY l.account_id,l.business_unit_id").all();
 return {tables,balances,integrity};
}finally{db.close()}}
function compare(baseline,after){const changes=[];for(const [name,a] of Object.entries(baseline.tables)){const b=after.tables[name];if(!b){changes.push({table:name,missing_table:true});continue}let missing=0,changed=0,added=0;const fields=new Set();for(const [id,h] of a.rows){const newer=b.rows.get(id);if(!newer)missing++;else if(newer.digest!==h.digest){changed++;for(const k of Object.keys(h.values))if(JSON.stringify(h.values[k])!==JSON.stringify(newer.values[k]))fields.add(k)}}for(const id of b.rows.keys())if(!a.rows.has(id))added++;if(missing||changed||added)changes.push({table:name,missing,changed,added,...(fields.size?{changed_fields:[...fields]}:{})})}return changes}
function uploadDigest(dir){const digest=hash();let files=0;function walk(base,relative=''){for(const item of fs.readdirSync(base,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const name=path.posix.join(relative,item.name),absolute=path.join(base,item.name);if(item.isSymbolicLink())throw Error('Uploads contain a symlink: '+name);if(item.isDirectory())walk(absolute,name);else if(item.isFile()){files++;digest.update(name+'\0');digest.update(hash().update(fs.readFileSync(absolute)).digest());}else throw Error('Unsupported upload entry: '+name)}}walk(dir);return {files,sha256:digest.digest('hex')}}
async function start(copy,secret){const port=35000+crypto.randomInt(10000),env={...process.env,PORT:String(port),JWT_SECRET:secret,NODE_ENV:'development',DATA_DIR:path.join(copy,'data'),UPLOAD_DIR:path.join(copy,'uploads'),LOCAL_TEST_MODE:'false',SEED_DEMO_USERS:'false',SEED_DEMO_DATA:'false'};delete env.V357_PROTECTED_SOURCE;
 const child=cp.spawn(process.execPath,['server/server.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',x=>output=(output+x).slice(-4000));child.stderr.on('data',x=>output=(output+x).slice(-4000));
 for(let i=0;i<200;i++){if(output.includes('running on port'))return {child,port};if(child.exitCode!==null)throw Error('Isolated startup failed: '+output.slice(-1000));await sleep(100)}child.kill('SIGTERM');throw Error('Isolated startup timed out: '+output.slice(-1000));
}
async function stop(server){server.child.kill('SIGTERM');for(let i=0;i<100&&server.child.exitCode===null;i++)await sleep(50);if(server.child.exitCode===null)throw Error('Isolated server did not stop cleanly')}
async function review(server,dbFile,secret){const base=`http://127.0.0.1:${server.port}`,health=await fetch(base+'/api/health').then(r=>r.json());if(health.version!=='30.59.0')throw Error('Wrong isolated version');const db=new Database(dbFile,{readonly:true,fileMustExist:true});let user,unit;try{user=db.prepare("SELECT id,name,email,role,business_unit_id,COALESCE(auth_version,1) auth_version FROM users WHERE role='CEO / Owner' AND active=1 ORDER BY id LIMIT 1").get();unit=db.prepare("SELECT id FROM business_units WHERE status!='Archived' ORDER BY id LIMIT 1").get()}finally{db.close()}
 const checks=['health 30.59.0'];if(!user)return {checks,warning:'No active CEO/Owner in copy; authenticated read views were not exercised'};
 const token=jwt.sign({id:user.id,name:user.name,email:user.email,role:user.role,business_unit_id:user.business_unit_id,auth_version:Number(user.auth_version||1)},secret,{expiresIn:'10m'}),headers={Authorization:'Bearer '+token,...(unit?{'x-business-unit-id':String(unit.id)}:{})};
 const date=new Date().toISOString().slice(0,10),from=date.slice(0,7)+'-01';
 const paths=[`/api/accounting/v358/statements?from=${from}&to=${date}`,'/api/accounting/v358/source-reconciliation?kind=all&page=1&page_size=25',`/api/accounting/v358/management-detail?kind=invoice_aging&as_of=${date}`,`/api/accounting/v358/management-detail?kind=supplier_invoice_aging&as_of=${date}`,`/api/accounting/v358/year-end-readiness?year=${date.slice(0,4)}`];
 for(const p of paths){const response=await fetch(base+p,{headers});if(!response.ok){const body=await response.json().catch(()=>({}));throw Error(`Isolated Accounting GET ${p} returned ${response.status}: ${String(body.error||'')}`)}const body=await response.json();if((p.includes('management-detail')||p.includes('source-reconciliation'))&&!Array.isArray(body.rows))throw Error('Invalid read response for '+p);checks.push(p.split('?')[0])}return {checks};
}
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'bom-v358-existing-copy-')),copyDb=path.join(temp,'data','blue-ocean.sqlite'),copyUploads=path.join(temp,'uploads'),result={version:'30.59.0',checked_at:new Date().toISOString(),scope:'isolated copy; supplied source opened read-only',status:'FAIL',checks:[],differences:[]};let server;
 try{fs.mkdirSync(path.dirname(copyDb),{recursive:true});const beforeSource=capture(dbPath),sourceUpload=uploadDigest(uploads),source=new Database(dbPath,{readonly:true,fileMustExist:true});try{await source.backup(copyDb)}finally{source.close()}
  const beforeCopy=capture(copyDb);if(compare(beforeSource,beforeCopy).length||JSON.stringify(beforeSource.balances)!==JSON.stringify(beforeCopy.balances))throw Error('Source changed during backup; use a consistent quiescent copy');
  fs.cpSync(uploads,copyUploads,{recursive:true});if(JSON.stringify(sourceUpload)!==JSON.stringify(uploadDigest(copyUploads)))throw Error('Upload copy differs from source');
  const secret=crypto.randomBytes(48).toString('hex');server=await start(temp,secret);const read=await review(server,copyDb,secret);result.checks=read.checks;if(read.warning)result.warning=read.warning;await stop(server);server=null;
  const after=capture(copyDb,beforeCopy.tables),originalAfter=capture(dbPath,beforeSource.tables),allChanges=compare(beforeCopy,after);
  // V30.15 derives supplier categories from existing activity on startup. Record that metadata
  // change separately; never exempt IDs, names, amounts, status, journal rows or evidence.
  const derivedCategory=x=>x.table==='pink_salt_suppliers'&&!x.missing&&!x.added&&x.changed_fields?.length===1&&x.changed_fields[0]==='supplier_categories_json';
  result.derived_metadata_changes=allChanges.filter(derivedCategory);result.differences=allChanges.filter(x=>!derivedCategory(x));result.source_unchanged=compare(beforeSource,originalAfter).length===0&&JSON.stringify(beforeSource.balances)===JSON.stringify(originalAfter.balances);result.gl_balances_unchanged=JSON.stringify(beforeCopy.balances)===JSON.stringify(after.balances);result.uploads_unchanged=JSON.stringify(sourceUpload)===JSON.stringify(uploadDigest(uploads))&&JSON.stringify(sourceUpload)===JSON.stringify(uploadDigest(copyUploads));result.upload_count=sourceUpload.files;result.protected_table_counts=Object.fromEntries(Object.entries(beforeCopy.tables).map(([name,x])=>[name,x.rows.size]));
  result.status=result.source_unchanged&&result.gl_balances_unchanged&&result.uploads_unchanged&&result.differences.length===0?'PASS':'REVIEW REQUIRED';
 }catch(e){result.error=e.message;process.exitCode=1}finally{if(server)server.child.kill('SIGTERM');fs.mkdirSync(path.dirname(path.resolve(reportPath)),{recursive:true});fs.writeFileSync(reportPath,JSON.stringify(result,null,2)+'\n');fs.rmSync(temp,{recursive:true,force:true})}
 if(result.status!=='PASS'){console.error('V30.58 existing-data staging:',result.status,result.error||JSON.stringify(result.differences));process.exitCode=1}else console.log('PASS V30.58 existing-data isolated copy; retained records, posted balances and uploads unchanged; report:',reportPath);
})().catch(e=>{console.error(e);process.exitCode=1});
